/*!
 * LMV v7.17.1
 * 
 * Copyright 2020 Autodesk, Inc.
 * All rights reserved.
 * 
 * This computer source code and related instructions and comments are the
 * unpublished confidential and proprietary information of Autodesk, Inc.
 * and are protected under Federal copyright and state trade secret law.
 * They may not be disclosed to, copied or used by any third party without
 * the prior written consent of Autodesk, Inc.
 * 
 * Autodesk Forge Viewer Usage Limitations:
 * 
 * The Autodesk Forge viewer can only be used to view files generated by
 * Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be
 * delivered from an Autodesk hosted URL.
 */
Autodesk.Extensions.Fusion360 =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./extensions/Fusion360/AnimationExtension.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./extensions/Fusion360/AnimationExtension.js":
/*!****************************************************!*\
  !*** ./extensions/Fusion360/AnimationExtension.js ***!
  \****************************************************/
/*! exports provided: ANIMATION_PLAY_EVENT, ANIMATION_PAUSE_EVENT, ANIMATION_SEEK_EVENT, ANIMATION_PREVIOUS_FRAME_EVENT, ANIMATION_NEXT_FRAME_EVENT, ANIMATION_TRACK_UPDATE_EVENT, ANIMATION_TOOLBAR_CLOSE_EVENT, AnimationExtension */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_PLAY_EVENT", function() { return ANIMATION_PLAY_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_PAUSE_EVENT", function() { return ANIMATION_PAUSE_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_SEEK_EVENT", function() { return ANIMATION_SEEK_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_PREVIOUS_FRAME_EVENT", function() { return ANIMATION_PREVIOUS_FRAME_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_NEXT_FRAME_EVENT", function() { return ANIMATION_NEXT_FRAME_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_TRACK_UPDATE_EVENT", function() { return ANIMATION_TRACK_UPDATE_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ANIMATION_TOOLBAR_CLOSE_EVENT", function() { return ANIMATION_TOOLBAR_CLOSE_EVENT; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AnimationExtension", function() { return AnimationExtension; });
/* harmony import */ var _AnimationToolbar_css__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./AnimationToolbar.css */ "./extensions/Fusion360/AnimationToolbar.css");
/* harmony import */ var _AnimationToolbar_css__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_AnimationToolbar_css__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var _AnimationPanel__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./AnimationPanel */ "./extensions/Fusion360/AnimationPanel.js");
/* harmony import */ var _AnimationLocales__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./AnimationLocales */ "./extensions/Fusion360/AnimationLocales.js");
var av = Autodesk.Viewing;
var avp = Autodesk.Viewing.Private;
var avu = Autodesk.Viewing.UI;

var ToolBar = avu.ToolBar;
var ControlGroup = avu.ControlGroup;
var Button = avu.Button;
var Control = avu.Control;
var TOOLBAR = av.TOOLBAR;
var isTouchDevice = avp.isTouchDevice;
var isIE11 = avp.isIE11;

var ANIMATION_PLAY_EVENT = 'animationPlayEvent';
var ANIMATION_PAUSE_EVENT = 'animationPauseEvent';
var ANIMATION_SEEK_EVENT = 'animationSeekEvent';
var ANIMATION_PREVIOUS_FRAME_EVENT = 'animationPreviousFrameEvent';
var ANIMATION_NEXT_FRAME_EVENT = 'animationNextFrameEvent';
var ANIMATION_TRACK_UPDATE_EVENT = 'animationTrackUpdateEvent';
var ANIMATION_TOOLBAR_CLOSE_EVENT = 'animationToolbarCloseEvent';





var SETTINGS_BUTTON_LABEL = 'Animation';

//TODO: These exports into the global namespace seem to only be used by unit tests
av.ANIMATION_PLAY_EVENT = ANIMATION_PLAY_EVENT;
av.ANIMATION_PAUSE_EVENT = ANIMATION_PAUSE_EVENT;
av.ANIMATION_SEEK_EVENT = ANIMATION_SEEK_EVENT;
av.ANIMATION_PREVIOUS_FRAME_EVENT = ANIMATION_PREVIOUS_FRAME_EVENT;
av.ANIMATION_NEXT_FRAME_EVENT = ANIMATION_NEXT_FRAME_EVENT;
av.ANIMATION_TRACK_UPDATE_EVENT = ANIMATION_TRACK_UPDATE_EVENT;
av.ANIMATION_TOOLBAR_CLOSE_EVENT = ANIMATION_TOOLBAR_CLOSE_EVENT;

/**
                                                                   * 
                                                                   * AnimationExtension adds a toolbar with buttons (play/pause/forward/backward/goto start/end)
                                                                   * and timeline scrubber to control animation playback. 
                                                                   * The extension provides api methods that will be reflected by the animation toolbar.
                                                                   * 
                                                                   * The extension id is: `Autodesk.Fusion360.Animation`
                                                                   * 
                                                                   * @example
                                                                   *   viewer.loadExtension('Autodesk.Fusion360.Animation')
                                                                   * 
                                                                   * @memberof Autodesk.Viewing.Extensions
                                                                   * @alias Autodesk.Viewing.Extensions.AnimationExtension
                                                                   * @see {@link Autodesk.Viewing.Extension} for common inherited methods.
                                                                   * @constructor
                                                                   */
function AnimationExtension(viewer, options) {
  av.Extension.call(this, viewer, options);
  this.viewer = viewer;
  this.animTools = null;
  this.animToolsId = "animationTools";
  this.playButton = null;
  this.playButtonIsPaused = true;
  this.prevAnimationTime = -1;
  this.name = 'fusionanimation';
  this._configButtonId = null;
  this._panel = null;

  this._onGeomAndObjTreeReady = this._onGeomAndObjTreeReady.bind(this);
  this.openPanel = this.openPanel.bind(this);
  this._onPlayCallback = this._onPlayCallback.bind(this);
  this._onCameraChange = this._onCameraChange.bind(this);
  this._onExplode = this._onExplode.bind(this);
  this._onResize = this._onResize.bind(this);
  this._onEscape = this._onEscape.bind(this);

  this._toolbarReady = false;
  this._animationReady = false;
}

AnimationExtension.prototype = Object.create(av.Extension.prototype);
AnimationExtension.prototype.constructor = AnimationExtension;

/**
                                                                * Converts seconds into Hours:Minutes:Seconds String
                                                                * @param {Number} time in seconds
                                                                * @returns {string}
                                                                * @private
                                                                */
function convertSecsToHMS(time) {
  var sign = "";
  if (time < 0) {sign = "-";time = -time;}
  var hrs = ~~(time / 3600);
  var mins = ~~(time % 3600 / 60);
  var secs = time % 60;
  var ret = sign;
  if (hrs > 0)
  ret += hrs + ":" + (mins < 10 ? "0" : "");
  ret += mins + ":" + (secs < 10 ? "0" : "");
  ret += secs.toFixed(2);
  return ret;
}

/**
   * Adds a toolbar button and hooks animation listeners.
   * 
   * @alias Autodesk.Viewing.Extensions.AnimationExtension#load
   */
AnimationExtension.prototype.load = function () {

  this.extendLocalization(_AnimationLocales__WEBPACK_IMPORTED_MODULE_2__["locales"]);

  this._initAnim = false;
  if (this._canAnimationInitialize()) {
    this._initAnimations({ model: this.viewer.model });
  } else {
    this.viewer.addEventListener(av.GEOMETRY_LOADED_EVENT, this._onGeomAndObjTreeReady, { once: true });
    this.viewer.addEventListener(av.OBJECT_TREE_CREATED_EVENT, this._onGeomAndObjTreeReady, { once: true });
  }

  return true;
};

/**
    * @private
    */
AnimationExtension.prototype._canAnimationInitialize = function () {
  return this.viewer.model && this.viewer.model.isLoadDone() && this.viewer.model.isObjectTreeCreated();
};

/**
    * @private
    */
AnimationExtension.prototype._onGeomAndObjTreeReady = function () {
  if (!this._initAnim && this._canAnimationInitialize()) {
    this._initAnimations({ model: this.viewer.model });
    this._initAnim = true;
  }
};

/**
    * @private
    */
AnimationExtension.prototype._initAnimations = function (event) {

  // Animations are available as soon as the model instance is created.
  var model = event.model;
  var animations = model.getData().animations;
  if (!animations) {
    return;
  }

  // init animations after geometry loaded
  var impl = this.viewer.impl;
  impl.keyFrameAnimator = new avp.KeyFrameAnimator(impl, animations.duration);
  for (var a in animations.animations) {
    impl.keyFrameAnimator.add(animations.animations[a]);
  }
  impl.keyFrameAnimator.goto(0);

  this.viewer.addEventListener(av.CAMERA_CHANGE_EVENT, this._onCameraChange);
  this.viewer.addEventListener(av.EXPLODE_CHANGE_EVENT, this._onExplode);
  this.viewer.addEventListener(av.ESCAPE_EVENT, this._onEscape);

  this._onAnimationReady();
  this.viewer.dispatchEvent({ type: av.ANIMATION_READY_EVENT });
};

/**
    * Removes toobar button and unhooks animation listeners.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#unload
    */
AnimationExtension.prototype.unload = function () {

  var viewer = this.viewer;
  viewer.removeEventListener(av.GEOMETRY_LOADED_EVENT, this._onGeomAndObjTreeReady);
  viewer.removeEventListener(av.OBJECT_TREE_CREATED_EVENT, this._onGeomAndObjTreeReady);
  viewer.removeEventListener(av.CAMERA_CHANGE_EVENT, this._onCameraChange);
  viewer.removeEventListener(av.EXPLODE_CHANGE_EVENT, this._onExplode);
  viewer.removeEventListener(av.VIEWER_RESIZE_EVENT, this._onResize);
  viewer.removeEventListener(av.ESCAPE_EVENT, this._onEscape);

  // stop animations
  this.rewind();
  viewer.impl.invalidate(true, true, true); // Required to reset animations when Extension unloads and viewer remains.

  if (this.animTools) {
    this.animTools.removeControl(this.animTools.timeText.getId());
    this.animTools.removeControl(this.animTools.timeline.getId());
    this.animTools.removeControl(this.animTools.timeLeftText.getId());
    this.animTools.removeControl(this.animTools.forwardButton.getId());
    this.animTools.removeControl(this.animTools.backwardButton.getId());
    this.animTools.removeControl(this.animTools.closeButton.getId());
  }

  if (this.toolbar) {
    this.toolbar.removeControl(this.animTools);
    this.toolbar.container.parentNode.removeChild(this.toolbar.container);
    this.toolbar = null;
  }

  if (this.playButton) {
    var viewerToolbar = viewer.getToolbar();
    if (viewerToolbar) {
      viewerToolbar.getControl(TOOLBAR.MODELTOOLSID).removeControl(this.playButton.getId());
    }
  }

  if (this._configButtonId !== null) {
    var settingsPanel = this.viewer.getSettingsPanel();
    settingsPanel && settingsPanel.removeConfigButton(this._configButtonId);
    this._configButtonId = null;
  }

  if (this._panel) {
    this._panel.uninitialize();
    this._panel = null;
  }

  this._toolbarReady = false;
  this._animationReady = false;

  return true;
};

/**
    * Plays the animation. Invoke pause() to stop the animation.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#play
    */
AnimationExtension.prototype.play = function () {

  if (this.isPlaying()) {
    return;
  }

  this.resetExplode(0, true);

  var viewer = this.viewer;
  var animator = viewer.impl.keyFrameAnimator;
  if (!animator) return;

  // restore previous animation if set
  if (this.prevAnimationTime > 0) {
    animator.goto(this.prevAnimationTime);
    this.prevAnimationTime = -1;
  }

  animator.play(0, this._onPlayCallback);

  this.updatePlayButton(animator.isPaused);

  if (this.animTools) {
    this.animTools.setVisible(true);
    if (!this.animTools.isPositionAdjusted) {
      this.adjustToolbarPosition();
      this.animTools.isPositionAdjusted = true;
    }
  }
};

/**
    * Pauses an active animation. Can resume by invoking play()
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#pause
    */
AnimationExtension.prototype.pause = function () {

  if (this.isPaused()) {
    return;
  }

  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return;
  animator.pause();

  // UI stuff
  this.updatePlayButton(animator.isPaused);
};

/**
    * Whether the animation is currently playing.
    * Always returns the opposite of isPaused()
    * @returns {Boolean}
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#isPlaying
    */
AnimationExtension.prototype.isPlaying = function () {

  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return false;
  return animator.isPlaying && !animator.isPaused;
};

/**
    * Wether the animation is currently paused.
    * Always returns the opposite of isPlaying()
    * @returns {Boolean}
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#isPaused
    */
AnimationExtension.prototype.isPaused = function () {

  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return false;
  return animator.isPaused;
};

/**
    * Rewinds and pauses the animation.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#rewind
    */
AnimationExtension.prototype.rewind = function () {
  this.setTimelineValue(0);
};

/**
    * Sets the animation at the very beginning (0), at the end(1) or anywhere in between.
    * For example, use value 0.5 to set the animation half way through it's completion.
    * Will pause a playing animation.
    *
    * @param {Number} scale - value between 0 and 1
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#setTimelineValue
    */
AnimationExtension.prototype.setTimelineValue = function (scale) {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return;
  scale = Math.min(Math.max(0, scale), 1);
  var time = scale * animator.duration;
  animator.goto(time);
  this.updateUI();
};

/**
    * Sets animation onto the previous keyframe.
    * Will pause the animation if playing.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#prevKeyframe
    */
AnimationExtension.prototype.prevKeyframe = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return;
  animator.prev();
  this.updateUI();
};

/**
    * Sets animation onto the next keyframe.
    * Will pause the animation if playing.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#nextKeyframe
    */
AnimationExtension.prototype.nextKeyframe = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return;
  animator.next();
  this.updateUI();
};

/**
    * Returns how many seconds does the animation take to complete.
    * @return {Number}
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#getDuration
    */
AnimationExtension.prototype.getDuration = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return 0;
  return animator.duration;
};

/**
    * Returns duration as a formatted String h:mm:ss (hours:minutes:seconds)
    * @returns {string}
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#getDurationLabel
    */
AnimationExtension.prototype.getDurationLabel = function () {
  return convertSecsToHMS(this.getDuration());
};

/**
    * Returns the elapsed time (in seconds) of the animation.
    * @return {Number}
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#getCurrentTime
    */
AnimationExtension.prototype.getCurrentTime = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator) return 0;
  return animator.currentTime;
};

/**
    * Returns the current animation time as a formatted String h:mm:ss (hours:minutes:seconds)
    * @returns {string}
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#getCurrentTimeLabel
    */
AnimationExtension.prototype.getCurrentTimeLabel = function () {
  return convertSecsToHMS(this.getCurrentTime());
};

/**
    * Whether a playing animation updates the camera position.
    * 
    * @param {boolean} followCam - true to allow animation to update camera position (default behavior).
    * 
    * @returns {boolean} true if the operation was successful.
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#setFollowCamera
    */
AnimationExtension.prototype.setFollowCamera = function (followCam) {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator)
  return false;

  animator.setFollowCamera(followCam || false);
  return true;
};

/**
    * @returns {boolean} Whether animations will update the camera's position (true) or not (false)
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#isFollowingCamera
    */
AnimationExtension.prototype.isFollowingCamera = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator)
  return true; // default behavior is following the camera

  return animator.isFollowingCamera();
};

/**
    * Changes the speed at which the animation is played. Use value 1 to run the 
    * animation at default speed, use value 2 to run it at double the speed, 
    * use value 0.5 to run it at half the speed.
    * 
    * @param {number} value - A multiplier for the animation's elapsed time.
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#setSpeedModifier
    */
AnimationExtension.prototype.setSpeedModifier = function (value) {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator)
  return false;

  animator.setSpeedModifier(value);
  return true;
};

/**
    * @returns {number} The playback speed multiplier.
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#getSpeedModifier
    */
AnimationExtension.prototype.getSpeedModifier = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator)
  return 1;

  return animator.getSpeedModifier();
};

/**
    * Sets whether the animation rewinds and plays as soon as the animation
    * finishes playing.
    * 
    * @param {boolean} loop - true to have the animation loop continuously.
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#setLooping
    */
AnimationExtension.prototype.setLooping = function (loop) {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator)
  return false;

  animator.setLooping(loop);
  return true;
};

/**
    * @returns {boolean} Whether the animation will loop continuously.
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#isLooping
    */
AnimationExtension.prototype.isLooping = function () {
  var animator = this.viewer.impl.keyFrameAnimator;
  if (!animator)
  return 1;

  return animator.isLooping();
};


/**
    * @private
    */
AnimationExtension.prototype._onAnimationReady = function () {

  // Check for animator class
  if (!this.viewer.impl.keyFrameAnimator) {
    return;
  }

  this._animationReady = true;
  this._initUI();
};

/**
    *
    * @private
    */
AnimationExtension.prototype.updateUI = function () {

  var animator = this.viewer.impl.keyFrameAnimator;
  if (!this.animTools || !animator) {
    return;
  }
  this.animTools.input.value = animator.duration > 0 ? animator.currentTime / animator.duration * 100 : 0;
  this.animTools.lapse.value = convertSecsToHMS(animator.currentTime);
  this.animTools.lapseLeft.value = convertSecsToHMS(animator.duration);
  this.updatePlayButton(animator.isPaused);
  this.updateToolbarBackground();
};

/**
    * @private
    */
AnimationExtension.prototype._onPlayCallback = function (value) {

  // TODO: We should be able to replace this whole method body with a call to update().
  // The only problem for now is taht we would also need to change KeyFrameAnimator because
  // the onPlayCallback() is being invoked BEFORE the animation is paused.
  if (!this.animTools) return;

  var animator = this.viewer.impl.keyFrameAnimator;
  this.viewer.dispatchEvent({ type: ANIMATION_TRACK_UPDATE_EVENT, data: { time: animator.currentTime, duration: animator.duration } });
  this.animTools.input.value = value;
  this.animTools.lapse.value = convertSecsToHMS(animator.currentTime);
  this.animTools.lapseLeft.value = convertSecsToHMS(animator.duration);

  if (value >= 100 && !animator.isLooping()) {
    this.updatePlayButton(true);
  }
  this.updateToolbarBackground();
};

/**
    *
    * @param isPaused
    * @private
    */
AnimationExtension.prototype.updatePlayButton = function (isPaused) {
  if (!this.playButton) {
    return;
  }

  if (isPaused === this.playButtonIsPaused) {
    return;
  }

  this.playButtonIsPaused = isPaused;
  var animator = this.viewer.impl.keyFrameAnimator;

  if (isPaused) {
    this.playButton.setIcon('toolbar-animation-play-icon');
    this.playButton.setToolTip('Play');
    this.viewer.dispatchEvent({ type: ANIMATION_PAUSE_EVENT, data: { time: animator.currentTime, duration: animator.duration } });

  } else {
    this.playButton.setIcon('toolbar-animation-pause-icon');
    this.playButton.setToolTip('Pause');
    this.viewer.dispatchEvent({ type: ANIMATION_PLAY_EVENT, data: { time: animator.currentTime, duration: animator.duration } });
  }
};

/**
    * Helper function that resets model explosion.
    * @param value
    * @param setSlider
    * @private
    */
AnimationExtension.prototype.resetExplode = function (value, setSlider) {
  var viewer = this.viewer;
  if (!viewer.model.is2d() && viewer.getExplodeScale() !== 0) {
    if (setSlider && viewer.explodeSlider) {// explodeSlider is only in GuiViewer3D instances
      viewer.explodeSlider.value = value;
    }
    viewer.explode(value);
  }
};

/**
    * @private
    */
AnimationExtension.prototype.adjustToolbarPosition = function () {
  // set timeline width
  var viewer = this.viewer;
  if (!viewer.toolbar) return;
  var fullwidth = viewer.toolbar.getDimensions().width;
  var viewportWidth = viewer.container.getBoundingClientRect().width;
  if (fullwidth > viewportWidth)
  fullwidth = viewer.modelTools.getDimensions().width;
  var inputWidth = fullwidth - (2 *
  this.animTools.backwardButton.getDimensions().width + 3 *
  this.animTools.timeText.getDimensions().width + this.animTools.closeButton.getDimensions().width + 20);
  this.animTools.input.style.width = inputWidth + 'px';
};

/**
    * @private
    */
AnimationExtension.prototype.hideAnimateToolbar = function () {
  if (this.animTools) {
    this.animTools.setVisible(false);
  }
};

/**
    * @private
    */
AnimationExtension.prototype.updateToolbarBackground = function () {
  if (!this.animTools) return;
  var input = this.animTools.input;
  var percentage = input.value;
  var col1 = "#ffffff",col2 = "#393939";
  input.style.background = "-webkit-linear-gradient(left," + col1 + " " + percentage + "%, " + col2 + " " + percentage + "%)";
  input.style.background = "-moz-linear-gradient(left," + col1 + " " + percentage + "%, " + col2 + " " + percentage + "%)";
  input.style.background = "-ms-linear-gradient(left," + col1 + " " + percentage + "%, " + col2 + " " + percentage + "%)";
  input.style.background = "-o-linear-gradient(left," + col1 + " " + percentage + "%, " + col2 + " " + percentage + "%)";
  input.style.background = "linear-gradient(to right," + col1 + " " + percentage + "%, " + col2 + " " + percentage + "%)";
};

/**
    * @private
    */
AnimationExtension.prototype._onCameraChange = function () {

  if (this.viewer.impl.keyFrameAnimator && !this.viewer.impl.keyFrameAnimator.isFollowingCamera())
  return;

  if (this.viewer.toolController.cameraUpdated) {
    var animator = this.viewer.impl.keyFrameAnimator;
    if (!animator) return;
    if (animator.isPlaying && !animator.isPaused) {
      animator.pause();
      this.updatePlayButton(animator.isPaused);
    }
  }
};

/**
    * @private
    */
AnimationExtension.prototype._onResize = function () {
  if (!this.toolbar) return;
  if (this.viewer.container.clientWidth < (isTouchDevice() ? 560 : 600)) {
    this.toolbar.setCollapsed(true);
  } else {
    this.toolbar.setCollapsed(false);
    this.adjustToolbarPosition();
  }
};

/**
    * @private
    */
AnimationExtension.prototype._onEscape = function () {

  if (this.isPlaying()) {
    this.pause();
  } else {
    this.hideAnimateToolbar();
  }
};

/**
    * @private
    */
AnimationExtension.prototype._onExplode = function () {
  // reset animation
  var animator = this.viewer.impl.keyFrameAnimator;
  if (animator) {
    if (animator.currentTime !== 0) {
      this.prevAnimationTime = animator.currentTime;
      animator.goto(0);
    }
    this.updatePlayButton(true);
  }
  this.hideAnimateToolbar();
};

/**
    * Invoked by the viewer when the toolbar UI is available.
    *
    * @param {Autodesk.Viewing.UI.ToolBar} toolbar - toolbar instance.
    *
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#onToolbarCreated
    */
AnimationExtension.prototype.onToolbarCreated = function (toolbar) {

  this._toolbarReady = true;
  this._initUI();
};

/**
    * @private
    */
AnimationExtension.prototype._initUI = function () {

  if (!this._toolbarReady || !this._animationReady) {
    return;
  }

  var viewer = this.viewer;
  var that = this;
  var _document = this.getDocument();

  this.toolbar = new ToolBar('animation-toolbar');
  this.toolbar.setGlobalManager(this.globalManager);
  this.toolbar.addClass('toolbar-animation-subtoolbar');
  viewer.container.appendChild(this.toolbar.container);

  this.animTools = new ControlGroup(this.animToolsId);
  this.animTools.setGlobalManager(this.globalManager);
  this.animTools.setVisible(false);
  this.toolbar.addControl(this.animTools);

  // play button at first of modelTools
  this.playButton = new Button('toolbar-animationPlay');
  this.playButton.setGlobalManager(this.globalManager);
  this.playButton.setIcon('toolbar-animation-play-icon');
  this.playButton.setToolTip('Play');
  this.playButton.onClick = function () {
    if (that.isPaused()) {
      that.activate();
    } else {
      that.deactivate();
    }
  };
  viewer.modelTools.addControl(this.playButton);

  // override reset button's onClick method
  if (viewer.modelTools.resetModelButton) {
    viewer.modelTools.resetModelButton.onClick = function (e) {
      viewer.showAll();
      var animator = viewer.impl.keyFrameAnimator;
      if (animator) {
        animator.goto(0);
        input.value = 0;
        lapse.value = convertSecsToHMS(0);
        lapseLeft.value = convertSecsToHMS(animator.duration);
        that.updatePlayButton(true);
      }
      that.resetExplode(0, true);
      that.updateToolbarBackground();
    };
  }

  // backward button
  this.animTools.backwardButton = new Button('toolbar-animationBackward');
  this.animTools.backwardButton.setGlobalManager(this.globalManager);
  this.animTools.backwardButton.setToolTip('Previous keyframe');
  this.animTools.backwardButton.onClick = function (e) {
    var animator = viewer.impl.keyFrameAnimator;
    if (animator !== undefined && animator) {
      animator.prev();
      viewer.dispatchEvent({ type: ANIMATION_PREVIOUS_FRAME_EVENT, data: { time: animator.currentTime, duration: animator.duration } });
      that.updateUI();
    }
  };
  this.animTools.backwardButton.addClass('toolbar-animation-button');
  this.animTools.backwardButton.setIcon('toolbar-animation-backward-icon');
  this.animTools.addControl(this.animTools.backwardButton);

  // forward button
  this.animTools.forwardButton = new Button('toolbar-animationForward');
  this.animTools.forwardButton.setGlobalManager(this.globalManager);
  this.animTools.forwardButton.setToolTip('Next keyframe');
  this.animTools.forwardButton.onClick = function (e) {
    var animator = viewer.impl.keyFrameAnimator;
    if (animator !== undefined && animator) {
      animator.next();
      viewer.dispatchEvent({ type: ANIMATION_NEXT_FRAME_EVENT, data: { time: animator.currentTime, duration: animator.duration } });
      that.updateUI();
    }
  };
  this.animTools.forwardButton.addClass('toolbar-animation-button');
  this.animTools.forwardButton.setIcon('toolbar-animation-forward-icon');
  this.animTools.addControl(this.animTools.forwardButton);

  // current time lapse
  this.animTools.timeText = new Control('toolbar-animation-time-lapse');
  this.animTools.timeText.setGlobalManager(this.globalManager);
  var lapse = this.animTools.lapse = _document.createElement("input");
  lapse.type = "text";
  lapse.value = "0";
  lapse.className = "animation-time-lapse";
  lapse.disabled = true;
  this.animTools.timeText.container.appendChild(lapse);
  this.animTools.timeText.addClass('toolbar-animation-button');
  this.animTools.addControl(this.animTools.timeText);

  // timeline
  this.animTools.timeline = new Control('toolbar-animation-timeline');
  this.animTools.timeline.setGlobalManager(this.globalManager);
  var input = this.animTools.input = _document.createElement("input");
  input.type = "range";
  input.value = "0";
  input.className = "animation-timeline";
  if (isIE11) {
    // In IE11, the input type=range has a weird default layout...
    input.style['padding-top'] = '0';
    input.style['padding-bottom'] = '0';
    input.style['margin-top'] = '10px';
  }
  this.animTools.timeline.container.appendChild(input);
  // oninput doesn't work on IE11, use onchange instead
  input.addEventListener(isIE11 ? "change" : "input", function (e) {
    var animator = viewer.impl.keyFrameAnimator;
    if (animator !== undefined && animator) {
      var time = input.value * animator.duration / 100;
      lapse.value = convertSecsToHMS(time);
      lapseLeft.value = convertSecsToHMS(animator.duration);
      animator.goto(time);
      viewer.dispatchEvent({ type: ANIMATION_SEEK_EVENT, data: { time: time, duration: animator.duration } });
      that.updatePlayButton(animator.isPaused);
      that.updateToolbarBackground();
    }
  });
  // tooltip for slider
  var tooltipSiderLabel = "Click-drag to scrub";
  var inputTooltip = _document.createElement("div");
  inputTooltip.className = "adsk-control-tooltip";
  inputTooltip.textContent = av.i18n.translate(tooltipSiderLabel);
  inputTooltip.setAttribute('data-i18n', tooltipSiderLabel);
  this.animTools.timeline.container.appendChild(inputTooltip);
  input.addEventListener("mouseover", function (event) {
    if (event.target === input)
    inputTooltip.style.visibility = "visible";
  });
  input.addEventListener("mouseout", function (event) {
    if (event.target === input)
    inputTooltip.style.visibility = "hidden";
  });

  this.animTools.timeline.addClass('toolbar-animation-button');
  this.animTools.timeline.addClass('toolbar-animation-timeline');
  this.animTools.addControl(this.animTools.timeline);

  // remaining time lapse
  this.animTools.timeLeftText = new Control('toolbar-animationRemainingTime');
  this.animTools.timeLeftText.setGlobalManager(this.globalManager);
  var lapseLeft = this.animTools.lapseLeft = _document.createElement("input");
  lapseLeft.type = "text";
  lapseLeft.value = "0";
  lapseLeft.className = "animation-time-lapse";
  lapseLeft.disabled = true;
  this.animTools.timeLeftText.container.appendChild(lapseLeft);
  this.animTools.timeLeftText.addClass('toolbar-animation-button');
  this.animTools.addControl(this.animTools.timeLeftText);

  // close button
  this.animTools.closeButton = new Button('toolbar-animation-Close');
  this.animTools.closeButton.setGlobalManager(this.globalManager);
  this.animTools.closeButton.addClass('docking-panel-close');
  this.animTools.closeButton.addClass('toolbar-animation-button');
  this.animTools.closeButton.addClass('toolbar-animation-close-button');
  this.animTools.closeButton.onClick = function () {
    that.hideAnimateToolbar();
    viewer.dispatchEvent({ type: ANIMATION_TOOLBAR_CLOSE_EVENT });
  };

  this.animTools.addControl(this.animTools.closeButton);


  // settings panel
  var settingsPanel = this.viewer.getSettingsPanel();
  if (settingsPanel) {
    this._configButtonId = settingsPanel.addConfigButton(SETTINGS_BUTTON_LABEL, this.openPanel);
  }

  viewer.addEventListener(av.VIEWER_RESIZE_EVENT, this._onResize);
};


/**
    * Opens a panel with options to configure the animation extension.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#openPanel
    */
AnimationExtension.prototype.openPanel = function () {
  if (!this._panel) {
    this._panel = new _AnimationPanel__WEBPACK_IMPORTED_MODULE_1__["AnimationPanel"](this.viewer, this, SETTINGS_BUTTON_LABEL);
  }
  this._panel.setVisible(true);
};

/**
    * Plays the animation.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#activate
    */
AnimationExtension.prototype.activate = function () {
  this.play();
  return true;
};

/**
    * Pauses the animation.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#deactivate
    */
AnimationExtension.prototype.deactivate = function () {
  this.pause();
  return true;
};

/**
    * @returns {boolean} true when the animation is playing.
    * 
    * @alias Autodesk.Viewing.Extensions.AnimationExtension#isActive
    */
AnimationExtension.prototype.isActive = function () {
  return this.isPlaying();
};



Autodesk.Viewing.theExtensionManager.registerExtension('Autodesk.Fusion360.Animation', AnimationExtension);

/***/ }),

/***/ "./extensions/Fusion360/AnimationLocales.js":
/*!**************************************************!*\
  !*** ./extensions/Fusion360/AnimationLocales.js ***!
  \**************************************************/
/*! exports provided: locales */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "locales", function() { return locales; });
/* harmony import */ var _res_locales_en_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../res/locales/en/nobundle-animation.loc.json */ "./res/locales/en/nobundle-animation.loc.json");
var _res_locales_en_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_0___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/en/nobundle-animation.loc.json */ "./res/locales/en/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_cs_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../res/locales/cs/nobundle-animation.loc.json */ "./res/locales/cs/nobundle-animation.loc.json");
var _res_locales_cs_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_1___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/cs/nobundle-animation.loc.json */ "./res/locales/cs/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_de_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../res/locales/de/nobundle-animation.loc.json */ "./res/locales/de/nobundle-animation.loc.json");
var _res_locales_de_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_2___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/de/nobundle-animation.loc.json */ "./res/locales/de/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_es_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../res/locales/es/nobundle-animation.loc.json */ "./res/locales/es/nobundle-animation.loc.json");
var _res_locales_es_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_3___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/es/nobundle-animation.loc.json */ "./res/locales/es/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_fr_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../res/locales/fr/nobundle-animation.loc.json */ "./res/locales/fr/nobundle-animation.loc.json");
var _res_locales_fr_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_4___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr/nobundle-animation.loc.json */ "./res/locales/fr/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_fr_CA_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../../res/locales/fr-CA/nobundle-animation.loc.json */ "./res/locales/fr-CA/nobundle-animation.loc.json");
var _res_locales_fr_CA_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_5___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr-CA/nobundle-animation.loc.json */ "./res/locales/fr-CA/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_it_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../../res/locales/it/nobundle-animation.loc.json */ "./res/locales/it/nobundle-animation.loc.json");
var _res_locales_it_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_6___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/it/nobundle-animation.loc.json */ "./res/locales/it/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_ja_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ../../res/locales/ja/nobundle-animation.loc.json */ "./res/locales/ja/nobundle-animation.loc.json");
var _res_locales_ja_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_7___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ja/nobundle-animation.loc.json */ "./res/locales/ja/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_ko_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ../../res/locales/ko/nobundle-animation.loc.json */ "./res/locales/ko/nobundle-animation.loc.json");
var _res_locales_ko_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_8___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ko/nobundle-animation.loc.json */ "./res/locales/ko/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_pl_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! ../../res/locales/pl/nobundle-animation.loc.json */ "./res/locales/pl/nobundle-animation.loc.json");
var _res_locales_pl_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_9___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pl/nobundle-animation.loc.json */ "./res/locales/pl/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_pt_BR_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ../../res/locales/pt-BR/nobundle-animation.loc.json */ "./res/locales/pt-BR/nobundle-animation.loc.json");
var _res_locales_pt_BR_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_10___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pt-BR/nobundle-animation.loc.json */ "./res/locales/pt-BR/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_ru_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_11__ = __webpack_require__(/*! ../../res/locales/ru/nobundle-animation.loc.json */ "./res/locales/ru/nobundle-animation.loc.json");
var _res_locales_ru_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_11___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ru/nobundle-animation.loc.json */ "./res/locales/ru/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_tr_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_12__ = __webpack_require__(/*! ../../res/locales/tr/nobundle-animation.loc.json */ "./res/locales/tr/nobundle-animation.loc.json");
var _res_locales_tr_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_12___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/tr/nobundle-animation.loc.json */ "./res/locales/tr/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANS_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_13__ = __webpack_require__(/*! ../../res/locales/zh-HANS/nobundle-animation.loc.json */ "./res/locales/zh-HANS/nobundle-animation.loc.json");
var _res_locales_zh_HANS_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_13___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANS/nobundle-animation.loc.json */ "./res/locales/zh-HANS/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANT_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_14__ = __webpack_require__(/*! ../../res/locales/zh-HANT/nobundle-animation.loc.json */ "./res/locales/zh-HANT/nobundle-animation.loc.json");
var _res_locales_zh_HANT_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_14___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANT/nobundle-animation.loc.json */ "./res/locales/zh-HANT/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_nl_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_15__ = __webpack_require__(/*! ../../res/locales/nl/nobundle-animation.loc.json */ "./res/locales/nl/nobundle-animation.loc.json");
var _res_locales_nl_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_15___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/nl/nobundle-animation.loc.json */ "./res/locales/nl/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_sv_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_16__ = __webpack_require__(/*! ../../res/locales/sv/nobundle-animation.loc.json */ "./res/locales/sv/nobundle-animation.loc.json");
var _res_locales_sv_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_16___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/sv/nobundle-animation.loc.json */ "./res/locales/sv/nobundle-animation.loc.json", 1);
/* harmony import */ var _res_locales_da_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_17__ = __webpack_require__(/*! ../../res/locales/da/nobundle-animation.loc.json */ "./res/locales/da/nobundle-animation.loc.json");
var _res_locales_da_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_17___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/da/nobundle-animation.loc.json */ "./res/locales/da/nobundle-animation.loc.json", 1);
/**
 * Include each locale json file and return it in an object
 * that can be consumed by i18n
 */




















var locales = {
  en: _res_locales_en_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_0__,
  cs: _res_locales_cs_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_1__,
  de: _res_locales_de_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_2__,
  es: _res_locales_es_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_3__,
  fr: _res_locales_fr_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_4__,
  "fr-CA": _res_locales_fr_CA_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_5__,
  it: _res_locales_it_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_6__,
  ja: _res_locales_ja_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_7__,
  ko: _res_locales_ko_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_8__,
  pl: _res_locales_pl_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_9__,
  "pt-BR": _res_locales_pt_BR_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_10__,
  ru: _res_locales_ru_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_11__,
  tr: _res_locales_tr_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_12__,
  "zh-HANS": _res_locales_zh_HANS_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_13__,
  "zh-HANT": _res_locales_zh_HANT_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_14__,
  nl: _res_locales_nl_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_15__,
  sv: _res_locales_sv_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_16__,
  da: _res_locales_da_nobundle_animation_loc_json__WEBPACK_IMPORTED_MODULE_17__ };

/***/ }),

/***/ "./extensions/Fusion360/AnimationPanel.js":
/*!************************************************!*\
  !*** ./extensions/Fusion360/AnimationPanel.js ***!
  \************************************************/
/*! exports provided: AnimationPanel */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "AnimationPanel", function() { return AnimationPanel; });



var TAB_ID = 'configTab';
var TAB_LABEL = 'Configuration';
var PAUSE_ON_ORBIT_LABEL = 'Animate camera';
var PAUSE_ON_ORBIT_DESCR = 'When checked, animation pauses whenever the user interacts with camera';
var SLIDER_LABEL = 'Speed modifier';
var SLIDER_MIN_VALUE = 0.1;
var SLIDER_MAX_VALUE = 4;
var LOOP_LABEL = 'Loop';
var LOOP_DESCR = 'Rewind and play as soon as the animation completes';


var AnimationPanel = function AnimationPanel(viewer, extension, title) {

  var PANEL_ID = 'adsk_fusion_animation_panel_' + viewer.id;
  var opts = { heightAdjustment: 90, width: 460 };
  Autodesk.Viewing.UI.SettingsPanel.call(this, viewer.container, PANEL_ID, title, opts);
  this.container.classList.add('viewer-settings-panel');

  this.viewer = viewer;

  // Add a default tab called Configuration
  this.addTab(TAB_ID, TAB_LABEL, { className: 'config' });
  this.selectTab(TAB_ID);

  // Checkbox "follow camera"
  var initValue = extension.isFollowingCamera();
  this.addCheckbox(TAB_ID, PAUSE_ON_ORBIT_LABEL, initValue, function (checked) {
    extension.setFollowCamera(checked);
  }, PAUSE_ON_ORBIT_DESCR);


  // Slider "Speed modifier"
  initValue = extension.getSpeedModifier();
  this.addSlider(TAB_ID, SLIDER_LABEL,
  SLIDER_MIN_VALUE, SLIDER_MAX_VALUE, initValue,
  function (event) {
    var value = event.detail.value;
    extension.setSpeedModifier(Number(value));
  },
  { step: 0.1 });


  // Checkbox "Loop"
  initValue = extension.isLooping();
  this.addCheckbox(TAB_ID, LOOP_LABEL, initValue, function (checked) {
    extension.setLooping(checked);
  }, LOOP_DESCR);


  this.createFooter();
};

AnimationPanel.prototype = Object.create(Autodesk.Viewing.UI.SettingsPanel.prototype);
AnimationPanel.prototype.constructor = AnimationPanel;

/***/ }),

/***/ "./extensions/Fusion360/AnimationToolbar.css":
/*!***************************************************!*\
  !*** ./extensions/Fusion360/AnimationToolbar.css ***!
  \***************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../../node_modules/css-loader!../../node_modules/sass-loader/dist/cjs.js!./AnimationToolbar.css */ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/Fusion360/AnimationToolbar.css");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(false) {}

/***/ }),

/***/ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/Fusion360/AnimationToolbar.css":
/*!********************************************************************************************************************!*\
  !*** ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./extensions/Fusion360/AnimationToolbar.css ***!
  \********************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../../node_modules/css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, "/**\n * Animation toolbar\n **/\n.adsk-viewing-viewer .toolbar-animation-subtoolbar {\n  font-size: 12px;\n  height: 50px;\n  bottom: 70px;\n  z-index: 4; }\n\n.adsk-viewing-viewer .toolbar-menu-collapsed .toolbar-animation-subtoolbar {\n  display: none; }\n\n.adsk-viewing-viewer .toolbar-animation-subtoolbar .adsk-control-group {\n  padding-top: 10px;\n  height: calc(100% - 10px);\n  position: relative; }\n\n.adsk-viewing-viewer .toolbar-animation-forward-icon {\n  min-width: 28px;\n  min-height: 16px; }\n\n.adsk-viewing-viewer .toolbar-animation-backward-icon {\n  min-width: 28px;\n  min-height: 16px; }\n\n.adsk-viewing-viewer .toolbar-animation-close-icon {\n  min-width: 18px;\n  min-height: 16px; }\n\n.adsk-viewing-viewer .toolbar-animation-timeline {\n  top: 0;\n  margin: 2px 0 0 0; }\n\n.adsk-viewing-viewer .animation-timeline {\n  outline: none; }\n\n.adsk-viewing-viewer .animation-time-lapse {\n  outline: none;\n  border-width: 0;\n  width: 48px;\n  position: relative;\n  z-index: 0;\n  background: rgba(34, 34, 34, 0);\n  -webkit-user-select: none;\n  -moz-user-select: none;\n  -khtml-user-select: none;\n  -ms-user-select: none; }\n\n.adsk-viewing-viewer .toolbar-animation-menu-placer {\n  bottom: 46px; }\n\n.adsk-viewing-viewer .toolbar-animation-button {\n  float: left;\n  cursor: pointer;\n  border-radius: 5px;\n  padding: 0;\n  width: auto;\n  height: auto;\n  min-width: 48px;\n  min-height: 48px; }\n\n.adsk-viewing-viewer .toolbar-animation-button {\n  border: none !important; }\n\n.adsk-viewing-viewer .toolbar-animation-button:hover {\n  border: none !important; }\n\n.adsk-viewing-viewer .toolbar-animation-close-button {\n  top: -14px;\n  width: 25px;\n  height: 48px;\n  min-width: 0;\n  min-height: 0;\n  position: relative; }\n\n.adsk-viewing-viewer .toolbar-animation-close-button.docking-panel-close {\n  background-position: 5px 19px; }\n\n.adsk-viewing-viewer .toolbar-animation-button > input {\n  margin-top: 5px;\n  width: 80px;\n  text-align: center; }\n", ""]);

// exports


/***/ }),

/***/ "./node_modules/css-loader/lib/css-base.js":
/*!*************************************************!*\
  !*** ./node_modules/css-loader/lib/css-base.js ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
// css base code, injected by the css-loader
module.exports = function(useSourceMap) {
	var list = [];

	// return the list of modules as css string
	list.toString = function toString() {
		return this.map(function (item) {
			var content = cssWithMappingToString(item, useSourceMap);
			if(item[2]) {
				return "@media " + item[2] + "{" + content + "}";
			} else {
				return content;
			}
		}).join("");
	};

	// import a list of modules into the list
	list.i = function(modules, mediaQuery) {
		if(typeof modules === "string")
			modules = [[null, modules, ""]];
		var alreadyImportedModules = {};
		for(var i = 0; i < this.length; i++) {
			var id = this[i][0];
			if(typeof id === "number")
				alreadyImportedModules[id] = true;
		}
		for(i = 0; i < modules.length; i++) {
			var item = modules[i];
			// skip already imported module
			// this implementation is not 100% perfect for weird media query combinations
			//  when a module is imported multiple times with different media queries.
			//  I hope this will never occur (Hey this way we have smaller bundles)
			if(typeof item[0] !== "number" || !alreadyImportedModules[item[0]]) {
				if(mediaQuery && !item[2]) {
					item[2] = mediaQuery;
				} else if(mediaQuery) {
					item[2] = "(" + item[2] + ") and (" + mediaQuery + ")";
				}
				list.push(item);
			}
		}
	};
	return list;
};

function cssWithMappingToString(item, useSourceMap) {
	var content = item[1] || '';
	var cssMapping = item[3];
	if (!cssMapping) {
		return content;
	}

	if (useSourceMap && typeof btoa === 'function') {
		var sourceMapping = toComment(cssMapping);
		var sourceURLs = cssMapping.sources.map(function (source) {
			return '/*# sourceURL=' + cssMapping.sourceRoot + source + ' */'
		});

		return [content].concat(sourceURLs).concat([sourceMapping]).join('\n');
	}

	return [content].join('\n');
}

// Adapted from convert-source-map (MIT)
function toComment(sourceMap) {
	// eslint-disable-next-line no-undef
	var base64 = btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap))));
	var data = 'sourceMappingURL=data:application/json;charset=utf-8;base64,' + base64;

	return '/*# ' + data + ' */';
}


/***/ }),

/***/ "./node_modules/style-loader/lib/addStyles.js":
/*!****************************************************!*\
  !*** ./node_modules/style-loader/lib/addStyles.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

var stylesInDom = {};

var	memoize = function (fn) {
	var memo;

	return function () {
		if (typeof memo === "undefined") memo = fn.apply(this, arguments);
		return memo;
	};
};

var isOldIE = memoize(function () {
	// Test for IE <= 9 as proposed by Browserhacks
	// @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
	// Tests for existence of standard globals is to allow style-loader
	// to operate correctly into non-standard environments
	// @see https://github.com/webpack-contrib/style-loader/issues/177
	return window && document && document.all && !window.atob;
});

var getTarget = function (target, parent) {
  if (parent){
    return parent.querySelector(target);
  }
  return document.querySelector(target);
};

var getElement = (function (fn) {
	var memo = {};

	return function(target, parent) {
                // If passing function in options, then use it for resolve "head" element.
                // Useful for Shadow Root style i.e
                // {
                //   insertInto: function () { return document.querySelector("#foo").shadowRoot }
                // }
                if (typeof target === 'function') {
                        return target();
                }
                if (typeof memo[target] === "undefined") {
			var styleTarget = getTarget.call(this, target, parent);
			// Special case to return head of iframe instead of iframe itself
			if (window.HTMLIFrameElement && styleTarget instanceof window.HTMLIFrameElement) {
				try {
					// This will throw an exception if access to iframe is blocked
					// due to cross-origin restrictions
					styleTarget = styleTarget.contentDocument.head;
				} catch(e) {
					styleTarget = null;
				}
			}
			memo[target] = styleTarget;
		}
		return memo[target]
	};
})();

var singleton = null;
var	singletonCounter = 0;
var	stylesInsertedAtTop = [];

var	fixUrls = __webpack_require__(/*! ./urls */ "./node_modules/style-loader/lib/urls.js");

module.exports = function(list, options) {
	if (typeof DEBUG !== "undefined" && DEBUG) {
		if (typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
	}

	options = options || {};

	options.attrs = typeof options.attrs === "object" ? options.attrs : {};

	// Force single-tag solution on IE6-9, which has a hard limit on the # of <style>
	// tags it will allow on a page
	if (!options.singleton && typeof options.singleton !== "boolean") options.singleton = isOldIE();

	// By default, add <style> tags to the <head> element
        if (!options.insertInto) options.insertInto = "head";

	// By default, add <style> tags to the bottom of the target
	if (!options.insertAt) options.insertAt = "bottom";

	var styles = listToStyles(list, options);

	addStylesToDom(styles, options);

	return function update (newList) {
		var mayRemove = [];

		for (var i = 0; i < styles.length; i++) {
			var item = styles[i];
			var domStyle = stylesInDom[item.id];

			domStyle.refs--;
			mayRemove.push(domStyle);
		}

		if(newList) {
			var newStyles = listToStyles(newList, options);
			addStylesToDom(newStyles, options);
		}

		for (var i = 0; i < mayRemove.length; i++) {
			var domStyle = mayRemove[i];

			if(domStyle.refs === 0) {
				for (var j = 0; j < domStyle.parts.length; j++) domStyle.parts[j]();

				delete stylesInDom[domStyle.id];
			}
		}
	};
};

function addStylesToDom (styles, options) {
	for (var i = 0; i < styles.length; i++) {
		var item = styles[i];
		var domStyle = stylesInDom[item.id];

		if(domStyle) {
			domStyle.refs++;

			for(var j = 0; j < domStyle.parts.length; j++) {
				domStyle.parts[j](item.parts[j]);
			}

			for(; j < item.parts.length; j++) {
				domStyle.parts.push(addStyle(item.parts[j], options));
			}
		} else {
			var parts = [];

			for(var j = 0; j < item.parts.length; j++) {
				parts.push(addStyle(item.parts[j], options));
			}

			stylesInDom[item.id] = {id: item.id, refs: 1, parts: parts};
		}
	}
}

function listToStyles (list, options) {
	var styles = [];
	var newStyles = {};

	for (var i = 0; i < list.length; i++) {
		var item = list[i];
		var id = options.base ? item[0] + options.base : item[0];
		var css = item[1];
		var media = item[2];
		var sourceMap = item[3];
		var part = {css: css, media: media, sourceMap: sourceMap};

		if(!newStyles[id]) styles.push(newStyles[id] = {id: id, parts: [part]});
		else newStyles[id].parts.push(part);
	}

	return styles;
}

function insertStyleElement (options, style) {
	var target = getElement(options.insertInto)

	if (!target) {
		throw new Error("Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.");
	}

	var lastStyleElementInsertedAtTop = stylesInsertedAtTop[stylesInsertedAtTop.length - 1];

	if (options.insertAt === "top") {
		if (!lastStyleElementInsertedAtTop) {
			target.insertBefore(style, target.firstChild);
		} else if (lastStyleElementInsertedAtTop.nextSibling) {
			target.insertBefore(style, lastStyleElementInsertedAtTop.nextSibling);
		} else {
			target.appendChild(style);
		}
		stylesInsertedAtTop.push(style);
	} else if (options.insertAt === "bottom") {
		target.appendChild(style);
	} else if (typeof options.insertAt === "object" && options.insertAt.before) {
		var nextSibling = getElement(options.insertAt.before, target);
		target.insertBefore(style, nextSibling);
	} else {
		throw new Error("[Style Loader]\n\n Invalid value for parameter 'insertAt' ('options.insertAt') found.\n Must be 'top', 'bottom', or Object.\n (https://github.com/webpack-contrib/style-loader#insertat)\n");
	}
}

function removeStyleElement (style) {
	if (style.parentNode === null) return false;
	style.parentNode.removeChild(style);

	var idx = stylesInsertedAtTop.indexOf(style);
	if(idx >= 0) {
		stylesInsertedAtTop.splice(idx, 1);
	}
}

function createStyleElement (options) {
	var style = document.createElement("style");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}

	if(options.attrs.nonce === undefined) {
		var nonce = getNonce();
		if (nonce) {
			options.attrs.nonce = nonce;
		}
	}

	addAttrs(style, options.attrs);
	insertStyleElement(options, style);

	return style;
}

function createLinkElement (options) {
	var link = document.createElement("link");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}
	options.attrs.rel = "stylesheet";

	addAttrs(link, options.attrs);
	insertStyleElement(options, link);

	return link;
}

function addAttrs (el, attrs) {
	Object.keys(attrs).forEach(function (key) {
		el.setAttribute(key, attrs[key]);
	});
}

function getNonce() {
	if (false) {}

	return __webpack_require__.nc;
}

function addStyle (obj, options) {
	var style, update, remove, result;

	// If a transform function was defined, run it on the css
	if (options.transform && obj.css) {
	    result = typeof options.transform === 'function'
		 ? options.transform(obj.css) 
		 : options.transform.default(obj.css);

	    if (result) {
	    	// If transform returns a value, use that instead of the original css.
	    	// This allows running runtime transformations on the css.
	    	obj.css = result;
	    } else {
	    	// If the transform function returns a falsy value, don't add this css.
	    	// This allows conditional loading of css
	    	return function() {
	    		// noop
	    	};
	    }
	}

	if (options.singleton) {
		var styleIndex = singletonCounter++;

		style = singleton || (singleton = createStyleElement(options));

		update = applyToSingletonTag.bind(null, style, styleIndex, false);
		remove = applyToSingletonTag.bind(null, style, styleIndex, true);

	} else if (
		obj.sourceMap &&
		typeof URL === "function" &&
		typeof URL.createObjectURL === "function" &&
		typeof URL.revokeObjectURL === "function" &&
		typeof Blob === "function" &&
		typeof btoa === "function"
	) {
		style = createLinkElement(options);
		update = updateLink.bind(null, style, options);
		remove = function () {
			removeStyleElement(style);

			if(style.href) URL.revokeObjectURL(style.href);
		};
	} else {
		style = createStyleElement(options);
		update = applyToTag.bind(null, style);
		remove = function () {
			removeStyleElement(style);
		};
	}

	update(obj);

	return function updateStyle (newObj) {
		if (newObj) {
			if (
				newObj.css === obj.css &&
				newObj.media === obj.media &&
				newObj.sourceMap === obj.sourceMap
			) {
				return;
			}

			update(obj = newObj);
		} else {
			remove();
		}
	};
}

var replaceText = (function () {
	var textStore = [];

	return function (index, replacement) {
		textStore[index] = replacement;

		return textStore.filter(Boolean).join('\n');
	};
})();

function applyToSingletonTag (style, index, remove, obj) {
	var css = remove ? "" : obj.css;

	if (style.styleSheet) {
		style.styleSheet.cssText = replaceText(index, css);
	} else {
		var cssNode = document.createTextNode(css);
		var childNodes = style.childNodes;

		if (childNodes[index]) style.removeChild(childNodes[index]);

		if (childNodes.length) {
			style.insertBefore(cssNode, childNodes[index]);
		} else {
			style.appendChild(cssNode);
		}
	}
}

function applyToTag (style, obj) {
	var css = obj.css;
	var media = obj.media;

	if(media) {
		style.setAttribute("media", media)
	}

	if(style.styleSheet) {
		style.styleSheet.cssText = css;
	} else {
		while(style.firstChild) {
			style.removeChild(style.firstChild);
		}

		style.appendChild(document.createTextNode(css));
	}
}

function updateLink (link, options, obj) {
	var css = obj.css;
	var sourceMap = obj.sourceMap;

	/*
		If convertToAbsoluteUrls isn't defined, but sourcemaps are enabled
		and there is no publicPath defined then lets turn convertToAbsoluteUrls
		on by default.  Otherwise default to the convertToAbsoluteUrls option
		directly
	*/
	var autoFixUrls = options.convertToAbsoluteUrls === undefined && sourceMap;

	if (options.convertToAbsoluteUrls || autoFixUrls) {
		css = fixUrls(css);
	}

	if (sourceMap) {
		// http://stackoverflow.com/a/26603875
		css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
	}

	var blob = new Blob([css], { type: "text/css" });

	var oldSrc = link.href;

	link.href = URL.createObjectURL(blob);

	if(oldSrc) URL.revokeObjectURL(oldSrc);
}


/***/ }),

/***/ "./node_modules/style-loader/lib/urls.js":
/*!***********************************************!*\
  !*** ./node_modules/style-loader/lib/urls.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports) {


/**
 * When source maps are enabled, `style-loader` uses a link element with a data-uri to
 * embed the css on the page. This breaks all relative urls because now they are relative to a
 * bundle instead of the current page.
 *
 * One solution is to only use full urls, but that may be impossible.
 *
 * Instead, this function "fixes" the relative urls to be absolute according to the current page location.
 *
 * A rudimentary test suite is located at `test/fixUrls.js` and can be run via the `npm test` command.
 *
 */

module.exports = function (css) {
  // get current location
  var location = typeof window !== "undefined" && window.location;

  if (!location) {
    throw new Error("fixUrls requires window.location");
  }

	// blank or null?
	if (!css || typeof css !== "string") {
	  return css;
  }

  var baseUrl = location.protocol + "//" + location.host;
  var currentDir = baseUrl + location.pathname.replace(/\/[^\/]*$/, "/");

	// convert each url(...)
	/*
	This regular expression is just a way to recursively match brackets within
	a string.

	 /url\s*\(  = Match on the word "url" with any whitespace after it and then a parens
	   (  = Start a capturing group
	     (?:  = Start a non-capturing group
	         [^)(]  = Match anything that isn't a parentheses
	         |  = OR
	         \(  = Match a start parentheses
	             (?:  = Start another non-capturing groups
	                 [^)(]+  = Match anything that isn't a parentheses
	                 |  = OR
	                 \(  = Match a start parentheses
	                     [^)(]*  = Match anything that isn't a parentheses
	                 \)  = Match a end parentheses
	             )  = End Group
              *\) = Match anything and then a close parens
          )  = Close non-capturing group
          *  = Match anything
       )  = Close capturing group
	 \)  = Match a close parens

	 /gi  = Get all matches, not the first.  Be case insensitive.
	 */
	var fixedCss = css.replace(/url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)/gi, function(fullMatch, origUrl) {
		// strip quotes (if they exist)
		var unquotedOrigUrl = origUrl
			.trim()
			.replace(/^"(.*)"$/, function(o, $1){ return $1; })
			.replace(/^'(.*)'$/, function(o, $1){ return $1; });

		// already a full url? no change
		if (/^(#|data:|http:\/\/|https:\/\/|file:\/\/\/|\s*$)/i.test(unquotedOrigUrl)) {
		  return fullMatch;
		}

		// convert the url to a full url
		var newUrl;

		if (unquotedOrigUrl.indexOf("//") === 0) {
		  	//TODO: should we add protocol?
			newUrl = unquotedOrigUrl;
		} else if (unquotedOrigUrl.indexOf("/") === 0) {
			// path should be relative to the base url
			newUrl = baseUrl + unquotedOrigUrl; // already starts with '/'
		} else {
			// path should be relative to current directory
			newUrl = currentDir + unquotedOrigUrl.replace(/^\.\//, ""); // Strip leading './'
		}

		// send back the fixed url(...)
		return "url(" + JSON.stringify(newUrl) + ")";
	});

	// send back the fixed css
	return fixedCss;
};


/***/ }),

/***/ "./res/locales/cs/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/cs/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"cs\",\"@@context\":\"Prohlížeč animací\",\"Play\":\"Přehrát\",\"Pause\":\"Pozastavit\",\"Next keyframe\":\"Další klíčový snímek\",\"Previous keyframe\":\"Předchozí klíčový snímek\",\"Click-drag to scrub\":\"Kliknutím a přetažením procházejte\",\"Close animation timeline\":\"Zavřít časovou osu animace\",\"Animate camera\":\"Animovat kameru\",\"When checked, animation pauses whenever the user interacts with camera\":\"Při zaškrtnutí se animace pozastaví, kdykoli bude uživatel manipulovat s kamerou.\",\"Loop\":\"Smyčka\",\"Rewind and play as soon as the animation completes\":\"Převinout zpět a přehrávat ihned po dokončení animace\",\"Speed modifier\":\"Ovladač rychlosti\"}");

/***/ }),

/***/ "./res/locales/da/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/da/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"da\",\"@@context\":\"Animationsfremviser\",\"Play\":\"Afspil\",\"Pause\":\"Pause\",\"Next keyframe\":\"Næste keyframe\",\"Previous keyframe\":\"Forrige keyframe\",\"Click-drag to scrub\":\"Klik og træk for hurtig visning\",\"Close animation timeline\":\"Luk tidslinje for animation\",\"Animate camera\":\"Animer kamera\",\"When checked, animation pauses whenever the user interacts with camera\":\"Hvis markeret pauser animationen, når som helst brugeren interagerer med kamera.\",\"Loop\":\"Loop\",\"Rewind and play as soon as the animation completes\":\"Spol tilbage, og afspil så snart animationen er færdig\",\"Speed modifier\":\"Hastighedsmodifikator\"}");

/***/ }),

/***/ "./res/locales/de/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/de/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"de\",\"@@context\":\"Viewer-Animation\",\"Play\":\"Wiedergabe\",\"Pause\":\"Pause\",\"Next keyframe\":\"Nächstes Keyframe\",\"Previous keyframe\":\"Vorheriges Keyframe\",\"Click-drag to scrub\":\"Für einen schnellen Vorlauf klicken und ziehen\",\"Close animation timeline\":\"Animationsablaufprogramm schließen\",\"Animate camera\":\"Kamera animieren\",\"When checked, animation pauses whenever the user interacts with camera\":\"Wenn dieses Kontrollkästchen aktiviert ist, wird die Animation bei jeder Interaktion mit dem Benutzer angehalten.\",\"Loop\":\"Schleife\",\"Rewind and play as soon as the animation completes\":\"Zurückspulen und wiedergeben, sobald die Animation endet\",\"Speed modifier\":\"Modifikator \\\"Geschwindigkeit\\\"\"}");

/***/ }),

/***/ "./res/locales/en/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/en/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"en\",\"@@context\":\"Viewer Animation\",\"Play\":\"Play\",\"Pause\":\"Pause\",\"Next keyframe\":\"Next keyframe\",\"Previous keyframe\":\"Previous keyframe\",\"Click-drag to scrub\":\"Click-drag to scrub\",\"Close animation timeline\":\"Close animation timeline\",\"Animate camera\":\"Animate camera\",\"When checked, animation pauses whenever the user interacts with camera\":\"When checked, animation pauses whenever the user interacts with camera.\",\"Loop\":\"Loop\",\"Rewind and play as soon as the animation completes\":\"Rewind and play as soon as the animation completes\",\"Speed modifier\":\"Speed modifier\"}");

/***/ }),

/***/ "./res/locales/es/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/es/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"es\",\"@@context\":\"Animación del visor\",\"Play\":\"Reproducir\",\"Pause\":\"Pausar\",\"Next keyframe\":\"Siguiente fotograma clave\",\"Previous keyframe\":\"Fotograma clave anterior\",\"Click-drag to scrub\":\"Haga clic y arrastre para anular.\",\"Close animation timeline\":\"Cerrar duración de la animación\",\"Animate camera\":\"Animar cámara\",\"When checked, animation pauses whenever the user interacts with camera\":\"Si se ha activado esta opción, la animación se detiene temporalmente cuando el usuario interacciona con la cámara.\",\"Loop\":\"Bucle\",\"Rewind and play as soon as the animation completes\":\"Rebobina y reproduce en cuanto se completa la animación.\",\"Speed modifier\":\"Modificador de velocidad\"}");

/***/ }),

/***/ "./res/locales/fr-CA/nobundle-animation.loc.json":
/*!*******************************************************!*\
  !*** ./res/locales/fr-CA/nobundle-animation.loc.json ***!
  \*******************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr-CA\",\"@@context\":\"Animation du visualiseur\",\"Play\":\"Lire\",\"Pause\":\"Suspendre\",\"Next keyframe\":\"Image clé suivante\",\"Previous keyframe\":\"Image clé précédente\",\"Click-drag to scrub\":\"Cliquez et faites glisser le curseur pour faire défiler la page\",\"Close animation timeline\":\"Fermer le plan de montage chronologique de l'animation\",\"Animate camera\":\"Animer la caméra\",\"When checked, animation pauses whenever the user interacts with camera\":\"Lorsque cette option est sélectionnée, l'animation se met en pause chaque fois que l'utilisateur interagit avec la caméra.\",\"Loop\":\"Boucle\",\"Rewind and play as soon as the animation completes\":\"Rembobiner et lire dès que l'animation est terminée\",\"Speed modifier\":\"Modificateur de vitesse\"}");

/***/ }),

/***/ "./res/locales/fr/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/fr/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr\",\"@@context\":\"Animation du visualiseur\",\"Play\":\"Lire\",\"Pause\":\"Suspendre\",\"Next keyframe\":\"Image clé suivante\",\"Previous keyframe\":\"Image clé précédente\",\"Click-drag to scrub\":\"Cliquez et faites glisser le curseur pour faire défiler la page\",\"Close animation timeline\":\"Fermer le plan de montage chronologique de l'animation\",\"Animate camera\":\"Animer la caméra\",\"When checked, animation pauses whenever the user interacts with camera\":\"Lorsque cette option est sélectionnée, l'animation se met en pause chaque fois que l'utilisateur interagit avec la caméra.\",\"Loop\":\"Boucle\",\"Rewind and play as soon as the animation completes\":\"Rembobiner et lire dès que l'animation est terminée\",\"Speed modifier\":\"Modificateur de vitesse\"}");

/***/ }),

/***/ "./res/locales/it/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/it/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"it\",\"@@context\":\"Animazione visualizzatore\",\"Play\":\"Riproduci\",\"Pause\":\"Pausa\",\"Next keyframe\":\"Fotogramma chiave successivo\",\"Previous keyframe\":\"Fotogramma chiave precedente\",\"Click-drag to scrub\":\"Fare clic e trascinare per scorrere\",\"Close animation timeline\":\"Chiudi sequenza temporale animazione\",\"Animate camera\":\"Anima inquadratura\",\"When checked, animation pauses whenever the user interacts with camera\":\"Quando questa opzione è selezionata, l'animazione viene messa in pausa ogni volta che l'utente interagisce con l'inquadratura.\",\"Loop\":\"Riproduzione continua\",\"Rewind and play as soon as the animation completes\":\"Riavvolgi e riproduci non appena l'animazione è stata completata\",\"Speed modifier\":\"Modificatore di velocità\"}");

/***/ }),

/***/ "./res/locales/ja/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/ja/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ja\",\"@@context\":\"ビューア アニメーション\",\"Play\":\"再生\",\"Pause\":\"一時停止\",\"Next keyframe\":\"次のキーフレーム\",\"Previous keyframe\":\"前のキーフレーム\",\"Click-drag to scrub\":\"クリックしてドラッグでスクラブ\",\"Close animation timeline\":\"アニメーション タイムラインを閉じる\",\"Animate camera\":\"カメラをアニメート\",\"When checked, animation pauses whenever the user interacts with camera\":\"オンにすると、ユーザがカメラを操作するたびにアニメーションが一時停止します。\",\"Loop\":\"ループ\",\"Rewind and play as soon as the animation completes\":\"アニメーションが完了したらすぐに巻き戻して再生します\",\"Speed modifier\":\"速度モディファイヤ\"}");

/***/ }),

/***/ "./res/locales/ko/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/ko/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ko\",\"@@context\":\"뷰어 애니메이션\",\"Play\":\"재생\",\"Pause\":\"일시 중지\",\"Next keyframe\":\"다음 키프레임\",\"Previous keyframe\":\"이전 키프레임\",\"Click-drag to scrub\":\"클릭한 상태로 끌어 스크럽\",\"Close animation timeline\":\"애니메이션 타임라인 닫기\",\"Animate camera\":\"카메라 애니메이트\",\"When checked, animation pauses whenever the user interacts with camera\":\"이 옵션을 선택하면 사용자가 카메라를 사용할 때마다 애니메이션이 일시 중지됩니다.\",\"Loop\":\"루프\",\"Rewind and play as soon as the animation completes\":\"애니메이션이 끝나면 뒤로 돌아가 재생\",\"Speed modifier\":\"속도 수정자\"}");

/***/ }),

/***/ "./res/locales/nl/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/nl/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"nl\",\"@@context\":\"Vieweranimatie\",\"Play\":\"Afspelen\",\"Pause\":\"Pauzeren\",\"Next keyframe\":\"Volgend keyframe\",\"Previous keyframe\":\"Vorig keyframe\",\"Click-drag to scrub\":\"Klik en sleep om te scrubben\",\"Close animation timeline\":\"Animatietijdlijn sluiten\",\"Animate camera\":\"Camera van animatie voorzien\",\"When checked, animation pauses whenever the user interacts with camera\":\"Als dit is aangevinkt, wordt de animatie gepauzeerd zodra de gebruiker de camera gebruikt.\",\"Loop\":\"Herhalen\",\"Rewind and play as soon as the animation completes\":\"Terugspoelen en afspelen zodra de animatie is voltooid\",\"Speed modifier\":\"Snelheid aanpassen\"}");

/***/ }),

/***/ "./res/locales/pl/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/pl/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pl\",\"@@context\":\"Animacja w przeglądarce\",\"Play\":\"Odtwórz\",\"Pause\":\"Pauza\",\"Next keyframe\":\"Następna ramka kluczowa\",\"Previous keyframe\":\"Poprzednia ramka kluczowa\",\"Click-drag to scrub\":\"Kliknij i przeciągnij, aby przewinąć\",\"Close animation timeline\":\"Zamknij oś czasu animacji\",\"Animate camera\":\"Animacja kamery\",\"When checked, animation pauses whenever the user interacts with camera\":\"Jeśli ta opcja jest zaznaczona, animacja zatrzymuje się, gdy użytkownik przejmie obsługę kamery.\",\"Loop\":\"Pętla\",\"Rewind and play as soon as the animation completes\":\"Cofnij i odtwórz zaraz po zakończeniu animacji\",\"Speed modifier\":\"Modyfikator prędkości\"}");

/***/ }),

/***/ "./res/locales/pt-BR/nobundle-animation.loc.json":
/*!*******************************************************!*\
  !*** ./res/locales/pt-BR/nobundle-animation.loc.json ***!
  \*******************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pt\",\"@@context\":\"Animação do visualizador\",\"Play\":\"Reproduzir\",\"Pause\":\"Pausar\",\"Next keyframe\":\"Próximo quadro-chave\",\"Previous keyframe\":\"Quadro-chave anterior\",\"Click-drag to scrub\":\"Clicar e arrastar para ignorar\",\"Close animation timeline\":\"Fechar linha de tempo da animação\",\"Animate camera\":\"Animar câmera\",\"When checked, animation pauses whenever the user interacts with camera\":\"Quando marcada, a animação pausa sempre que o usuário interage com a câmera.\",\"Loop\":\"Loop\",\"Rewind and play as soon as the animation completes\":\"Rebobinar e reproduzir assim que a animação ficar concluída\",\"Speed modifier\":\"Modificador de velocidade\"}");

/***/ }),

/***/ "./res/locales/ru/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/ru/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ru\",\"@@context\":\"Просмотр анимации\",\"Play\":\"Воспроизведение\",\"Pause\":\"Пауза\",\"Next keyframe\":\"Следующий ключевой кадр\",\"Previous keyframe\":\"Предыдущий ключевой кадр\",\"Click-drag to scrub\":\"Чтобы отменить, нажмите и перетащите\",\"Close animation timeline\":\"Закрыть временную шкалу анимации\",\"Animate camera\":\"Анимация камеры\",\"When checked, animation pauses whenever the user interacts with camera\":\"Если флажок установлен, анимация приостанавливается при взаимодействии пользователя с камерой.\",\"Loop\":\"Цикл\",\"Rewind and play as soon as the animation completes\":\"Перемотка назад и воспроизведение сразу после завершения анимации\",\"Speed modifier\":\"Модификатор скорости\"}");

/***/ }),

/***/ "./res/locales/sv/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/sv/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"sv\",\"@@context\":\"Animering av visningsprogrammet\",\"Play\":\"Spela upp\",\"Pause\":\"Pausa\",\"Next keyframe\":\"Nästa keyframe\",\"Previous keyframe\":\"Föregående keyframe\",\"Click-drag to scrub\":\"Klicka-och-dra för att skrubba\",\"Close animation timeline\":\"Stäng animeringstidslinjen\",\"Animate camera\":\"Animera kameran\",\"When checked, animation pauses whenever the user interacts with camera\":\"När detta är valt, pausas animationer när användaren interagerar med kameran.\",\"Loop\":\"Upprepa\",\"Rewind and play as soon as the animation completes\":\"Spola tillbaka och spela upp direkt efter att animationen är klar\",\"Speed modifier\":\"Hastighetsmodifierare\"}");

/***/ }),

/***/ "./res/locales/tr/nobundle-animation.loc.json":
/*!****************************************************!*\
  !*** ./res/locales/tr/nobundle-animation.loc.json ***!
  \****************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"tr\",\"@@context\":\"Görüntüleyici Animasyonu\",\"Play\":\"Oynat\",\"Pause\":\"Duraklat\",\"Next keyframe\":\"Sonraki ana kare\",\"Previous keyframe\":\"Önceki ana kare\",\"Click-drag to scrub\":\"Temizlemek için tıkla ve sürükle\",\"Close animation timeline\":\"Canlandırma zaman çizgisini kapat\",\"Animate camera\":\"Kamerayı canlandır\",\"When checked, animation pauses whenever the user interacts with camera\":\"İşaretlendiğinde, kullanıcı kamera ile etkileşimde bulunduğunda canlandırma duraklar.\",\"Loop\":\"Döngü\",\"Rewind and play as soon as the animation completes\":\"Canlandırma tamamlanır tamamlanmaz geri al ve oynat\",\"Speed modifier\":\"Hız değiştirici\"}");

/***/ }),

/***/ "./res/locales/zh-HANS/nobundle-animation.loc.json":
/*!*********************************************************!*\
  !*** ./res/locales/zh-HANS/nobundle-animation.loc.json ***!
  \*********************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hans\",\"@@context\":\"查看器动画演示\",\"Play\":\"播放\",\"Pause\":\"暂停\",\"Next keyframe\":\"下一关键帧\",\"Previous keyframe\":\"上一关键帧\",\"Click-drag to scrub\":\"单击并拖动以擦除\",\"Close animation timeline\":\"关闭动画时间轴\",\"Animate camera\":\"照相机动画演示\",\"When checked, animation pauses whenever the user interacts with camera\":\"如果选中，动画将在用户与照相机交互时暂停。\",\"Loop\":\"循环\",\"Rewind and play as soon as the animation completes\":\"只要动画完成播放，就会倒回并播放\",\"Speed modifier\":\"速度修改器\"}");

/***/ }),

/***/ "./res/locales/zh-HANT/nobundle-animation.loc.json":
/*!*********************************************************!*\
  !*** ./res/locales/zh-HANT/nobundle-animation.loc.json ***!
  \*********************************************************/
/*! exports provided: @@locale, @@context, Play, Pause, Next keyframe, Previous keyframe, Click-drag to scrub, Close animation timeline, Animate camera, When checked, animation pauses whenever the user interacts with camera, Loop, Rewind and play as soon as the animation completes, Speed modifier, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hant\",\"@@context\":\"檢視器動畫\",\"Play\":\"播放\",\"Pause\":\"暫停\",\"Next keyframe\":\"下一個關鍵畫面\",\"Previous keyframe\":\"上一個關鍵畫面\",\"Click-drag to scrub\":\"按一下並拖曳以進行編修\",\"Close animation timeline\":\"關閉動畫時間軸線\",\"Animate camera\":\"以動畫顯示相機\",\"When checked, animation pauses whenever the user interacts with camera\":\"如果勾選此選項，每當使用者與相機互動時，動畫就會暫停。\",\"Loop\":\"循環播放\",\"Rewind and play as soon as the animation completes\":\"動畫一完成就倒轉並播放\",\"Speed modifier\":\"速度修改器\"}");

/***/ })

/******/ });
//# sourceMappingURL=Fusion360.js.map