/*!
 * LMV v7.17.1
 * 
 * Copyright 2020 Autodesk, Inc.
 * All rights reserved.
 * 
 * This computer source code and related instructions and comments are the
 * unpublished confidential and proprietary information of Autodesk, Inc.
 * and are protected under Federal copyright and state trade secret law.
 * They may not be disclosed to, copied or used by any third party without
 * the prior written consent of Autodesk, Inc.
 * 
 * Autodesk Forge Viewer Usage Limitations:
 * 
 * The Autodesk Forge viewer can only be used to view files generated by
 * Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be
 * delivered from an Autodesk hosted URL.
 */
Autodesk.Extensions.NPR =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./extensions/NPR/index.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./extensions/NPR/NPRLocales.js":
/*!**************************************!*\
  !*** ./extensions/NPR/NPRLocales.js ***!
  \**************************************/
/*! exports provided: locales */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "locales", function() { return locales; });
/* harmony import */ var _res_locales_en_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../res/locales/en/nobundle-npr.loc.json */ "./res/locales/en/nobundle-npr.loc.json");
var _res_locales_en_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_0___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/en/nobundle-npr.loc.json */ "./res/locales/en/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_cs_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../res/locales/cs/nobundle-npr.loc.json */ "./res/locales/cs/nobundle-npr.loc.json");
var _res_locales_cs_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_1___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/cs/nobundle-npr.loc.json */ "./res/locales/cs/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_de_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../res/locales/de/nobundle-npr.loc.json */ "./res/locales/de/nobundle-npr.loc.json");
var _res_locales_de_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_2___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/de/nobundle-npr.loc.json */ "./res/locales/de/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_es_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../res/locales/es/nobundle-npr.loc.json */ "./res/locales/es/nobundle-npr.loc.json");
var _res_locales_es_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_3___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/es/nobundle-npr.loc.json */ "./res/locales/es/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_fr_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../res/locales/fr/nobundle-npr.loc.json */ "./res/locales/fr/nobundle-npr.loc.json");
var _res_locales_fr_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_4___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr/nobundle-npr.loc.json */ "./res/locales/fr/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_fr_CA_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../../res/locales/fr-CA/nobundle-npr.loc.json */ "./res/locales/fr-CA/nobundle-npr.loc.json");
var _res_locales_fr_CA_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_5___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr-CA/nobundle-npr.loc.json */ "./res/locales/fr-CA/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_it_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../../res/locales/it/nobundle-npr.loc.json */ "./res/locales/it/nobundle-npr.loc.json");
var _res_locales_it_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_6___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/it/nobundle-npr.loc.json */ "./res/locales/it/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_ja_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ../../res/locales/ja/nobundle-npr.loc.json */ "./res/locales/ja/nobundle-npr.loc.json");
var _res_locales_ja_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_7___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ja/nobundle-npr.loc.json */ "./res/locales/ja/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_ko_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ../../res/locales/ko/nobundle-npr.loc.json */ "./res/locales/ko/nobundle-npr.loc.json");
var _res_locales_ko_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_8___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ko/nobundle-npr.loc.json */ "./res/locales/ko/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_pl_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! ../../res/locales/pl/nobundle-npr.loc.json */ "./res/locales/pl/nobundle-npr.loc.json");
var _res_locales_pl_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_9___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pl/nobundle-npr.loc.json */ "./res/locales/pl/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_pt_BR_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ../../res/locales/pt-BR/nobundle-npr.loc.json */ "./res/locales/pt-BR/nobundle-npr.loc.json");
var _res_locales_pt_BR_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_10___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pt-BR/nobundle-npr.loc.json */ "./res/locales/pt-BR/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_ru_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_11__ = __webpack_require__(/*! ../../res/locales/ru/nobundle-npr.loc.json */ "./res/locales/ru/nobundle-npr.loc.json");
var _res_locales_ru_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_11___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ru/nobundle-npr.loc.json */ "./res/locales/ru/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_tr_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_12__ = __webpack_require__(/*! ../../res/locales/tr/nobundle-npr.loc.json */ "./res/locales/tr/nobundle-npr.loc.json");
var _res_locales_tr_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_12___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/tr/nobundle-npr.loc.json */ "./res/locales/tr/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANS_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_13__ = __webpack_require__(/*! ../../res/locales/zh-HANS/nobundle-npr.loc.json */ "./res/locales/zh-HANS/nobundle-npr.loc.json");
var _res_locales_zh_HANS_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_13___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANS/nobundle-npr.loc.json */ "./res/locales/zh-HANS/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANT_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_14__ = __webpack_require__(/*! ../../res/locales/zh-HANT/nobundle-npr.loc.json */ "./res/locales/zh-HANT/nobundle-npr.loc.json");
var _res_locales_zh_HANT_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_14___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANT/nobundle-npr.loc.json */ "./res/locales/zh-HANT/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_nl_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_15__ = __webpack_require__(/*! ../../res/locales/nl/nobundle-npr.loc.json */ "./res/locales/nl/nobundle-npr.loc.json");
var _res_locales_nl_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_15___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/nl/nobundle-npr.loc.json */ "./res/locales/nl/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_sv_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_16__ = __webpack_require__(/*! ../../res/locales/sv/nobundle-npr.loc.json */ "./res/locales/sv/nobundle-npr.loc.json");
var _res_locales_sv_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_16___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/sv/nobundle-npr.loc.json */ "./res/locales/sv/nobundle-npr.loc.json", 1);
/* harmony import */ var _res_locales_da_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_17__ = __webpack_require__(/*! ../../res/locales/da/nobundle-npr.loc.json */ "./res/locales/da/nobundle-npr.loc.json");
var _res_locales_da_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_17___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/da/nobundle-npr.loc.json */ "./res/locales/da/nobundle-npr.loc.json", 1);
/**
 * Include each locale json file and return it in an object
 * that can be consumed by i18n
 */





















var locales = {
  en: _res_locales_en_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_0__,

  cs: _res_locales_cs_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_1__,
  de: _res_locales_de_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_2__,
  es: _res_locales_es_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_3__,
  fr: _res_locales_fr_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_4__,
  "fr-CA": _res_locales_fr_CA_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_5__,
  it: _res_locales_it_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_6__,
  ja: _res_locales_ja_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_7__,
  ko: _res_locales_ko_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_8__,
  pl: _res_locales_pl_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_9__,
  "pt-BR": _res_locales_pt_BR_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_10__,
  ru: _res_locales_ru_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_11__,
  tr: _res_locales_tr_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_12__,
  "zh-HANS": _res_locales_zh_HANS_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_13__,
  "zh-HANT": _res_locales_zh_HANT_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_14__,
  nl: _res_locales_nl_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_15__,
  sv: _res_locales_sv_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_16__,
  da: _res_locales_da_nobundle_npr_loc_json__WEBPACK_IMPORTED_MODULE_17__ };

/***/ }),

/***/ "./extensions/NPR/NPRRenderContextExtension.js":
/*!*****************************************************!*\
  !*** ./extensions/NPR/NPRRenderContextExtension.js ***!
  \*****************************************************/
/*! exports provided: NPRRenderContextExtension */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "NPRRenderContextExtension", function() { return NPRRenderContextExtension; });
/**
 * NPR related functions are moved to an extension
 * to keep default LMV render context unadulterated, and
 * to help customers to implement their own postprocess extensions.
 * This is achieved by extending RenderContextPostProcessExtension.
 */

var POSTPROC_STYLE_OFF = 0;
var POSTPROC_STYLE_EDGING = 1;
var POSTPROC_STYLE_CEL = 2;
var POSTPROC_STYLE_GRAPHITE = 3;
var POSTPROC_STYLE_PENCIL = 4;

var getResourceUrl = Autodesk.Viewing.Private.getResourceUrl;
var ShaderPass = Autodesk.Viewing.Private.ShaderPass;
var CelShader = Autodesk.Viewing.Private.CelShader;
var RenderContextPostProcessExtension = Autodesk.Viewing.Private.RenderContextPostProcessExtension;

var av = Autodesk.Viewing;

var NPRRenderContextExtension = function NPRRenderContextExtension(renderContext, viewer) {
  RenderContextPostProcessExtension.call(this, renderContext);

  this.viewer = viewer;
  this.setGlobalManager(viewer.globalManager);

  // Initialize private variables
  var _postProcPass = null;
  var _pencilMap = null;
  var _graphiteMaps = [];
  var _pencilBackgroundMap = null;

  this.preloadPostProcessStyle = function (style) {
    if (style == undefined) {
      // if no argument given, load them all
      this.preloadPostProcessStyle("graphite");
      this.preloadPostProcessStyle("pencil");
      return;
    }
    switch (style) {
      case "graphite":
        if (_graphiteMaps[0] === undefined) {// TODO better way to test? Note it differs from the one below
          // LMV-2820 fix - we are in control of the URL, so to have Ninja function, we allow load from "another" site.
          THREE.ImageUtils.crossOrigin = '';
          for (var i = 0; i < 8; i++) {
            var file = getResourceUrl("extensions/NPR/res/postprocess/Graphite" + (i + 1) + ".png");
            _graphiteMaps[i] = THREE.ImageUtils.loadTexture(file);
            //_graphiteMaps[i] = THREE.ImageUtils.loadTexture("http://localhost:8000/build/res/postprocess/Graphite" + (i+1) + ".png"); 
            _graphiteMaps[i].wrapS = _graphiteMaps[i].wrapT = THREE.RepeatWrapping;
          }
          _postProcPass.uniforms['tGraphite1'].value = _graphiteMaps[0];
          _postProcPass.uniforms['tGraphite2'].value = _graphiteMaps[1];
          _postProcPass.uniforms['tGraphite3'].value = _graphiteMaps[2];
          _postProcPass.uniforms['tGraphite4'].value = _graphiteMaps[3];
          _postProcPass.uniforms['tGraphite5'].value = _graphiteMaps[4];
          _postProcPass.uniforms['tGraphite6'].value = _graphiteMaps[5];
          _postProcPass.uniforms['tGraphite7'].value = _graphiteMaps[6];
          _postProcPass.uniforms['tGraphite8'].value = _graphiteMaps[7];
        }
        break;
      case "pencil":
        if (_pencilMap === null) {// TODO better way to test?
          // LMV-2820 fix - we are in control of the URL, so to have Ninja function, we allow load from "another" site.
          THREE.ImageUtils.crossOrigin = '';
          _pencilMap = THREE.ImageUtils.loadTexture(getResourceUrl("extensions/NPR/res/postprocess/ColorPencil_02.png"));
          _pencilMap.wrapS = _pencilMap.wrapT = THREE.RepeatWrapping;
          _pencilBackgroundMap = THREE.ImageUtils.loadTexture(getResourceUrl("extensions/NPR/res/postprocess/paper2.jpg"));
          _pencilBackgroundMap.wrapS = _pencilBackgroundMap.wrapT = THREE.RepeatWrapping;

          _postProcPass.uniforms['tFill'].value = _pencilMap;
          _postProcPass.uniforms['tPaper'].value = _pencilBackgroundMap;
        }
        break;}

  };

  // returns 1 (or some other error code) on failure, 0 on success
  this.setPostProcessParameter = function (token, value) {
    this.changePostProcessParameter(token, value);

    this.viewer.impl.fireRenderOptionChanged();
    this.viewer.impl.invalidate(true);
  };


  this.changePostProcessParameter = function (token, value) {
    var _settings = this.renderContext.settings;

    switch (token) {
      case "style":
        _settings.postProcShaded = false;
        _postProcPass.uniforms['style'].value = POSTPROC_STYLE_OFF;
        if (this.renderContext.depthTargetSupported()) {
          // put this code back in if we can't run with mobile
          // if _isWeakDevice, I guess we can't use? Needs ID buffer and normals/depths.
          // if ( _isWeakDevice ) {
          //     // sorry, not available on mobile - needs ID buffer and normal/depth buffer
          //     return 1;
          // } else {
          // load any textures that haven't been loaded.
          this.preloadPostProcessStyle(value);
          switch (value) {
            case "edging":
              _settings.postProcShaded = true;
              _postProcPass.uniforms['style'].value = POSTPROC_STYLE_EDGING;
              break;
            case "cel":
              _settings.postProcShaded = true;
              _postProcPass.uniforms['style'].value = POSTPROC_STYLE_CEL;
              break;
            case "graphite":
              _settings.postProcShaded = true;
              _postProcPass.uniforms['style'].value = POSTPROC_STYLE_GRAPHITE;
              break;
            case "pencil":
              _settings.postProcShaded = true;
              _postProcPass.uniforms['style'].value = POSTPROC_STYLE_PENCIL;
              break;}

          if (_settings.postProcShaded) {
            _settings.idbuffer = true;
          } else {
            _settings.idbuffer = !this.renderContext.isWeakDevice(); // TODO are these good conditions?    
          }

          this.renderContext.initPostPipeline(_settings.sao, _settings.antialias);
        }
        break;

      case "edges":
        _postProcPass.uniforms['idEdges'].value = value ? 1 : 0;
        _postProcPass.uniforms['normalEdges'].value = value ? 1 : 0;
        _postProcPass.uniforms['depthEdges'].value = value ? 1 : 0;
        // turning off edges means we can use considerably less memory and fragment shading evaluations,
        // i.e., we can use normal-resolution off-screen targets, not 2x2 larger
        this.renderContext.initPostPipeline(_settings.sao, _settings.antialias);
        break;
      case "idEdges":
        _postProcPass.uniforms['idEdges'].value = value ? 1 : 0;
        this.renderContext.initPostPipeline(_settings.sao, _settings.antialias);
        break;
      case "normalEdges":
        _postProcPass.uniforms['normalEdges'].value = value ? 1 : 0;
        this.renderContext.initPostPipeline(_settings.sao, _settings.antialias);
        break;
      case "depthEdges":
        _postProcPass.uniforms['depthEdges'].value = value ? 1 : 0;
        this.renderContext.initPostPipeline(_settings.sao, _settings.antialias);
        break;
      case "brightness":
        _postProcPass.uniforms['brightness'].value = value;
        break;
      case "contrast":
        _postProcPass.uniforms['contrast'].value = value;
        break;
      case "grayscale":
        _postProcPass.uniforms['grayscale'].value = value ? 1 : 0;
        break;
      case "preserveColor":
        _postProcPass.uniforms['preserveColor'].value = value ? 1 : 0;
        break;
      case "levels":
        _postProcPass.uniforms['levels'].value = value;
        break;
      case "repeats":
        _postProcPass.uniforms['repeats'].value = value;
        break;
      case "rotation": // 0.0 to 1.0, around circle (e.g. 0.5 == pi radians, 1.0 == 2*pi)
        _postProcPass.uniforms['rotation'].value = value;
        break;
      default:
        console.error("setPostProcessParameter: parameter '" + token + "' is not valid.");}


    return 0;
  };

  // TODO what's a better return value if undefined? Or just issue a warning? Should there be a separate query function?
  this.queryPostProcessParameter = function (token, value) {
    if (_postProcPass.uniforms[token] !== 'undefined') {
      return _postProcPass.uniforms[token].value;
    } else {
      logger.warning("queryPostProcessParameter: parameter '" + token + "' is not valid");
      return value;
    }
  };

  this.load = function () {
    _postProcPass = new ShaderPass(CelShader);
    this.renderContext.setNoDepthNoBlend(_postProcPass);

    // Initialize the NPR related resources
    this.preloadPostProcessStyle();
  };

  this.unload = function () {

    this.changePostProcessParameter('style', null);

    // Need to do some cleanup here, once user deactive the extension
    // Can we remove all those resources to safe a little bit memory
    var _iteratorNormalCompletion = true;var _didIteratorError = false;var _iteratorError = undefined;try {for (var _iterator = _graphiteMaps[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {var texture = _step.value;
        texture.dispose();
      }} catch (err) {_didIteratorError = true;_iteratorError = err;} finally {try {if (!_iteratorNormalCompletion && _iterator.return != null) {_iterator.return();}} finally {if (_didIteratorError) {throw _iteratorError;}}}

    _graphiteMaps = [];

    this.viewer = undefined;
    this.renderContext = undefined;
  };

  this.updateUniformValue = function (key, value, usingCopy) {
    if (usingCopy) {
      _postProcPass.uniforms[key].value.copy(value);
    } else {
      _postProcPass.uniforms[key].value = value;
    }
  };

  this.postProcessEdgesOn = function () {
    return _postProcPass.uniforms['idEdges'].value !== 0 ||
    _postProcPass.uniforms['normalEdges'].value !== 0 ||
    _postProcPass.uniforms['depthEdges'].value !== 0;
  };

  this.setMaterialNeedsUpdate = function () {
    _postProcPass.material.needsUpdate = true;
  };

  this.render = function (renderer, outTarget, inTarget) {
    _postProcPass.render(renderer, outTarget, inTarget);
  };

  this.changeResolution = function (resX, resY) {
    _postProcPass.uniforms["resolution"].value.set(resX, resY);
  };
};

NPRRenderContextExtension.prototype = Object.create(RenderContextPostProcessExtension.prototype);
NPRRenderContextExtension.prototype.constructor = NPRRenderContextExtension;
av.GlobalManagerMixin.call(NPRRenderContextExtension.prototype);



/***/ }),

/***/ "./extensions/NPR/NPRRenderOptionsPanel.js":
/*!*************************************************!*\
  !*** ./extensions/NPR/NPRRenderOptionsPanel.js ***!
  \*************************************************/
/*! exports provided: NPRRenderOptionsPanel */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "NPRRenderOptionsPanel", function() { return NPRRenderOptionsPanel; });




var TAB_ID = 'configTab';
var TAB_LABEL = 'Configuration';
var POST_PROCESS_LABEL = 'Postprocess Style';
var DISPLAY_EDGES = 'Display edges';
var DISPLAY_EDGES_DESC = 'Controls whether edge lines should be drawn around objects';
var GRAYSCALE = 'Grayscale';
var GRAYSCALE_DESC = 'Converts the rendering to grayscale with no color';
var BRIGHTNESS = 'Brightness';
var CONTRAST = 'Contrast';
var PRESERVE_COLOR = 'Preserve Color';
var PRESERVE_COLOR_DESC = 'Maintains the hue by pulling the color back into gamut if its too high';
var LEVELS = 'Levels';
var REPEATS = 'Repeats';
var ROTATION = 'Rotation';

var NPRRenderOptionsPanel = function NPRRenderOptionsPanel(viewer, extension, title) {var _this = this;
  var PANEL_ID = 'adsk_npr_renderoptions_panel_' + viewer.id;
  var opts = { heightAdjustment: 90, width: 460 };
  Autodesk.Viewing.UI.SettingsPanel.call(this, viewer.container, PANEL_ID, title, opts);
  this.setGlobalManager(viewer.globalManager);
  this.container.classList.add('viewer-settings-panel');
  this.viewer = viewer;

  // Add a default tab called Render Options
  this.addTab(TAB_ID, TAB_LABEL, { className: 'config' });
  this.selectTab(TAB_ID);

  // DropDown "Postprocess Style"
  var postProcessList = ['none', 'edging', 'cel', 'graphite', 'pencil'];

  this.postProcess = this.addDropDownMenu(TAB_ID, POST_PROCESS_LABEL, postProcessList, 0, function (event) {
    var value = event.detail.value;

    // load them all up, since someone is fiddling with style
    extension.preloadPostProcessStyle();
    extension.setPostProcessParameter("style", postProcessList[value]);

    var styleVal = Math.floor(parseFloat(value));
    var enable = styleVal != 0.0;
    _this.edgesCheckbox.setDisabled(!enable);
    _this.grayscaleCheckbox.setDisabled(!enable);
    _this.brightnessSlider.setDisabled(!enable);
    _this.contrastSlider.setDisabled(!enable);
    _this.preserveColorCheckbox.setDisabled(!enable);
    _this.levelsSlider.setDisabled(styleVal !== 2.0);
    _this.repeatsSlider.setDisabled(styleVal < 3.0);
    _this.rotationSlider.setDisabled(styleVal < 3.0);
  });
  this.postProcessDropdown = this.getControl(this.postProcess);

  // Checkbox "Display Edges"
  this.edgesToggle = this.addCheckbox(TAB_ID, DISPLAY_EDGES, true, function (checked) {
    extension.setPostProcessParameter("edges", checked);
  }, DISPLAY_EDGES_DESC);
  this.edgesCheckbox = this.getControl(this.edgesToggle);

  // Checkbox "Gray Scale"
  this.grayscaleToggle = this.addCheckbox(TAB_ID, GRAYSCALE, true, function (checked) {
    extension.setPostProcessParameter("grayscale", checked);
  }, GRAYSCALE_DESC);
  this.grayscaleCheckbox = this.getControl(this.grayscaleToggle);

  // Slider "Brightness"
  this.brightness = this.addSlider(TAB_ID, BRIGHTNESS,
  -1.0, 1.0, 0.0,
  function (event) {
    var value = event.detail.value;
    extension.setPostProcessParameter('brightness', parseFloat(value));
  },
  { step: 0.01 });

  this.brightnessSlider = this.getControl(this.brightness);

  // Slider "Contrast"
  this.contrast = this.addSlider(TAB_ID, CONTRAST,
  -1.0, 1.0, 0.0,
  function (event) {
    var value = event.detail.value;
    extension.setPostProcessParameter('contrast', parseFloat(value));
  },
  { step: 0.01 });

  this.contrastSlider = this.getControl(this.contrast);

  // Checkbox "Preserve Color"
  this.preserveColorToggle = this.addCheckbox(TAB_ID, PRESERVE_COLOR, true, function (checked) {
    extension.setPostProcessParameter("preserveColor", checked);
  }, PRESERVE_COLOR_DESC);
  this.preserveColorCheckbox = this.getControl(this.preserveColorToggle);

  // Slider "Levels"
  this.levels = this.addSlider(TAB_ID, LEVELS, 2.0, 2.99, 0,
  function (event) {
    var value = event.detail.value;
    extension.setPostProcessParameter("levels", 2 * parseFloat(value));
  }, { step: 0.01 });

  this.levelsSlider = this.getControl(this.levels);

  // Slider "Repeats"
  this.repeats = this.addSlider(TAB_ID, REPEATS, 3.0, 5.0, 3.0,
  function (event) {
    var value = event.detail.value;
    // "graphite" value ranges from 3.0 - 3.99;
    // "pencil" value ranges from 4.0 - 5.0;
    extension.setPostProcessParameter("repeats", parseFloat(value));
  }, { step: 0.01 });
  this.repeatsSlider = this.getControl(this.repeats);

  // Slider "Rotation"
  this.rotation = this.addSlider(TAB_ID, ROTATION,
  0.0, 1.0, 0.0,
  function (event) {
    var value = event.detail.value;
    extension.setPostProcessParameter("rotation", parseFloat(value));
  },
  { step: 0.01 });

  this.rotationSlider = this.getControl(this.rotation);
};

NPRRenderOptionsPanel.prototype = Object.create(Autodesk.Viewing.UI.SettingsPanel.prototype);
NPRRenderOptionsPanel.prototype.constructor = NPRRenderOptionsPanel;



/***/ }),

/***/ "./extensions/NPR/index.js":
/*!*********************************!*\
  !*** ./extensions/NPR/index.js ***!
  \*********************************/
/*! exports provided: NPRExtension */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "NPRExtension", function() { return NPRExtension; });
/* harmony import */ var _NPRRenderContextExtension__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./NPRRenderContextExtension */ "./extensions/NPR/NPRRenderContextExtension.js");
/* harmony import */ var _NPRRenderOptionsPanel__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./NPRRenderOptionsPanel */ "./extensions/NPR/NPRRenderOptionsPanel.js");
/* harmony import */ var _NPRLocales__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./NPRLocales */ "./extensions/NPR/NPRLocales.js");




var SETTINGS_BUTTON_LABEL = 'Non-Photorealistic Rendering';

var Extension = Autodesk.Viewing.Extension;

/**
                                             * Provides UI controls for NPR settings
                                             * 
                                             * The extension id is: `Autodesk.NPR`
                                             * 
                                             * @example
                                             *    viewer.loadExtension('Autodesk.NPR');
                                             * 
                                             * @memberof Autodesk.Viewing.Extensions.NPR
                                             * @see {@link Autodesk.Viewing.Extension} for common inherited methods.
                                             * @constructor
                                             * @param {Autodesk.Viewing.Viewer3D} viewer - Viewer instance.
                                             * @param {Object} options - Not used.
                                             */
function NPRExtension(viewer, options) {
  Extension.call(this, viewer, options);
  this.viewer = viewer;
  this._configButtonId = null;
  this._panel = null;
  this.hasUI = Autodesk.Viewing.GuiViewer3D && viewer instanceof Autodesk.Viewing.GuiViewer3D;
  this.openPanel = this.openPanel.bind(this);
  this._initButtonConfig = this._initButtonConfig.bind(this);
};

NPRExtension.prototype = Object.create(Autodesk.Viewing.Extension.prototype);
NPRExtension.prototype.constructor = NPRExtension;

/**
                                                    * Load the NPR extension.
                                                    * It will fail to load when running a headless viewer.
                                                    */
NPRExtension.prototype.load = function () {
  this.extendLocalization(_NPRLocales__WEBPACK_IMPORTED_MODULE_2__["locales"]);
  this.nprRenderContextExtension = new _NPRRenderContextExtension__WEBPACK_IMPORTED_MODULE_0__["NPRRenderContextExtension"](this.viewer.impl.renderer(), this.viewer);
  this.nprRenderContextExtension.load();
  this.viewer.impl.renderer().postShadingManager().registerPostProcessingExtension(this.nprRenderContextExtension);
  return true;
};

/**
    * Unload the NPR extension.
    */
NPRExtension.prototype.unload = function () {
  if (this._configButtonId !== null) {
    this.viewer.viewerSettingsPanel.removeConfigButton(this._configButtonId);
    this._configButtonId = null;
  }
  if (this._panel) {
    this._panel.uninitialize();
    this._panel = null;
  }
  if (this.nprRenderContextExtension) {
    this.viewer.impl.renderer().postShadingManager().removePostProcessingExtension();
    this.viewer.impl.invalidate(true, true, true);
    this.nprRenderContextExtension = null;
  }
  return true;
};

/**
    * Invoked by the viewer when the toolbar UI is available. 
    * Adds a button to the Settings panel.
    *
    * @alias Autodesk.Viewing.Extensions.NPRExtension#onToolbarCreated
    */
NPRExtension.prototype.onToolbarCreated = function () {
  this._initButtonConfig();
};

/**
    * Opens the NPR Render Options panel.
    *
    * @alias Autodesk.Viewing.Extensions.NPRExtension#openPanel
    */
NPRExtension.prototype.openPanel = function () {
  if (!this._panel) {
    this._panel = new _NPRRenderOptionsPanel__WEBPACK_IMPORTED_MODULE_1__["NPRRenderOptionsPanel"](this.viewer, this.nprRenderContextExtension, SETTINGS_BUTTON_LABEL);
  }
  this._panel.setVisible(true);
};

/**
    * Changes post-processing setting parameters. The supported param/value combinations are:
    * 
    * - "style": either "edging", "cel", "graphite", "pencil" or `null` to turn post-processing off.
    * - "edges": `boolean`
    * - "idEdges": `boolean`
    * - "normalEdges": `boolean` 
    * - "depthEdges": `boolean`
    * - "brightness": `Number`
    * - "contrast": `Number`
    * - "grayscale": `boolean`
    * - "preserveColor": `boolean`
    * - "levels": `Number`
    * - "repeats": `Number`
    * - "rotation": `Number` between 0 and 1, around circle (e.g. 0.5 == pi radians, 1.0 == 2*pi)
    *
    * Fires event {@link RENDER_OPTION_CHANGED_EVENT}.
    *
    * @param {string} param - Either "style", "edges", "idEdges", "normalEdges", "depthEdges", "brightness", 
    *                         "contrast", "grayscale", "preserveColor", "levels", "repeats" or "rotation".
    * @param {*} value - type depends on the specified `param`.
    *
    * @alias Autodesk.Viewing.Extensions.NPRExtension#setParameter
    */
NPRExtension.prototype.setParameter = function (param, value) {
  this.nprRenderContextExtension.setPostProcessParameter(param, value);
};

/**
    * Adds a button to the Settings Panel.
    * @private
    */
NPRExtension.prototype._initButtonConfig = function () {
  var settingsPanel = this.viewer.getSettingsPanel();
  if (!settingsPanel) {
    this.addEventListener(av.TOOLBAR_CREATED_EVENT, this._initButtonConfig, { once: true });
    return;
  }
  this._configButtonId = settingsPanel.addConfigButton(SETTINGS_BUTTON_LABEL, this.openPanel);
};


/**
    * Register the extension with the extension manager.
    */
Autodesk.Viewing.theExtensionManager.registerExtension('Autodesk.NPR', NPRExtension);

/***/ }),

/***/ "./res/locales/cs/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/cs/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"cs\",\"@@context\":\"Rozšíření Nefotorealistické rendrování\",\"Non-Photorealistic Rendering\":\"Nefotorealistické rendrování\",\"Postprocess Style\":\"Styl následného zpracování\",\"Controls whether edge lines should be drawn around object\":\"Určuje, zda se mají čáry hran kreslit kolem objektu.\",\"Grayscale\":\"Odstíny šedi\",\"Converts the rendering to grayscale with no color\":\"Převede rendrovaný výsledek na stupně šedé bez barev.\",\"Brightness\":\"Jas\",\"Preserve Color\":\"Zachovat barvu\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Zachová odstín vrácením barvy zpět do škály barev, pokud je příliš vysoká.\",\"Levels\":\"Úrovně\",\"Repeats\":\"Opakování\",\"Rotation\":\"Natočení\"}");

/***/ }),

/***/ "./res/locales/da/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/da/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"da\",\"@@context\":\"Udvidelse til Ikke-fotorealistisk rendering\",\"Non-Photorealistic Rendering\":\"Ikke-fotorealistisk rendering\",\"Postprocess Style\":\"Efterbehandlingsstil\",\"Controls whether edge lines should be drawn around object\":\"Kontrollerer, om der skal tegnes kantlinjer omkring objekt\",\"Grayscale\":\"Gråtone\",\"Converts the rendering to grayscale with no color\":\"Konverterer renderingen til gråtone uden farve\",\"Brightness\":\"Lysstyrke\",\"Preserve Color\":\"Bevar farve\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Bevarer nuancen ved at trække farven tilbage i spektret, hvis den er for høj\",\"Levels\":\"Niveauer\",\"Repeats\":\"Gentagelser\",\"Rotation\":\"Rotation\"}");

/***/ }),

/***/ "./res/locales/de/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/de/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"de\",\"@@context\":\"Erweiterung für nicht fotorealistisches Rendering\",\"Non-Photorealistic Rendering\":\"Nicht fotorealistisches Rendering\",\"Postprocess Style\":\"Nachbearbeitungsstil\",\"Controls whether edge lines should be drawn around object\":\"Bestimmt, ob Kantenlinien um das Objekt gezeichnet werden sollen\",\"Grayscale\":\"Graustufen\",\"Converts the rendering to grayscale with no color\":\"Wandelt das Rendering in Graustufen ohne Farbe um\",\"Brightness\":\"Helligkeit\",\"Preserve Color\":\"Farben beibehalten\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Behält den Farbton bei, indem der Farbwert in die Farbskala zurückgezogen wird, wenn er zu hoch ist\",\"Levels\":\"Ebenen\",\"Repeats\":\"Wiederholungen\",\"Rotation\":\"Drehung\"}");

/***/ }),

/***/ "./res/locales/en/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/en/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"en\",\"@@context\":\"Non-Photorealistic Rendering extension\",\"Non-Photorealistic Rendering\":\"Non-Photorealistic Rendering\",\"Postprocess Style\":\"Postprocess Style\",\"Controls whether edge lines should be drawn around object\":\"Controls whether edge lines should be drawn around object\",\"Grayscale\":\"Grayscale\",\"Converts the rendering to grayscale with no color\":\"Converts the rendering to grayscale with no color\",\"Brightness\":\"Brightness\",\"Preserve Color\":\"Preserve Color\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Maintains the hue by pulling the color back into gamut if its too high\",\"Levels\":\"Levels\",\"Repeats\":\"Repeats\",\"Rotation\":\"Rotation\"}");

/***/ }),

/***/ "./res/locales/es/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/es/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"es\",\"@@context\":\"Extensión de renderización no fotorrealista\",\"Non-Photorealistic Rendering\":\"Renderización no fotorrealista\",\"Postprocess Style\":\"Estilo de procesamiento posterior\",\"Controls whether edge lines should be drawn around object\":\"Determina si se deben dibujar las líneas de arista alrededor del objeto.\",\"Grayscale\":\"Escala de grises\",\"Converts the rendering to grayscale with no color\":\"Convierte la renderización a escala de grises sin color.\",\"Brightness\":\"Brillo\",\"Preserve Color\":\"Conservar color\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Mantiene el tono restableciendo el color dentro de la gama si es demasiado alto.\",\"Levels\":\"Niveles\",\"Repeats\":\"Repetición\",\"Rotation\":\"Rotación\"}");

/***/ }),

/***/ "./res/locales/fr-CA/nobundle-npr.loc.json":
/*!*************************************************!*\
  !*** ./res/locales/fr-CA/nobundle-npr.loc.json ***!
  \*************************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr-CA\",\"@@context\":\"Extension de rendu non photoréaliste\",\"Non-Photorealistic Rendering\":\"Rendu non photoréaliste\",\"Postprocess Style\":\"Style de post-traitement\",\"Controls whether edge lines should be drawn around object\":\"Contrôle l’affichage de lignes de bordure autour de l’objet\",\"Grayscale\":\"Échelle de gris\",\"Converts the rendering to grayscale with no color\":\"Affiche le rendu dans une échelle de gris sans couleur\",\"Brightness\":\"Luminosité\",\"Preserve Color\":\"Préserver la couleur\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Conserve la teinte et, si elle est trop vive, en ajuste la couleur selon la gamme de couleurs\",\"Levels\":\"Niveaux\",\"Repeats\":\"Répétitions\",\"Rotation\":\"Rotation\"}");

/***/ }),

/***/ "./res/locales/fr/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/fr/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr\",\"@@context\":\"Extension de rendu non photoréaliste\",\"Non-Photorealistic Rendering\":\"Rendu non photoréaliste\",\"Postprocess Style\":\"Style de post-traitement\",\"Controls whether edge lines should be drawn around object\":\"Détermine si des lignes d'arête doivent être dessinées autour de l'objet\",\"Grayscale\":\"Gamme de gris\",\"Converts the rendering to grayscale with no color\":\"Convertit le rendu en gamme de gris sans couleur\",\"Brightness\":\"Luminosité\",\"Preserve Color\":\"Conserver la couleur\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Conserve la teinte en retirant la couleur de la gamme si elle est trop élevée\",\"Levels\":\"Niveaux\",\"Repeats\":\"Répétitions\",\"Rotation\":\"Rotation\"}");

/***/ }),

/***/ "./res/locales/it/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/it/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"it\",\"@@context\":\"Estensione di rendering non fotorealistico\",\"Non-Photorealistic Rendering\":\"Rendering non fotorealistico\",\"Postprocess Style\":\"Stile di post-elaborazione\",\"Controls whether edge lines should be drawn around object\":\"Controlla se le linee dei bordi devono essere disegnate attorno all'oggetto\",\"Grayscale\":\"Scala di grigi\",\"Converts the rendering to grayscale with no color\":\"Converte il rendering in scala di grigi senza colore\",\"Brightness\":\"Luminosità\",\"Preserve Color\":\"Mantieni colore\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Mantiene la tonalità riportando il colore nella gamma se è troppo alta\",\"Levels\":\"Livelli\",\"Repeats\":\"Ripetizioni\",\"Rotation\":\"Rotazione\"}");

/***/ }),

/***/ "./res/locales/ja/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/ja/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ja\",\"@@context\":\"非フォトリアリスティック レンダリング エクステンション\",\"Non-Photorealistic Rendering\":\"非フォトリアリスティック レンダリング\",\"Postprocess Style\":\"ポストプロセス スタイル\",\"Controls whether edge lines should be drawn around object\":\"エッジ ラインをオブジェクトの周囲に描画するかどうかをコントロールします\",\"Grayscale\":\"グレースケール\",\"Converts the rendering to grayscale with no color\":\"レンダリングを色のないグレースケールに変換します\",\"Brightness\":\"明るさ\",\"Preserve Color\":\"色を保持\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"高すぎる場合は、色を色域に戻すことによって色相を維持します。\",\"Levels\":\"レベル\",\"Repeats\":\"繰り返し\",\"Rotation\":\"回転\"}");

/***/ }),

/***/ "./res/locales/ko/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/ko/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ko\",\"@@context\":\"비사실적 렌더링 확장\",\"Non-Photorealistic Rendering\":\"비사실적 렌더링\",\"Postprocess Style\":\"사후 처리 스타일\",\"Controls whether edge lines should be drawn around object\":\"객체 주위에 모서리 선을 그려야 하는지 여부를 제어합니다.\",\"Grayscale\":\"회색조\",\"Converts the rendering to grayscale with no color\":\"렌더링을 색상 없는 회색조로 변환합니다.\",\"Brightness\":\"밝기\",\"Preserve Color\":\"색상 유지\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"색조가 너무 높은 경우 색상을 색 영역으로 가져와 색조를 유지합니다.\",\"Levels\":\"레벨\",\"Repeats\":\"반복\",\"Rotation\":\"회전\"}");

/***/ }),

/***/ "./res/locales/nl/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/nl/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"nl\",\"@@context\":\"Extensie voor niet-fotorealistische rendering\",\"Non-Photorealistic Rendering\":\"Niet-fotorealistische rendering\",\"Postprocess Style\":\"Stijl nabewerken\",\"Controls whether edge lines should be drawn around object\":\"Bepaalt of er om een object randlijnen moeten worden getekend\",\"Grayscale\":\"Grijstinten\",\"Converts the rendering to grayscale with no color\":\"Converteert de rendering naar grijstinten zonder kleur\",\"Brightness\":\"Helderheid\",\"Preserve Color\":\"Kleur behouden\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Zorgt dat de tinten behouden blijven door de kleur terug te trekken naar het kleurengamma wanneer deze te hoog is\",\"Levels\":\"Niveaus\",\"Repeats\":\"Herhaalt\",\"Rotation\":\"Draaien\"}");

/***/ }),

/***/ "./res/locales/pl/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/pl/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pl\",\"@@context\":\"Rozszerzenie inne niż fotorealistyczne renderowanie\",\"Non-Photorealistic Rendering\":\"Inne niż fotorealistyczne renderowanie\",\"Postprocess Style\":\"Styl postprocesu\",\"Controls whether edge lines should be drawn around object\":\"Określa, czy mają być rysowane linie krawędzi wokół obiektu\",\"Grayscale\":\"Skala szarości\",\"Converts the rendering to grayscale with no color\":\"Przekształca renderowanie w skalę szarości bez koloru\",\"Brightness\":\"Jasność\",\"Preserve Color\":\"Zachowaj kolor\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Zachowuje odcień koloru przez wciągnięcie koloru z powrotem do gamy, jeśli zbyt duży\",\"Levels\":\"Poziomy\",\"Repeats\":\"Powtórzenia\",\"Rotation\":\"Obrót\"}");

/***/ }),

/***/ "./res/locales/pt-BR/nobundle-npr.loc.json":
/*!*************************************************!*\
  !*** ./res/locales/pt-BR/nobundle-npr.loc.json ***!
  \*************************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ptb\",\"@@context\":\"Extensão da Renderização não fotorrealista\",\"Non-Photorealistic Rendering\":\"Renderização não fotorrealista\",\"Postprocess Style\":\"Estilo pós-processamento\",\"Controls whether edge lines should be drawn around object\":\"Controla se as linhas de borda devem ser desenhadas à volta do objeto\",\"Grayscale\":\"Escala de cinza\",\"Converts the rendering to grayscale with no color\":\"Converte a renderização em escala de cinza sem nenhuma cor\",\"Brightness\":\"Brilho\",\"Preserve Color\":\"Preservar cor\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Mantém a matiz reduzindo a gama de cores, se ela for muito alta\",\"Levels\":\"Níveis\",\"Repeats\":\"Repetições\",\"Rotation\":\"Rotação\"}");

/***/ }),

/***/ "./res/locales/ru/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/ru/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ru\",\"@@context\":\"Расширение для нефотореалистичной визуализации\",\"Non-Photorealistic Rendering\":\"Нефотореалистичная визуализация\",\"Postprocess Style\":\"Стиль постобработки\",\"Controls whether edge lines should be drawn around object\":\"Управление отображением линий ребер вокруг объекта\",\"Grayscale\":\"Оттенки серого\",\"Converts the rendering to grayscale with no color\":\"Преобразование визуализации в оттенки серого без цвета\",\"Brightness\":\"Яркость\",\"Preserve Color\":\"Сохранить цвет\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Сохранение оттенка путем возврата цвета в гамму, если он находится слишком высоко\",\"Levels\":\"Уровни\",\"Repeats\":\"Повторы\",\"Rotation\":\"Поворот\"}");

/***/ }),

/***/ "./res/locales/sv/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/sv/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"sv\",\"@@context\":\"Icke fotorealistisk rendering-tillägg\",\"Non-Photorealistic Rendering\":\"Icke fotorealistisk rendering\",\"Postprocess Style\":\"Efterbearbetningsformat\",\"Controls whether edge lines should be drawn around object\":\"Styr om kantlinjer ska ritas runt objektet\",\"Grayscale\":\"Gråskala\",\"Converts the rendering to grayscale with no color\":\"Konverterar renderingen till gråskala utan färg\",\"Brightness\":\"Ljusstyrka\",\"Preserve Color\":\"Bevara färg\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Bibehåller nyansen genom att dra tillbaka färgen i tonskala om den är för hög\",\"Levels\":\"Nivåer\",\"Repeats\":\"Upprepningar\",\"Rotation\":\"Rotation\"}");

/***/ }),

/***/ "./res/locales/tr/nobundle-npr.loc.json":
/*!**********************************************!*\
  !*** ./res/locales/tr/nobundle-npr.loc.json ***!
  \**********************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"tr\",\"@@context\":\"Fotorealistik Olmayan İşleme uzantısı\",\"Non-Photorealistic Rendering\":\"Fotorealistik Olmayan İşleme\",\"Postprocess Style\":\"İşlem sonrası Stili\",\"Controls whether edge lines should be drawn around object\":\"Kenar çizgilerinin nesnenin çevresine çizilip çizilmeyeceğini kontrol eder\",\"Grayscale\":\"Gri Tonlama\",\"Converts the rendering to grayscale with no color\":\"İşlemeyi renk olmadan gri tonlamaya dönüştürür\",\"Brightness\":\"Parlaklık\",\"Preserve Color\":\"Rengi Koru\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"Yüksek olduğunda rengi skalasına geri çekerek tonu sağlar\",\"Levels\":\"Seviyeler\",\"Repeats\":\"Tekrarlar\",\"Rotation\":\"Döndürme\"}");

/***/ }),

/***/ "./res/locales/zh-HANS/nobundle-npr.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/zh-HANS/nobundle-npr.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hans\",\"@@context\":\"非照片级真实感渲染尺寸\",\"Non-Photorealistic Rendering\":\"非照片级真实感渲染\",\"Postprocess Style\":\"后处理样式\",\"Controls whether edge lines should be drawn around object\":\"控制边线是否应围绕对象绘制\",\"Grayscale\":\"灰度\",\"Converts the rendering to grayscale with no color\":\"可以将渲染转换为没有颜色的灰度\",\"Brightness\":\"亮度\",\"Preserve Color\":\"保留颜色\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"通过将颜色拉回到色域(如果太高)，可保留色调\",\"Levels\":\"标高\",\"Repeats\":\"重复\",\"Rotation\":\"旋转\"}");

/***/ }),

/***/ "./res/locales/zh-HANT/nobundle-npr.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/zh-HANT/nobundle-npr.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Non-Photorealistic Rendering, Postprocess Style, Controls whether edge lines should be drawn around object, Grayscale, Converts the rendering to grayscale with no color, Brightness, Preserve Color, Maintains the hue by pulling the color back into gamut if its too high, Levels, Repeats, Rotation, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hant\",\"@@context\":\"非相片擬真彩現延伸\",\"Non-Photorealistic Rendering\":\"非相片擬真彩現\",\"Postprocess Style\":\"後處理型式\",\"Controls whether edge lines should be drawn around object\":\"控制是否應該在物件周圍繪製邊緣線\",\"Grayscale\":\"灰階\",\"Converts the rendering to grayscale with no color\":\"將彩現轉換為沒有顏色的灰階\",\"Brightness\":\"亮度\",\"Preserve Color\":\"保留顏色\",\"Maintains the hue by pulling the color back into gamut if its too high\":\"如果太高則將顏色拉回範圍以維持色調\",\"Levels\":\"等級\",\"Repeats\":\"重複\",\"Rotation\":\"旋轉\"}");

/***/ })

/******/ });
//# sourceMappingURL=NPR.js.map