/*!
 * LMV v7.47.0
 * 
 * Copyright 2021 Autodesk, Inc.
 * All rights reserved.
 * 
 * This computer source code and related instructions and comments are the
 * unpublished confidential and proprietary information of Autodesk, Inc.
 * and are protected under Federal copyright and state trade secret law.
 * They may not be disclosed to, copied or used by any third party without
 * the prior written consent of Autodesk, Inc.
 * 
 * Autodesk Forge Viewer Usage Limitations:
 * 
 * The Autodesk Forge viewer can only be used to view files generated by
 * Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be
 * delivered from an Autodesk hosted URL.
 */
Autodesk.Extensions.FusionSim =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./extensions/FusionSim/FusionSim.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./extensions/FusionSim/FusionSim.css":
/*!********************************************!*\
  !*** ./extensions/FusionSim/FusionSim.css ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../../node_modules/css-loader!../../node_modules/sass-loader/dist/cjs.js!./FusionSim.css */ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/FusionSim/FusionSim.css");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(false) {}

/***/ }),

/***/ "./extensions/FusionSim/FusionSim.js":
/*!*******************************************!*\
  !*** ./extensions/FusionSim/FusionSim.js ***!
  \*******************************************/
/*! exports provided: Simulation */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Simulation", function() { return Simulation; });
/* harmony import */ var _GalleryPanel__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./GalleryPanel */ "./extensions/FusionSim/GalleryPanel.js");
/* harmony import */ var _ModelStructurePanel__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./ModelStructurePanel */ "./extensions/FusionSim/ModelStructurePanel.js");
/* harmony import */ var _FusionSim_css__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./FusionSim.css */ "./extensions/FusionSim/FusionSim.css");
/* harmony import */ var _FusionSim_css__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(_FusionSim_css__WEBPACK_IMPORTED_MODULE_2__);


 // REQUIRED!!

'use strict';

var av = Autodesk.Viewing;

av.GEOMETRY_LOAD_START = 'geometryLoadStarted'; // Ehhh, what?

var Simulation = function () {

  var defaults = {};

  var loadSimulationExtension = false;

  function Simulation(viewer, options) {
    var that = this;
    options = options || {};
    // Check options, else override with defaults.
    for (var i in defaults) {
      options[i] = options[i] || defaults[i];
    }
    av.Extension.call(that, viewer, options);
    this.name = 'fusionsim';

    viewer.addEventListener(av.GEOMETRY_LOAD_START, function (event) {
      //if extension is already loadded
      //need to unload it first
      if (loadSimulationExtension)
      that.unload();
      var extension = event.data.extensions;
      if (extension === 'Autodesk.Fusion360.Simulation') {
        loadSimulationExtension = true;
      } else {
        that.unload();
        loadSimulationExtension = false;
      }
    });
    viewer.addEventListener(av.GEOMETRY_LOADED_EVENT, function (event) {
      //  if (loadSimulationExtension) {
      that.load();
      //   }
    });
  }

  Simulation.prototype = Object.create(av.Extension.prototype);
  var prototype = Simulation.prototype;
  prototype.constructor = Simulation;


  prototype.load = function () {

    var that = this;
    var viewer = that.viewer;
    if (!viewer.model) return true;
    that.galleryPanel = new _GalleryPanel__WEBPACK_IMPORTED_MODULE_0__["GalleryPanel"](that.viewer);
    that.viewer.addPanel(that.galleryPanel);
    that.simButton = new av.UI.Button('toolbar-simulation');
    that.simButton.setVisible(false);
    that.simButton.setToolTip('Simulation Results');
    that.simButton.onClick = function (e) {
      var visible = that.galleryPanel.isVisible();
      if (!visible) {
        that.activate(that.galleryPanel);
      } else {
        that.deactivate(that.galleryPanel);
      }
      that.simButton.setState(!visible ? av.UI.Button.State.ACTIVE : av.UI.Button.State.INACTIVE);
    };
    that.simButton.setIcon('toolbar-simulationIcon');
    viewer.settingsTools.addControl(that.simButton, {
      index: 1 });


    // Change these viewer settings for SIM files.
    // keep defaults
    that.hideLines = viewer.prefs.get("lineRendering");
    that.ghosting = viewer.prefs.get("ghosting");
    that.ambientShadow = viewer.prefs.get("ambientShadows");
    that.antialiazing = viewer.prefs.get("antialiasing");
    that.lightPreset = viewer.prefs.get("lightPreset");
    viewer.model.getObjectTree(function (instanceTree) {
      setTimeout(function () {
        that.galleryPanel.initModel(instanceTree, that);
        that.initModelBrowser();
      }, 100);
    });
    return true;
  };
  prototype.unload = function () {
    var that = this;
    if (!that.viewer.model) return;
    that.showResultsDlg(false);
    that.simButton.removeFromParent();
    that.viewer.removePanel(this.galleryPanel);
    that.galleryPanel.uninitialize();
    // restore viewer settings back.
    that.viewer.hideLines(!that.hideLines);
    that.viewer.setGhosting(that.ghosting);
    that.viewer.setQualityLevel(that.ambientShadow, that.antialiazing);
    that.viewer.setLightPreset(that.lightPreset);
    return true;
  };

  prototype.initModelBrowser = function () {
    var that = this;
    setTimeout(function () {
      that.options = that.options || {};
      that.options.addFooter = true;
      that.modelStructurePanel = new _ModelStructurePanel__WEBPACK_IMPORTED_MODULE_1__["SimModelStructurePanel"](that, 'Simulation Model Structure Loading', that.options);
      that.viewer.getExtension('Autodesk.ModelStructure').setModelStructurePanel(that.modelStructurePanel);
      that.modelStructurePanel.setGallery(that.galleryPanel);
    }, 100);
  };

  prototype.showResultsDlg = function (show) {
    var that = this;
    that.simButton.setState(show ? av.UI.Button.State.ACTIVE : av.UI.Button.State.INACTIVE);
    that.simButton.setVisible(show);
    that.galleryPanel.setVisible(show);
  };
  prototype.applySettings = function () {
    var viewer = this.viewer;
    viewer.hideLines(false);
    viewer.setGhosting(false);
    viewer.setQualityLevel(false, true);
    viewer.setLightPreset(4);
  };
  prototype.simData = function () {
    return this.galleryPanel.simDef;
  };

  prototype.activate = function (galleryPanel) {
    if (!this.activeStatus) {
      galleryPanel.setVisible(true);
      this.activeStatus = true;
    }
    return true;

  };

  prototype.deactivate = function (galleryPanel) {
    if (this.activeStatus) {
      galleryPanel.setVisible(false);
      this.activeStatus = false;
    }
    return true;
  };


  return Simulation;
}();

av.theExtensionManager.registerExtension('Autodesk.Fusion360.Simulation', Simulation);

/***/ }),

/***/ "./extensions/FusionSim/GalleryPanel.js":
/*!**********************************************!*\
  !*** ./extensions/FusionSim/GalleryPanel.js ***!
  \**********************************************/
/*! exports provided: GalleryPanel */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "GalleryPanel", function() { return GalleryPanel; });
/* harmony import */ var _SimulationDef__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./SimulationDef */ "./extensions/FusionSim/SimulationDef.js");


'use strict';

var av = Autodesk.Viewing;
var _ave = av.Extension;
var aves = av.Extensions;
var avu = av.UI;
var i18n = av.i18n;

var GalleryPanel = function () {
  // helper methods
  function styleBuilder(element, styleObject) {
    if (!element || !styleObject) return;
    var cssText = element.style.cssText.trim();
    var colon = ";";
    var isEndingWithColon = cssText.substring(cssText.length - 1) === ";";
    if (!isEndingWithColon) {
      cssText = cssText + ";";
    }
    var styleString = [];
    for (var style in styleObject) {
      styleString[styleString.length] = [style, styleObject[style]].join(':');
    }
    styleString = styleString.join(';');
    element.style.cssText = styleString;
  }

  function preparePanel() {
    var that = this,labelUndeformed,optUndeformed,resultGroup,legend,resultTypes,resultSteps,divColorScale,colorScale,colorScaleTopText,colorScaleBottomText, /*line1,*/line2,tbl,tblBody;
    avu.DockingPanel.prototype.initialize.call(that);
    var container = that.container;
    container.classList.add('property-panel', 'simulation-container', 'position-' + (that.position || "left") + '-corner');
    container.dockRight = true;

    var _document = that.getDocument();
    legend = that.legend = _document.createElement('div');
    var docfrag = _document.createDocumentFragment();

    //results div//////////
    var divResults = _document.createElement('div');
    divResults.classList.add('sim-div-Results');

    resultGroup = that.resultsGroup = _document.createElement("select");
    resultGroup.classList.add('simulation-resultGroup');
    divResults.appendChild(resultGroup);

    resultTypes = that.resultTypes = _document.createElement("select");
    resultTypes.classList.add('simulation-resultTypes');
    resultTypes.id = 'resultTypes';
    divResults.appendChild(resultTypes);

    resultSteps = that.resultSteps = document.createElement('select');
    resultSteps.classList.add('simulation-resultSteps');
    resultSteps.id = 'resultSteps';
    divResults.appendChild(resultSteps);

    docfrag.appendChild(divResults);
    ///////////////////////
    //sim options
    var divResultsOption = that.divResultsOption = _document.createElement('div');
    divResultsOption.classList.add('sim-div-options');
    optUndeformed = that.optUndeformed = _document.createElement("input");
    optUndeformed.classList.add('sim-undeformedOption');
    optUndeformed.setAttribute("type", "checkbox");
    optUndeformed.setAttribute("name", "optUndeformed");
    optUndeformed.setAttribute("id", "Undeformed");
    optUndeformed.addEventListener('change', function (e) {// When someone clicks on it
      var activeLoadCase = that.simDef.loadCases[that.simDef.activeLoadCaseKey];
      if (activeLoadCase === null) return;
      if (activeLoadCase.undeformedResults === -1)
      return;
      if (that.optUndeformed.checked) {
        //show undeformed state
        that.viewer.show(activeLoadCase.undeformedResults);
      } else
      {
        that.viewer.hide(activeLoadCase.undeformedResults);
      }
    });

    optUndeformed.checked = false;
    divResultsOption.appendChild(optUndeformed);
    //do this after you append it
    optUndeformed.checked = false;

    labelUndeformed = that.labelUndeformed = _document.createElement('label');
    labelUndeformed.classList.add('sim-undeformedOptionText');
    labelUndeformed.htmlFor = "Undeformed";
    labelUndeformed.setAttribute("data-i18n", "Show Undeformed Model");
    labelUndeformed.textContent = i18n.translate("Show Undeformed Model");
    divResultsOption.appendChild(labelUndeformed);
    docfrag.appendChild(divResultsOption);
    ///////////////////////

    //      line1 = that.line1 = document.createElement("hr");
    //      line1.classList.add('sim-line1');
    //      docfrag.appendChild(line1);

    //color scale div
    divColorScale = that.divColorScale = _document.createElement("div");
    divColorScale.classList.add('sim-div-colorscale');
    divColorScale.classList.add('sim-div-colorscale-top1');
    colorScale = that.colorScale = _document.createElement("div");
    colorScale.classList.add('simulation-colorscale');
    divColorScale.appendChild(colorScale);

    colorScaleTopText = that.colorScaleTopText = _document.createElement("div");
    colorScaleTopText.classList.add('sim-colorScaleTopText');
    colorScaleTopText.innerHTML = "- 3333";
    divColorScale.appendChild(colorScaleTopText);

    colorScaleBottomText = that.colorScaleBottomText = _document.createElement("div");
    colorScaleBottomText.classList.add('sim-colorScaleBottomText');
    colorScaleBottomText.innerHTML = "- 3333";
    divColorScale.appendChild(colorScaleBottomText);
    docfrag.appendChild(divColorScale);
    ////////////////////////////////////

    line2 = that.line2 = _document.createElement("hr");
    line2.classList.add('sim-line2');
    docfrag.appendChild(line2);

    var divTable = _document.createElement('div');
    divTable.classList.add('sim-div-Table');
    divTable.addEventListener('click', function (e) {// When someone clicks on it
      divTable.classList.add('sim-div-Table-Collapse');
      container.classList.add('simulation-container-Collapse');
      divColorScale.classList.add('sim-div-colorscale-Collapse');
    });

    divColorScale.addEventListener('click', function (e) {// When someone clicks on it
      divTable.classList.remove('sim-div-Table-Collapse');
      container.classList.remove('simulation-container-Collapse');
      divColorScale.classList.remove('sim-div-colorscale-Collapse');
    });

    tbl = that.tbl = _document.createElement("table");
    tblBody = that.tblBody = _document.createElement("tbody");
    tbl.appendChild(tblBody);
    tbl.classList.add('sim-table');
    divTable.appendChild(tbl);
    docfrag.appendChild(divTable);

    legend.appendChild(docfrag);

    container.appendChild(legend);
  }

  function getPropertyValue(properties, propertyName) {
    for (var i = 0; i < properties.length; ++i) {
      var property = properties[i];
      if (property.displayName === propertyName) {
        return property.displayValue;
      }
    }
    return null;
  }

  function toggleDisable(element, len) {
    var resultGroupDisable = false;
    var style = '""';
    if (len <= 1) {
      resultGroupDisable = true;
      style = "none";
    }
    element.disabled = resultGroupDisable;
    styleBuilder(element, {
      "-webkit-appearance": style,
      "-moz-appearance": style,
      appearance: style });

  }

  // GalleryPanel class
  function GalleryPanel(viewer, options) {
    var that = this;
    options = options || {};
    that.viewer = viewer;
    that.simDef = null;
    this.setGlobalManager(viewer.globalManager);
    avu.DockingPanel.call(that, viewer.container, 'Simulation-Panel', 'Simulation Results');
    // panel position configuration.
    that.position = options.position || "right";
  }

  GalleryPanel.prototype = Object.create(avu.DockingPanel.prototype);
  var prototype = GalleryPanel.prototype;
  prototype.constructor = GalleryPanel;

  prototype.initialize = function () {
    var that = this;
    preparePanel.call(that);
    that.resultsGroup.addEventListener('change', function (event) {
      var simDef = that.simDef;
      var activeLoadCase = simDef.loadCases[that.simDef.activeLoadCaseKey];
      that.viewer.hide(activeLoadCase.resultsNode);
      var caller = 'fillResultTypes';
      if (simDef.modalAnalysis) {
        caller = 'fillModalResultTypes';
      } else if (simDef.analysisType === simDef.SimulationStudies.NLSS) {
        caller = 'fillNLSSResultTypes';
      }
      that[caller](simDef.activeLoadCaseKey, that.resultsGroup.value);
      setTimeout(function () {
        that.setSimObjectsVisibility();
      }, 100);
    });
    that.resultTypes.addEventListener('change', function () {
      var activeLoadCase = that.simDef.loadCases[that.simDef.activeLoadCaseKey];
      that.viewer.hide(activeLoadCase.resultsNode);
      that.setSimObjectsVisibility();
    });
    that.resultSteps.addEventListener('change', function () {
      var activeLoadCase = that.simDef.loadCases[that.simDef.activeLoadCaseKey];
      that.viewer.hide(activeLoadCase.resultsNode);
      that.updateType();
      that.setSimObjectsVisibility();
    });
  };

  prototype.updateType = function () {
    var selectedStep = document.getElementById('resultSteps').selectedIndex;
    document.getElementById('resultTypes').selectedIndex = selectedStep;
  };

  prototype.setSimulationDef = function (simDef) {
    var that = this,studyNode,loadCase,studyName,tblBody,resultsGroup,viewer;
    that.simDef = simDef;
    studyNode = simDef.studyNode * 1;
    function onStudyPropertiesRetrieved(studyNode) {
      var name = getPropertyValue(studyNode.properties, "Name");
      that.setTitle(name);
    }

    //hide undeformed option if neccessary
    if (simDef.undeformedResults === -1) {
      that.optUndeformed.classList.add('sim-hide');
      that.labelUndeformed.classList.add('sim-hide');
      that.divColorScale.classList.remove('sim-div-colorscale-top1');
      that.divColorScale.classList.add('sim-div-colorscale-top2');
    } else {
      if (simDef.analysisType === simDef.SimulationStudies.NLSS) {
        that.resultSteps.classList.remove('sim-hide');
        that.divResultsOption.classList.add('sim-div-options-NLSS');
        that.divColorScale.classList.remove('sim-div-colorscale-top1');
        that.divColorScale.classList.add('sim-div-colorscale-top1-NLSS');
        that.colorScale.classList.add('simulation-colorscale-NLSS');
        that.colorScaleTopText.classList.add('sim-colorScaleTopText-NLSS');
        that.colorScaleBottomText.classList.add('sim-colorScaleBottomText-NLSS');
      } else {
        that.resultSteps.classList.add('sim-hide');
        that.divResultsOption.classList.remove('sim-div-options-NLSS');
        that.divColorScale.classList.add('sim-div-colorscale-top1');
        that.divColorScale.classList.remove('sim-div-colorscale-top1-NLSS');
        that.colorScale.classList.remove('simulation-colorscale-NLSS');
        that.colorScaleTopText.classList.remove('sim-colorScaleTopText-NLSS');
        that.colorScaleBottomText.classList.remove('sim-colorScaleBottomText-NLSS');
      }
    }

    function onError(status, message, data) {
    }

    that.viewer.getProperties(studyNode, onStudyPropertiesRetrieved, onError);
    //result groups
    studyName = i18n.translate(simDef.studyName());
    // info: Analysis type
    tblBody = that.tblBody;
    if (!that.rowType) {
      var rowsToInsert = [
      {
        name: 'rowType',
        content: [i18n.translate("Analysis Type"), studyName] },

      {
        name: 'rowNodes',
        content: [i18n.translate("Nodes"), '1872'] },

      {
        name: 'rowElements',
        content: [i18n.translate("Elements"), '1084'] },

      {
        name: 'rowMin',
        content: [i18n.translate("Min"), '0.000E+02 MPa'] },

      {
        name: 'rowMax',
        content: [i18n.translate("Max"), '5.117E+02 MPa'] }];


      rowsToInsert.forEach(function (row) {
        that[row.name] = tblBody.insertRow(-1);
        row.content.forEach(function (cellValue) {
          that[row.name].insertCell(-1).innerHTML = cellValue;
        });
      });
    } else {
      that.rowType.cells[1].innerHTML = studyName;
    }

    viewer = that.viewer;

    viewer.model.getObjectTree(function (instanceTree) {
      that.instanceTree = instanceTree;
      var calleeResultTypes, calleeResultsGroup;
      if (simDef.analysisType === simDef.SimulationStudies.MODAL || simDef.analysisType === simDef.SimulationStudies.BUCKLING) {
        calleeResultsGroup = "fillResultsGroup";
        calleeResultTypes = "fillModalResultTypes";
      } else if (simDef.analysisType === simDef.SimulationStudies.NLSS) {
        calleeResultsGroup = "fillNLSSResultsGroup";
        calleeResultTypes = "fillNLSSResultTypes";
      } else {
        calleeResultsGroup = "fillResultsGroup";
        calleeResultTypes = "fillResultTypes";
      }
      that[calleeResultsGroup](that.simDef.activeLoadCaseKey);
      that[calleeResultTypes](that.simDef.activeLoadCaseKey, that.resultsGroup.value);
      setTimeout(function () {
        simDef.simExt.showResultsDlg(true);
        simDef.simExt.applySettings();
        that.setSimObjectsVisibility();
      }, 500);
    });

    //elements & nodes
    var activeLoadCase = that.simDef.loadCases[that.simDef.activeLoadCaseKey];
    var resultsNode = +activeLoadCase.resultsNode;

    function onResultsPropertiesRetrieved(resultsNode) {
      var elements = getPropertyValue(resultsNode.properties, "Elements");
      var nodes = getPropertyValue(resultsNode.properties, "Nodes");
      that.rowElements.cells[1].innerText = elements;
      that.rowNodes.cells[1].innerText = nodes;
    }

    viewer.getProperties(resultsNode, onResultsPropertiesRetrieved, onError);

    if (simDef.analysisType === simDef.SimulationStudies.NLSS) that.updateType();
  };

  prototype.processNodes = function (instanceTree, onProcessed) {
    var that = this;
    var nodeIdsToProcess = [];
    var simDef = that.simDef;
    var viewer = that.viewer;
    var loadCase = null;
    if (!simDef) {
      simDef = new _SimulationDef__WEBPACK_IMPORTED_MODULE_0__["SimulationDef"]();
    } else {
      simDef.reset();
    }
    instanceTree.enumNodeChildren(instanceTree.getRootId(), function (dbId) {
      nodeIdsToProcess[nodeIdsToProcess.length] = dbId;
    }, true);
    function processNodeId(node, onNodeProcessed) {
      function onPropertiesRetrieved(result) {
        //force to hide until all init. that.viewer.hide(node);
        var properties = result.properties;
        var name = getPropertyValue(result.properties, 'A1C6011B-E1A6-4ADF-975D-A0003C592F87');
        if (name) {
          var bSimNode = true;
          switch (name) {
            case "SIM_STUDY":
              simDef.studyNode = node;
              var type = getPropertyValue(result.properties, "Study Type");
              simDef.analysisType = type;
              break;
            case "SIM_POINT_MASSES":
              simDef.pointMasssesNode = node;
              break;
            case "SIM_POINT_MASS":
              simDef.pointMassNodes.push(node);
              break;
            case "SIM_CONNECTORS":
              simDef.connectorsNode = node;
              break;
            case "SIM_CONNECTOR":
              //case "SIM_BOLT_CONNECTOR":
              //case "SIM_SPRING_CONNECTOR":
              simDef.connectorNodes.push(node);
              break;
            case "SIM_LOAD_CASE":
              loadCase = simDef.addLoadCase(getPropertyValue(result.properties, 'Name'), node, node);
              break;
            case "SIM_CONSTRAINTS":
              if (loadCase == null) {
                loadCase = simDef.addLoadCase(i18n.translate("Load Case:1"), 0, 0);
              }
              loadCase.constraintsNode = node;
              break;
            case "SIM_CONSTRAINT":
              loadCase.constraintNodes.push(node);
              break;
            case "SIM_LOADS":
              if (loadCase == null) {
                loadCase = simDef.addLoadCase(i18n.translate("Load Case:1"), 0, 0);
              }
              loadCase.loadsNode = node;
              break;
            case "SIM_LOAD":
              loadCase.loadNodes.push(node);
              break;
            case "SIM_RESULTS_SCALAR_PLOT":
              if (loadCase == null) {
                loadCase = simDef.addLoadCase(i18n.translate("Load Case:1"), 0, 0);
              }
              if (simDef.analysisType === simDef.SimulationStudies.LSS || simDef.analysisType === simDef.SimulationStudies.NLSS || simDef.analysisType === simDef.SimulationStudies.THERMAL ||
              simDef.analysisType === simDef.SimulationStudies.THERMALSTRESS || simDef.analysisType === simDef.SimulationStudies.SHAPEGENERATOR) {
                loadCase.associateResult(getPropertyValue(properties, "Name"), node);
              } else {//Buckling, Modal
                loadCase.associateModalResult(getPropertyValue(properties, "Name"), node);
              }
              break;
            case "SIM_RESULTS_GROUP":
              if (loadCase == null) {
                loadCase = simDef.addLoadCase(i18n.translate("Load Case:1"), 0, 0);
              }
              if (simDef.analysisType === simDef.SimulationStudies.LSS || simDef.analysisType === simDef.SimulationStudies.NLSS || simDef.analysisType === simDef.SimulationStudies.THERMAL ||
              simDef.analysisType === simDef.SimulationStudies.THERMALSTRESS || simDef.analysisType === simDef.SimulationStudies.SHAPEGENERATOR) {
                loadCase.associateResultGroup(getPropertyValue(properties, "Name"), node);
              }
              break;
            case "SIM_RESULTS":
              if (loadCase == null) {
                loadCase = simDef.addLoadCase(i18n.translate("Load Case:1"), 0, 0);
              }
              loadCase.resultsNode = node;
              //viewer.hide(node);
              break;
            case "SIM_RESULTS_UNDEFORMED_FEATURE_EDGES_PLOT":
              if (loadCase == null) {
                loadCase = simDef.addLoadCase(i18n.translate("Load Case:1"), 0, 0);
              }
              loadCase.undeformedResults = node;
              //viewer.hide(node);
              break;
            case "SIM_RESULTS_SCALAR_PLOT_BODY":
            case "SIM_RESULTS_SAMPLE":
              // Nothing for now!
              break;}

          if (bSimNode === true) {
            simDef.simNodes.push(node);
          }
        } else
        {
          simDef.modelNodes.push(node);
        }
        onNodeProcessed();
      }

      function onError(status, message, data) {
        onNodeProcessed();
      }

      if (node && viewer) {
        viewer.getProperties(node, onPropertiesRetrieved, onError);
      }
    }

    // Process the nodes one by one.
    function processNext() {
      if (nodeIdsToProcess.length > 0) {
        processNodeId(nodeIdsToProcess.shift(), processNext);
      } else {
        // No more nodes to process - call the provided callback.
        onProcessed(simDef);
      }
    }

    processNext();
  };

  prototype.initModel = function (instanceTree, simExt) {
    var that = this;
    var viewer = that.viewer;
    if (!viewer) return;
    that.processNodes(instanceTree, function (simDef) {
      simDef.simExt = simExt;
      that.setSimulationDef(simDef);
    });
    that.addEventListener(that.viewer, av.SELECTION_CHANGED_EVENT, function (e) {
      var nodes = e.nodeArray;
      if (nodes) {
        that.handleClick(nodes[0]);

        //     for (var k = 0; k < nodes.length; k++)
        //     {
        //         if(that.isModelNode(nodes[k]))
        //         {
        //           that.viewer.hide(that.simDef.resultsNode);
        //           break;
        //         }
        //      }
      }
    });
  };

  prototype.fillResultsGroup = function (loadCaseKey) {

    if (!loadCaseKey)
    return;

    var that = this;
    var simDef = that.simDef;
    var loadCase = simDef.loadCases[loadCaseKey];
    var resultsGroup = that.resultsGroup;

    var _document = that.getDocument();
    resultsGroup.options.length = 0;
    var groupKeys = Object.keys(simDef.analysisType === simDef.SimulationStudies.MODAL || simDef.analysisType === simDef.SimulationStudies.BUCKLING ? loadCase.modalResults : loadCase.resultGroups);
    for (var i = 0; i < groupKeys.length; i++) {
      var item = _document.createElement("option");
      item.value = groupKeys[i];
      var name = simDef.analysisType === simDef.SimulationStudies.MODAL || simDef.analysisType === simDef.SimulationStudies.BUCKLING ? groupKeys[i] : loadCase.resultGroups[groupKeys[i]];
      item.setAttribute("data-i18n", name);
      item.textContent = i18n.translate(name);
      resultsGroup.add(item);
    }

    toggleDisable(resultsGroup, resultsGroup.options.length, false);
  };

  prototype.fillNLSSResultsGroup = function (loadCaseKey) {
    var that = this;
    var simDef = that.simDef;
    var loadCase = simDef.loadCases[loadCaseKey];
    var resultsGroup = that.resultsGroup;

    var _document = that.getDocument();
    resultsGroup.options.length = 0;
    var groupKeys = Object.keys(loadCase.resultGroups);
    var groupBuffer;
    groupBuffer = [];
    for (var i = 0; i < groupKeys.length; i++) {
      var name = loadCase.resultGroups[groupKeys[i]];
      if (groupBuffer.includes(name)) continue;
      groupBuffer.push(name);

      var item = _document.createElement("option");
      item.value = name;
      item.setAttribute("data-i18n", name);
      item.textContent = i18n.translate(name);
      resultsGroup.add(item);
    }

    toggleDisable(resultsGroup, resultsGroup.options.length, false);
  };

  prototype.fillResultTypes = function (loadCaseKey, resultGroupKey) {
    var that = this;
    var viewer = that.viewer;
    var resultTypes = that.resultTypes;
    var resultsGroup = that.resultsGroup;
    var loadCase = that.simDef.loadCases[loadCaseKey];

    resultTypes.options.length = 0;
    var node = +resultGroupKey;

    function onError(status, message, data) {
      // onNodeProcessed();
    }

    function onGroupPropertiesRetrieved(groupResult) {
      var key = "Result group";
      var resultGroup = getPropertyValue(groupResult.properties, key);

      var _document = that.getDocument();
      function onResultPropertiesRetrieved(resultType) {
        var resultTypeGroup = getPropertyValue(resultType.properties, key);
        if (resultTypeGroup === resultGroup) {
          var item = _document.createElement("option");
          item.value = resultType.dbId;
          var name = loadCase.resultTypes[resultType.dbId];
          item.setAttribute("data-i18n", name);
          item.textContent = i18n.translate(name);
          resultTypes.add(item);
          toggleDisable(resultTypes, resultTypes.options.length, resultsGroup.options.length === 0);
        }
      }

      //result types
      var keys = Object.keys(loadCase.resultTypes);
      for (var i = 0; i < keys.length; i++) {
        var resultNode = +keys[i];
        viewer.getProperties(resultNode, onResultPropertiesRetrieved, onError);
      }
    }

    viewer.getProperties(node, onGroupPropertiesRetrieved, onError);
  };

  prototype.fillModalResultTypes = function (loadCaseKey, resultGroupKey) {
    var that = this;
    var resultTypes = that.resultTypes;
    var resultsGroup = that.resultsGroup;
    var loadCase = that.simDef.loadCases[loadCaseKey];

    resultTypes.options.length = 0;
    var resultGroup = resultGroupKey;

    var _document = that.getDocument();
    function onResultPropertiesRetrieved(resultType) {
      var resultTypeGroup = getPropertyValue(resultType.properties, "Result type");
      if (resultTypeGroup === resultGroup) {
        var item = _document.createElement("option");
        item.value = resultType.dbId;
        var resultMode = getPropertyValue(resultType.properties, "Mode");
        var name = resultMode;
        item.setAttribute("data-i18n", name);
        item.textContent = name; //Autodesk.Viewing.i18n.translate(name); //Mode 1: 200 Hz -> result from translate 200 Hz -> not acceptable
        that.resultTypes.add(item);
        //that.simDef.associateResult(name, resultType.dbId);
        toggleDisable(resultTypes, resultTypes.options.length, resultsGroup.options.length === 0);
      }
    }

    function onError(status, message, data) {
      // onNodeProcessed();
    }

    //result types
    var keys = loadCase.modalResults[resultGroup] || [];
    for (var i = 0; i < keys.length; i++) {
      var resultNode = +keys[i];
      that.viewer.getProperties(resultNode, onResultPropertiesRetrieved, onError);
    }

  };



  prototype.fillNLSSResultTypes = function (loadCaseKey, resultGroupKey) {
    var that = this;
    var viewer = that.viewer;
    var uiResultTypes = that.resultTypes;
    var uiResultsSteps = that.resultSteps;
    var loadCase = that.simDef.loadCases[loadCaseKey];
    var _document = that.getDocument();

    var node = +resultGroupKey;

    function onError(status, message, data) {
      // onNodeProcessed();
    }

    function onGroupPropertiesRetrieved(groupResult) {
      function onResultPropertiesRetrieved(resultType) {
        var itemType = _document.createElement("option");
        itemType.value = resultType.dbId;
        var itemTypeName = getPropertyValue(resultType.properties, "Result type");
        itemType.setAttribute('data-i18n', itemTypeName);
        itemType.textContent = i18n.translate(itemTypeName);
        uiResultTypes.add(itemType);
        toggleDisable(uiResultTypes, 0);

        var itemStep = _document.createElement("option");
        itemStep.value = resultType.dbId;

        // we do not want to display original display name in "Step X: X" format
        // since for the NLSS, step values and units are irrelevant.
        // Instead, we will parse its name to "Step X" format
        var itemStepName = getPropertyValue(resultType.properties, "Mode");
        var indexDelimiter = itemStepName.indexOf(':');
        if (indexDelimiter != -1) itemStepName = itemStepName.substr(0, indexDelimiter);

        itemStep.setAttribute('data-i18n', itemStepName);
        itemStep.textContent = i18n.translate(itemStepName);
        uiResultsSteps.add(itemStep);
      }

      // first, remove all old entries
      _document.getElementById("resultTypes").options.length = 0;
      _document.getElementById("resultSteps").options.length = 0;

      var keysGroup = Object.keys(loadCase.resultGroups).map(function (e) {return loadCase.resultGroups[e];});
      var keysTypes = Object.keys(loadCase.resultTypes);
      for (var i = 0; i < keysGroup.length; i++) {
        if (resultGroupKey === keysGroup[i]) {
          var resultNode = +keysTypes[i];
          viewer.getProperties(resultNode, onResultPropertiesRetrieved, onError);
        }
      }
    }

    viewer.getProperties(node, onGroupPropertiesRetrieved, onError);
  };

  prototype.uninitialize = function () {
    avu.DockingPanel.prototype.uninitialize.call(this);
    this.viewer = null;
  };

  prototype.setTitle = function (title, options) {
    if (!title) {
      title = 'Simulations';
      options = options || {};
      options.localizeTitle = true;
    }
    avu.DockingPanel.prototype.setTitle.call(this, title, options);
  };

  prototype.setModelNodesVisible = function (bVisible) {
    var that = this;
    var viewer = that.viewer;
    if (!that.simDef) return;
    var modelNodes = that.simDef.modelNodes;
    if (modelNodes && modelNodes.length > 0) {
      for (var k = 0; k < modelNodes.length; k++) {
        viewer[bVisible ? "show" : "hide"](modelNodes[k]);
      }
    }
  };

  //    prototype.isModelNode = function (node) {
  //      var that = this;
  //      if(!that.simDef) return;
  //      var modelNodes = that.simDef.modelNodes;
  //      if (!modelNodes || modelNodes.length === 0) {
  //        return;
  //      }
  //      return modelNodes.indexOf(node) !== -1;
  //    };

  prototype.setNodeVisibility = function (node, visible) {
    this.viewer[visible ? "show" : "hide"](node);
  };

  prototype.isSimStudyNode = function (node) {
    if (!this.simDef.studyNode) return false;
    return this.simDef.studyNode === node;
  };

  prototype.handleClick = function (nodeId) {
    var that = this;
    if (that.simDef === null) return false;
    var activeLoadCase = that.simDef.loadCases[that.simDef.activeLoadCaseKey];
    if (activeLoadCase === null) return false;
    //if(!activeLoadCase.isImportant(node)) return false;
    var groupKeys = Object.keys(that.simDef.loadCases);
    for (var i = 0; i < groupKeys.length; i++) {
      var loadCase = that.simDef.loadCases[groupKeys[i]];
      if (loadCase.isImportant(nodeId) && activeLoadCase !== loadCase) {
        //hide old load case items
        if (activeLoadCase.loadsNode !== -1) that.viewer.hide(activeLoadCase.loadsNode);
        if (activeLoadCase.constraintsNode !== -1) that.viewer.hide(activeLoadCase.constraintsNode);
        if (activeLoadCase.undeformedResults !== -1) that.viewer.hide(activeLoadCase.undeformedResults);
        if (activeLoadCase.resultsNode !== -1) that.viewer.hide(activeLoadCase.resultsNode);
        if (that.simDef.connectorsNode !== -1) that.viewer.hide(that.simDef.connectorsNode);
        //set new active load case
        that.simDef.activeLoadCaseKey = groupKeys[i];
        //fill results group cbo with new items
        that.fillResultsGroup(that.simDef.activeLoadCaseKey);
        var callee;
        if (that.simDef.analysisType === that.simDef.SimulationStudies.MODAL || that.simDef.analysisType === that.simDef.SimulationStudies.BUCKLING) {
          callee = 'fillModalResultTypes';
        } else if (that.simDef.analysisType === that.simDef.SimulationStudies.NLSS) {
          callee = 'fillNLSSResultTypes';
        } else {
          callee = 'fillResultTypes';
        }

        //fill results type cbo with new items
        that[callee](that.simDef.activeLoadCaseKey, that.resultsGroup.value);
        //sets the visibility of new items
        setTimeout(function () {
          that.simDef.simExt.showResultsDlg(true);
          that.setSimObjectsVisibility();
        }, 500);
        return true;
      }
    }

    return false;
  };

  prototype.setSimObjectsVisibility = function (node) {
    var that = this;
    //if no results and no active load then show model and hide results panel
    var activeLoadCase = that.simDef.loadCases[that.simDef.activeLoadCaseKey];
    if (!that.resultTypes || that.resultTypes.options.length === 0 || activeLoadCase === null) {
      that.setModelNodesVisible(true);
      that.simDef.simExt.showResultsDlg(false);
      return;
    }

    var resultNode = +that.resultTypes.value;
    //hide models
    that.setModelNodesVisible(false);
    //show result
    if (resultNode !== -1) that.viewer.show(resultNode);
    //show loads of active load case
    if (activeLoadCase.loadsNode !== -1) that.viewer.show(activeLoadCase.loadsNode);
    //show constraints of active load case
    if (activeLoadCase.constraintsNode !== -1) that.viewer.show(activeLoadCase.constraintsNode);
    //show undeformed style if
    if (that.optUndeformed.checked && activeLoadCase.undeformedResults !== -1)
    that.viewer.show(activeLoadCase.undeformedResults);
    //show connectors
    if (that.simDef.connectorsNode !== -1) that.viewer.show(that.simDef.connectorsNode);

    //this.viewer.fitToView();
    function onResultPropertiesRetrieved(resultType) {
      var minValue = getPropertyValue(resultType.properties, "Minimal value");
      var maxValue = getPropertyValue(resultType.properties, "Maximal value");
      var reversed = getPropertyValue(resultType.properties, "Scale reversed");
      var unit = getPropertyValue(resultType.properties, "Unit");
      that.rowMin.cells[1].innerText = minValue + " " + unit;
      that.rowMax.cells[1].innerText = maxValue + " " + unit;

      var minRefValue = getPropertyValue(resultType.properties, "Lower referential value");
      var maxRefValue = getPropertyValue(resultType.properties, "Upper referential value");
      if (reversed === "True") {
        //var temp = maxRefValue;
        //maxRefValue = minRefValue;
        //minRefValue = temp;
        that.colorScale.style.transform = "rotate(90deg)";
        that.colorScale.style.moztransform = "rotate(90deg)";
        that.colorScale.style.webkittransform = "rotate(90deg)";
      } else
      {
        that.colorScale.style.transform = "rotate(-90deg)";
        that.colorScale.style.moztransform = "rotate(-90deg)";
        that.colorScale.style.webkittransform = "rotate(-90deg)";
      }
      that.colorScaleTopText.innerHTML = "- " + maxRefValue + " " + unit;
      that.colorScaleBottomText.innerHTML = "- " + minRefValue + " " + unit;
    }

    function onError(status, message, data) {
      // onNodeProcessed();
    }

    that.viewer.getProperties(resultNode, onResultPropertiesRetrieved, onError);
  };

  return GalleryPanel;
}();

/***/ }),

/***/ "./extensions/FusionSim/ModelStructurePanel.js":
/*!*****************************************************!*\
  !*** ./extensions/FusionSim/ModelStructurePanel.js ***!
  \*****************************************************/
/*! exports provided: SimModelStructurePanel */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "SimModelStructurePanel", function() { return SimModelStructurePanel; });


function SimModelStructurePanel(ext, title, options) {
  Autodesk.Viewing.Extensions.ViewerModelStructurePanel.call(this, ext.viewer, title, options);
  this.viewer = ext.viewer;
  this.ext = ext;
};

SimModelStructurePanel.prototype = Object.create(Autodesk.Viewing.Extensions.ViewerModelStructurePanel.prototype);
SimModelStructurePanel.prototype.constructor = SimModelStructurePanel;

SimModelStructurePanel.prototype.setGallery = function (gallery) {
  this.simGalleryPanel = gallery;
};

SimModelStructurePanel.prototype.initialize = function () {
  Autodesk.Viewing.Extensions.ViewerModelStructurePanel.prototype.initialize.call(this);
};

SimModelStructurePanel.prototype.isSimResultsNode = function (node) {
  if (!this.simGalleryPanel || !this.simGalleryPanel.simDef || !this.simGalleryPanel.simDef.resultsNode) return false;
  return this.simGalleryPanel.simDef.resultsNode == node;
};

SimModelStructurePanel.prototype.isSimStudyNode = function (node) {
  if (!this.simGalleryPanel || !this.simGalleryPanel.simDef || !this.simGalleryPanel.simDef.studyNode) return false;
  return this.simGalleryPanel.simDef.studyNode == node;
};

SimModelStructurePanel.prototype.isModelNode = function (node) {
  if (!this.simGalleryPanel || !this.simGalleryPanel.simDef || !this.simGalleryPanel.simDef.modelNodes || this.simGalleryPanel.simDef.modelNodes.length == 0)
  return false;

  return this.simGalleryPanel.simDef.modelNodes.indexOf(node) !== -1;
};

SimModelStructurePanel.prototype.shouldInclude = function (node) {
  var that = this;
  if (!that.simGalleryPanel || !that.simGalleryPanel.simDef) return false;
  if (that.isModelNode(node)) return true;
  if (that.isSimStudyNode(node)) return true;

  var simDef = that.simGalleryPanel.simDef;
  var groupKeys = Object.keys(simDef.loadCases);
  for (var i = 0; i < groupKeys.length; i++) {
    var loadCase = simDef.loadCases[groupKeys[i]];
    if (loadCase.resultsNode === node) return false;
  }

  return true;
};

SimModelStructurePanel.prototype.onClick = function (node, event) {
  Autodesk.Viewing.Extensions.ViewerModelStructurePanel.prototype.onClick.call(this, node, event);

  this.simGalleryPanel.handleClick(node);
};

SimModelStructurePanel.prototype.expandStudyNode = function () {
  if (!this.simGalleryPanel.simDef.studyNode) return;
  this.tree.setCollapsed(this.simGalleryPanel.simDef.studyNode, false);
};

/***/ }),

/***/ "./extensions/FusionSim/SimulationDef.js":
/*!***********************************************!*\
  !*** ./extensions/FusionSim/SimulationDef.js ***!
  \***********************************************/
/*! exports provided: SimulationDef */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "SimulationDef", function() { return SimulationDef; });
/* harmony import */ var _SimulationLoadCaseDef__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./SimulationLoadCaseDef */ "./extensions/FusionSim/SimulationLoadCaseDef.js");


'use strict';

var SimulationDef = function () {
  function SimulationDef() {
    var that = this;
    that.SimulationStudies = { LSS: "SimCaseLSS",
      NLSS: "SimCaseNLSS",
      MODAL: "SimCaseModalFrequencies",
      BUCKLING: "SimCaseStructuralBuckling",
      THERMAL: "SimCaseThermalSteady",
      THERMALSTRESS: "SimCaseThermalStress",
      SHAPEGENERATOR: "SimCaseTopOpt",
      NAMES: {
        UNKNOWN: "Unknown",
        LSS: "Static Stress",
        NLSS: "Nonlinear Static Stress",
        MODAL: "Modal Frequencies",
        BUCKLING: "Structural Buckling",
        THERMAL: "Thermal",
        THERMALSTRESS: "Thermal Stress",
        SHAPEGENERATOR: "Shape Optimization" } };

    that.studyNode;
    that.loadCases = {};
    that.pointMasssesNode = -1;
    that.pointMassNodes = [];
    that.connectorsNode = -1;
    that.connectorNodes = [];
    that.activeLoadCaseKey = null;
    that.modelNodes = [];
    that.analysisType = that.SimulationStudies.LSS;
    that.modelStructurePanel = null;
    that.simExt = null;
    that.simNodes = [];
  }

  SimulationDef.prototype = {
    constructor: SimulationDef };

  var prototype = SimulationDef.prototype;
  prototype.studyName = function () {
    var name = this.SimulationStudies.NAMES.UNKNOWN;
    if (this.analysisType === this.SimulationStudies.LSS)
    name = this.SimulationStudies.NAMES.LSS;else
    if (this.analysisType === this.SimulationStudies.NLSS)
    name = this.SimulationStudies.NAMES.NLSS;else
    if (this.analysisType === this.SimulationStudies.MODAL)
    name = this.SimulationStudies.NAMES.MODAL;else
    if (this.analysisType === this.SimulationStudies.BUCKLING)
    name = this.SimulationStudies.NAMES.BUCKLING;else
    if (this.analysisType === this.SimulationStudies.THERMAL)
    name = this.SimulationStudies.NAMES.THERMAL;else
    if (this.analysisType === this.SimulationStudies.THERMALSTRESS)
    name = this.SimulationStudies.NAMES.THERMALSTRESS;else
    if (this.analysisType === this.SimulationStudies.SHAPEGENERATOR)
    name = this.SimulationStudies.NAMES.SHAPEGENERATOR;
    return name;
  };

  prototype.reset = function () {
    var that = this;
    that.studyNode = -1;
    that.modelNodes = [];
    that.analysisType = that.SimulationStudies.LSS;
    that.loadCases = {};
    that.pointMasssesNode = -1;
    that.pointMassNodes = [];
    that.connectorsNode = -1;
    that.connectorNodes = [];
    that.activeLoadCaseKey = null;
    that.simNodes = [];
    that.modelStructurePanel = null;
  };
  prototype.addLoadCase = function (loadCaseName, loadCaseID, loadCaseNode) {
    var that = this;
    var loadCaseDef = new _SimulationLoadCaseDef__WEBPACK_IMPORTED_MODULE_0__["SimulationLoadCaseDef"]();
    loadCaseDef.loadCase = loadCaseNode;
    loadCaseDef.loadCaseName = loadCaseName;
    //if initialization so set active the first one
    that.loadCases["SIM_LOAD_CASE" + loadCaseID] = loadCaseDef;
    if (Object.keys(that.loadCases).length === 1)
    that.activeLoadCaseKey = "SIM_LOAD_CASE" + loadCaseID;

    return loadCaseDef;
  };

  prototype.shouldDisplayInTree = function (node) {
    var that = this;
    var nodeId = node.dbId;
    if (that.simNodes.indexOf(nodeId) < 0) return false;
    if (that.studyNode === nodeId) return true;
    if (that.activeLoadCaseKey === null) return false;

    if (that.pointMasssesNode === nodeId) return true;
    if (that.pointMassNodes.indexOf(nodeId) !== -1) return true;

    if (that.connectorNodes.indexOf(nodeId) !== -1) return true;
    if (that.connectorsNode === nodeId) return true;

    var groupKeys = Object.keys(that.loadCases);
    for (var i = 0; i < groupKeys.length; i++) {
      var loadCase = that.loadCases[groupKeys[i]];
      if (loadCase.isImportant(nodeId))
      return loadCase.shouldDisplayInTree(nodeId);
    }

    //var activeLoadCase = that.loadCases[that.activeLoadCaseKey];
    //if(activeLoadCase === null) return false;
    //var visible = activeLoadCase.isImportant(node);

    return false;
  };

  return SimulationDef;
}();

/***/ }),

/***/ "./extensions/FusionSim/SimulationLoadCaseDef.js":
/*!*******************************************************!*\
  !*** ./extensions/FusionSim/SimulationLoadCaseDef.js ***!
  \*******************************************************/
/*! exports provided: SimulationLoadCaseDef */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "SimulationLoadCaseDef", function() { return SimulationLoadCaseDef; });
var SimulationLoadCaseDef = function () {
  function SimulationLoadCaseDef() {
    var that = this;

    that.loadCase = -1;
    that.loadCaseName = "";
    that.constraintsNode = -1;
    that.constraintNodes = [];
    that.loadsNode = -1;
    that.loadNodes = [];
    that.resultsNode = -1;
    that.undeformedResults = -1;
    that.resultTypes = {};
    that.resultGroups = {};
    that.modalResults = {};
  }

  SimulationLoadCaseDef.prototype = {
    constructor: SimulationLoadCaseDef };


  var prototype = SimulationLoadCaseDef.prototype;
  prototype.associateResult = function (resultName, resultNode) {
    this.resultTypes[resultNode] = resultName;
  };

  prototype.associateResultGroup = function (resultGroupName, resultGroupNode) {
    this.resultGroups[resultGroupNode] = resultGroupName;
  };

  prototype.associateModalResult = function (resultName, resultNode) {
    var subResultNode = [];
    subResultNode = this.modalResults[resultName];
    if (!subResultNode) {
      var subNode = [];
      subNode.push(resultNode);
      subResultNode = subNode;
    } else {
      subResultNode.push(resultNode);
    }
    this.modalResults[resultName] = subResultNode;
  };

  prototype.isImportant = function (nodeId) {
    var that = this;
    if (that.loadCase === nodeId) return true;
    if (that.loadNodes.indexOf(nodeId) !== -1) return true;
    if (that.constraintNodes.indexOf(nodeId) !== -1) return true;

    //do not show///
    if (that.resultsNode === nodeId) return true;
    ////////////
    if (that.constraintsNode === nodeId) return true;
    if (that.loadsNode === nodeId) return true;

    return false;
  };

  prototype.shouldDisplayInTree = function (nodeId) {
    var that = this;
    if (that.loadCase === nodeId) return true;
    if (that.loadNodes.indexOf(nodeId) !== -1) return true;
    if (that.constraintNodes.indexOf(nodeId) !== -1) return true;

    //do not show///
    if (that.resultsNode === nodeId) return false;
    ////////////
    if (that.constraintsNode === nodeId) return true;
    if (that.loadsNode === nodeId) return true;

    return false;
  };

  prototype.reset = function () {
    var that = this;
    that.loadCase = -1;
    that.loadCaseName = '';
    that.constraintsNode = -1;
    that.constraintNodes = [];
    that.loadsNode = -1;
    that.loadNodes = [];
    that.resultsNode = -1;
    that.undeformedResults = -1;
    that.resultTypes = {};
    that.resultGroups = {};
    that.modalResults = {};
  };
  return SimulationLoadCaseDef;
}();

/***/ }),

/***/ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/FusionSim/FusionSim.css":
/*!*************************************************************************************************************!*\
  !*** ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./extensions/FusionSim/FusionSim.css ***!
  \*************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../../node_modules/css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, ".toolbar-simulationIcon {\n  background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAZCAYAAAArK+5dAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAINJREFUeNpiYKAxYIQxLl299p9ahuppazFiCFLLAnRzmGgdRDS3gIUWwTRwPsAW+5T6ioWayRGbY0i1oBGI60nxHbFxcAGIDYEubqA4iJBdhTVH0iiIDID4PNCARlITAKnJtH7IpyIGWgfRaEajQ0ajeRDhyL1kZzRSK5x6hhEHAAIMAPgbTyRsh4JhAAAAAElFTkSuQmCC\"); }\n\n.toolbar-simulationSetupIcon {\n  background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAOxJREFUeNpi/P//P8NAAiaGAQajDsDnAFISx38S1Y9GwchwwDuktJGGO/UACyIcGBtAV/MAi5oHSPpd8JgPxoRCgBENo4MCIsUYyA0BBiLwASTfH8ARgkq49FPDAQpIFimg6ScYBSxUSGwPgHgiEhsG3kMx/jjGUxv+xxHv2IAAlP5Aquup5YDRgmjUAQPuAFAuuADFAvQuCQWA+AJSYXQBKkaMXoodYADEH7BUSB+gchQ7AF9tiMtykhzBSGa/gFRNjNROhIJA/BGIFYlkUz0XBEBT/AMi2WTlAmKqYVLYVE0DoyXh8HEAQIABAH7a/BD95CkUAAAAAElFTkSuQmCC\"); }\n\n.simulation-colorscale {\n  background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAABCAYAAABADtw1AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAADdJREFUWIXt1LENACAMxEBn/6HDCFAg5QUurnflgm4AStJ/GtB9BDRIOwELkg4Q0PCc6f1ImgEs9yMAHrvm2CUAAAAASUVORK5CYII=\");\n  background-size: contain;\n  -moz-transform: rotate(90deg);\n  -webkit-transform: rotate(90deg); }\n\n.simulation-container {\n  min-height: 35px !important;\n  height: 510px !important;\n  position: absolute !important;\n  background-color: rgba(34, 34, 34, 0.9) !important; }\n\n.simulation-container-Collapse {\n  height: 356px !important; }\n\n.position-left-corner {\n  top: 150px;\n  left: 220px; }\n\n.position-right-corner {\n  right: 100px;\n  top: 170px; }\n\n.simulation-resultGroup, .simulation-resultTypes, .simulation-resultSteps {\n  position: relative !important;\n  width: 100% !important;\n  color: black !important;\n  height: 22px !important;\n  border: 1px !important;\n  -webkit-box-sizing: border-box !important;\n  -moz-box-sizing: border-box !important;\n  box-sizing: border-box !important; }\n\n.sim-div-Results {\n  position: absolute !important;\n  top: 51px !important;\n  left: 5px !important;\n  right: 5px !important; }\n\n.simulation-resultTypes, .simulation-resultSteps {\n  margin-top: 5px !important; }\n\n.toolbar-simulationIcon {\n  background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAVJJREFUeNrslzFOwzAUhh3ETo7AxJoeIQOXYMtAl06dGFAHD52YcgS69wgM5QSElSlHSE9gnqXf0lMi288GlErE0qfW7znPv1/+SElhjFFzjis181gE/ERAQ/SgyS1SZJqwI6pR7JNY/WUHbPETeCYOLHdAzOXlQmwHBLya6bCxGvjy0drXAW0lscX/I05VsXbbWB3Ja8xbYkjxgMbmN5ifUaTH/DYzry/uMfR1wJ7khbjD/I3Yj1q8I+6F+S/iCZ0RmdCNLmLCFQiZsGOxyV6xW1Cxe7om3sED4h9AIebya3baKucx1MTAVIdOFeqWu3ZAzclePgE9sSHakQDDBG6wzq3VnrUtWysWkHKqlG4lC3AXnYhH/CrjH7G1YgGLBxYPzO4BS/mLHih9++S8kKR6IIhUgMKbj9QDtbTu7C+lKR0Y0zAPNLl1iuXb8N8L+BZgAFKZnMHoWj7GAAAAAElFTkSuQmCC\"); }\n\n.sim-div-options {\n  top: 95px;\n  margin-top: 5px;\n  left: 5px;\n  right: 5px;\n  position: absolute; }\n\n.sim-div-options-NLSS {\n  top: 125px !important; }\n\n.sim-undeformedOption {\n  width: 14px;\n  height: 14px; }\n\n.sim-undeformedOptionText {\n  color: white !important;\n  font-weight: 200 !important; }\n\n.sim-line1 {\n  position: absolute;\n  top: 110px;\n  width: 100%;\n  border-top: 1px solid black; }\n\n.sim-div-colorscale {\n  left: 5px;\n  right: 5px;\n  height: 220px;\n  margin-top: 5px;\n  position: absolute; }\n\n.sim-div-colorscale-top1 {\n  top: 120px; }\n\n.sim-div-colorscale-top1-NLSS {\n  top: 140px !important; }\n\n.sim-div-colorscale-top2 {\n  top: 100px; }\n\n.sim-div-colorscale-Collapse {\n  cursor: pointer; }\n\n.simulation-colorscale {\n  background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABAAAAAABCAYAAABADtw1AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAADdJREFUWIXt1LENACAMxEBn/6HDCFAg5QUurnflgm4AStJ/GtB9BDRIOwELkg4Q0PCc6f1ImgEs9yMAHrvm2CUAAAAASUVORK5CYII=\");\n  background-size: contain;\n  -moz-transform: rotate(90deg);\n  -webkit-transform: rotate(90deg);\n  width: 220px;\n  height: 20px;\n  left: -70px;\n  top: 110px;\n  position: absolute;\n  background-repeat: repeat; }\n\n.simulation-colorscale-NLSS {\n  width: 190px !important; }\n\n.sim-colorScaleTopText, .sim-colorScaleBottomText {\n  left: 52px;\n  color: white !important;\n  position: relative !important; }\n\n.sim-colorScaleTopText {\n  top: 0px; }\n\n.sim-colorScaleTopText-NLSS {\n  top: 13px !important; }\n\n.sim-colorScaleBottomText {\n  top: 195px; }\n\n.sim-colorScaleBottomText-NLSS {\n  top: 178px !important; }\n\n.sim-line2 {\n  position: absolute;\n  top: 360px;\n  width: 100%;\n  border-top: 1px solid black; }\n\n.sim-div-Table {\n  position: absolute !important;\n  top: 370px !important;\n  left: 5px !important;\n  right: 5px !important;\n  margin-top: 5px;\n  cursor: pointer; }\n\n.sim-div-Table-Collapse {\n  height: 0px !important;\n  transition: height 0s 10000s;\n  visibility: hidden !important; }\n\n.sim-table {\n  position: relative !important;\n  color: white !important;\n  width: 100% !important;\n  margin: 0 0 0 0;\n  -webkit-box-sizing: border-box !important;\n  -moz-box-sizing: border-box !important;\n  box-sizing: border-box !important; }\n\n.sim-hide {\n  visibility: hidden !important; }\n", ""]);

// exports


/***/ }),

/***/ "./node_modules/css-loader/lib/css-base.js":
/*!*************************************************!*\
  !*** ./node_modules/css-loader/lib/css-base.js ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
// css base code, injected by the css-loader
module.exports = function(useSourceMap) {
	var list = [];

	// return the list of modules as css string
	list.toString = function toString() {
		return this.map(function (item) {
			var content = cssWithMappingToString(item, useSourceMap);
			if(item[2]) {
				return "@media " + item[2] + "{" + content + "}";
			} else {
				return content;
			}
		}).join("");
	};

	// import a list of modules into the list
	list.i = function(modules, mediaQuery) {
		if(typeof modules === "string")
			modules = [[null, modules, ""]];
		var alreadyImportedModules = {};
		for(var i = 0; i < this.length; i++) {
			var id = this[i][0];
			if(typeof id === "number")
				alreadyImportedModules[id] = true;
		}
		for(i = 0; i < modules.length; i++) {
			var item = modules[i];
			// skip already imported module
			// this implementation is not 100% perfect for weird media query combinations
			//  when a module is imported multiple times with different media queries.
			//  I hope this will never occur (Hey this way we have smaller bundles)
			if(typeof item[0] !== "number" || !alreadyImportedModules[item[0]]) {
				if(mediaQuery && !item[2]) {
					item[2] = mediaQuery;
				} else if(mediaQuery) {
					item[2] = "(" + item[2] + ") and (" + mediaQuery + ")";
				}
				list.push(item);
			}
		}
	};
	return list;
};

function cssWithMappingToString(item, useSourceMap) {
	var content = item[1] || '';
	var cssMapping = item[3];
	if (!cssMapping) {
		return content;
	}

	if (useSourceMap && typeof btoa === 'function') {
		var sourceMapping = toComment(cssMapping);
		var sourceURLs = cssMapping.sources.map(function (source) {
			return '/*# sourceURL=' + cssMapping.sourceRoot + source + ' */'
		});

		return [content].concat(sourceURLs).concat([sourceMapping]).join('\n');
	}

	return [content].join('\n');
}

// Adapted from convert-source-map (MIT)
function toComment(sourceMap) {
	// eslint-disable-next-line no-undef
	var base64 = btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap))));
	var data = 'sourceMappingURL=data:application/json;charset=utf-8;base64,' + base64;

	return '/*# ' + data + ' */';
}


/***/ }),

/***/ "./node_modules/style-loader/lib/addStyles.js":
/*!****************************************************!*\
  !*** ./node_modules/style-loader/lib/addStyles.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

var stylesInDom = {};

var	memoize = function (fn) {
	var memo;

	return function () {
		if (typeof memo === "undefined") memo = fn.apply(this, arguments);
		return memo;
	};
};

var isOldIE = memoize(function () {
	// Test for IE <= 9 as proposed by Browserhacks
	// @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
	// Tests for existence of standard globals is to allow style-loader
	// to operate correctly into non-standard environments
	// @see https://github.com/webpack-contrib/style-loader/issues/177
	return window && document && document.all && !window.atob;
});

var getTarget = function (target, parent) {
  if (parent){
    return parent.querySelector(target);
  }
  return document.querySelector(target);
};

var getElement = (function (fn) {
	var memo = {};

	return function(target, parent) {
                // If passing function in options, then use it for resolve "head" element.
                // Useful for Shadow Root style i.e
                // {
                //   insertInto: function () { return document.querySelector("#foo").shadowRoot }
                // }
                if (typeof target === 'function') {
                        return target();
                }
                if (typeof memo[target] === "undefined") {
			var styleTarget = getTarget.call(this, target, parent);
			// Special case to return head of iframe instead of iframe itself
			if (window.HTMLIFrameElement && styleTarget instanceof window.HTMLIFrameElement) {
				try {
					// This will throw an exception if access to iframe is blocked
					// due to cross-origin restrictions
					styleTarget = styleTarget.contentDocument.head;
				} catch(e) {
					styleTarget = null;
				}
			}
			memo[target] = styleTarget;
		}
		return memo[target]
	};
})();

var singleton = null;
var	singletonCounter = 0;
var	stylesInsertedAtTop = [];

var	fixUrls = __webpack_require__(/*! ./urls */ "./node_modules/style-loader/lib/urls.js");

module.exports = function(list, options) {
	if (typeof DEBUG !== "undefined" && DEBUG) {
		if (typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
	}

	options = options || {};

	options.attrs = typeof options.attrs === "object" ? options.attrs : {};

	// Force single-tag solution on IE6-9, which has a hard limit on the # of <style>
	// tags it will allow on a page
	if (!options.singleton && typeof options.singleton !== "boolean") options.singleton = isOldIE();

	// By default, add <style> tags to the <head> element
        if (!options.insertInto) options.insertInto = "head";

	// By default, add <style> tags to the bottom of the target
	if (!options.insertAt) options.insertAt = "bottom";

	var styles = listToStyles(list, options);

	addStylesToDom(styles, options);

	return function update (newList) {
		var mayRemove = [];

		for (var i = 0; i < styles.length; i++) {
			var item = styles[i];
			var domStyle = stylesInDom[item.id];

			domStyle.refs--;
			mayRemove.push(domStyle);
		}

		if(newList) {
			var newStyles = listToStyles(newList, options);
			addStylesToDom(newStyles, options);
		}

		for (var i = 0; i < mayRemove.length; i++) {
			var domStyle = mayRemove[i];

			if(domStyle.refs === 0) {
				for (var j = 0; j < domStyle.parts.length; j++) domStyle.parts[j]();

				delete stylesInDom[domStyle.id];
			}
		}
	};
};

function addStylesToDom (styles, options) {
	for (var i = 0; i < styles.length; i++) {
		var item = styles[i];
		var domStyle = stylesInDom[item.id];

		if(domStyle) {
			domStyle.refs++;

			for(var j = 0; j < domStyle.parts.length; j++) {
				domStyle.parts[j](item.parts[j]);
			}

			for(; j < item.parts.length; j++) {
				domStyle.parts.push(addStyle(item.parts[j], options));
			}
		} else {
			var parts = [];

			for(var j = 0; j < item.parts.length; j++) {
				parts.push(addStyle(item.parts[j], options));
			}

			stylesInDom[item.id] = {id: item.id, refs: 1, parts: parts};
		}
	}
}

function listToStyles (list, options) {
	var styles = [];
	var newStyles = {};

	for (var i = 0; i < list.length; i++) {
		var item = list[i];
		var id = options.base ? item[0] + options.base : item[0];
		var css = item[1];
		var media = item[2];
		var sourceMap = item[3];
		var part = {css: css, media: media, sourceMap: sourceMap};

		if(!newStyles[id]) styles.push(newStyles[id] = {id: id, parts: [part]});
		else newStyles[id].parts.push(part);
	}

	return styles;
}

function insertStyleElement (options, style) {
	var target = getElement(options.insertInto)

	if (!target) {
		throw new Error("Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.");
	}

	var lastStyleElementInsertedAtTop = stylesInsertedAtTop[stylesInsertedAtTop.length - 1];

	if (options.insertAt === "top") {
		if (!lastStyleElementInsertedAtTop) {
			target.insertBefore(style, target.firstChild);
		} else if (lastStyleElementInsertedAtTop.nextSibling) {
			target.insertBefore(style, lastStyleElementInsertedAtTop.nextSibling);
		} else {
			target.appendChild(style);
		}
		stylesInsertedAtTop.push(style);
	} else if (options.insertAt === "bottom") {
		target.appendChild(style);
	} else if (typeof options.insertAt === "object" && options.insertAt.before) {
		var nextSibling = getElement(options.insertAt.before, target);
		target.insertBefore(style, nextSibling);
	} else {
		throw new Error("[Style Loader]\n\n Invalid value for parameter 'insertAt' ('options.insertAt') found.\n Must be 'top', 'bottom', or Object.\n (https://github.com/webpack-contrib/style-loader#insertat)\n");
	}
}

function removeStyleElement (style) {
	if (style.parentNode === null) return false;
	style.parentNode.removeChild(style);

	var idx = stylesInsertedAtTop.indexOf(style);
	if(idx >= 0) {
		stylesInsertedAtTop.splice(idx, 1);
	}
}

function createStyleElement (options) {
	var style = document.createElement("style");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}

	if(options.attrs.nonce === undefined) {
		var nonce = getNonce();
		if (nonce) {
			options.attrs.nonce = nonce;
		}
	}

	addAttrs(style, options.attrs);
	insertStyleElement(options, style);

	return style;
}

function createLinkElement (options) {
	var link = document.createElement("link");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}
	options.attrs.rel = "stylesheet";

	addAttrs(link, options.attrs);
	insertStyleElement(options, link);

	return link;
}

function addAttrs (el, attrs) {
	Object.keys(attrs).forEach(function (key) {
		el.setAttribute(key, attrs[key]);
	});
}

function getNonce() {
	if (false) {}

	return __webpack_require__.nc;
}

function addStyle (obj, options) {
	var style, update, remove, result;

	// If a transform function was defined, run it on the css
	if (options.transform && obj.css) {
	    result = typeof options.transform === 'function'
		 ? options.transform(obj.css) 
		 : options.transform.default(obj.css);

	    if (result) {
	    	// If transform returns a value, use that instead of the original css.
	    	// This allows running runtime transformations on the css.
	    	obj.css = result;
	    } else {
	    	// If the transform function returns a falsy value, don't add this css.
	    	// This allows conditional loading of css
	    	return function() {
	    		// noop
	    	};
	    }
	}

	if (options.singleton) {
		var styleIndex = singletonCounter++;

		style = singleton || (singleton = createStyleElement(options));

		update = applyToSingletonTag.bind(null, style, styleIndex, false);
		remove = applyToSingletonTag.bind(null, style, styleIndex, true);

	} else if (
		obj.sourceMap &&
		typeof URL === "function" &&
		typeof URL.createObjectURL === "function" &&
		typeof URL.revokeObjectURL === "function" &&
		typeof Blob === "function" &&
		typeof btoa === "function"
	) {
		style = createLinkElement(options);
		update = updateLink.bind(null, style, options);
		remove = function () {
			removeStyleElement(style);

			if(style.href) URL.revokeObjectURL(style.href);
		};
	} else {
		style = createStyleElement(options);
		update = applyToTag.bind(null, style);
		remove = function () {
			removeStyleElement(style);
		};
	}

	update(obj);

	return function updateStyle (newObj) {
		if (newObj) {
			if (
				newObj.css === obj.css &&
				newObj.media === obj.media &&
				newObj.sourceMap === obj.sourceMap
			) {
				return;
			}

			update(obj = newObj);
		} else {
			remove();
		}
	};
}

var replaceText = (function () {
	var textStore = [];

	return function (index, replacement) {
		textStore[index] = replacement;

		return textStore.filter(Boolean).join('\n');
	};
})();

function applyToSingletonTag (style, index, remove, obj) {
	var css = remove ? "" : obj.css;

	if (style.styleSheet) {
		style.styleSheet.cssText = replaceText(index, css);
	} else {
		var cssNode = document.createTextNode(css);
		var childNodes = style.childNodes;

		if (childNodes[index]) style.removeChild(childNodes[index]);

		if (childNodes.length) {
			style.insertBefore(cssNode, childNodes[index]);
		} else {
			style.appendChild(cssNode);
		}
	}
}

function applyToTag (style, obj) {
	var css = obj.css;
	var media = obj.media;

	if(media) {
		style.setAttribute("media", media)
	}

	if(style.styleSheet) {
		style.styleSheet.cssText = css;
	} else {
		while(style.firstChild) {
			style.removeChild(style.firstChild);
		}

		style.appendChild(document.createTextNode(css));
	}
}

function updateLink (link, options, obj) {
	var css = obj.css;
	var sourceMap = obj.sourceMap;

	/*
		If convertToAbsoluteUrls isn't defined, but sourcemaps are enabled
		and there is no publicPath defined then lets turn convertToAbsoluteUrls
		on by default.  Otherwise default to the convertToAbsoluteUrls option
		directly
	*/
	var autoFixUrls = options.convertToAbsoluteUrls === undefined && sourceMap;

	if (options.convertToAbsoluteUrls || autoFixUrls) {
		css = fixUrls(css);
	}

	if (sourceMap) {
		// http://stackoverflow.com/a/26603875
		css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
	}

	var blob = new Blob([css], { type: "text/css" });

	var oldSrc = link.href;

	link.href = URL.createObjectURL(blob);

	if(oldSrc) URL.revokeObjectURL(oldSrc);
}


/***/ }),

/***/ "./node_modules/style-loader/lib/urls.js":
/*!***********************************************!*\
  !*** ./node_modules/style-loader/lib/urls.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports) {


/**
 * When source maps are enabled, `style-loader` uses a link element with a data-uri to
 * embed the css on the page. This breaks all relative urls because now they are relative to a
 * bundle instead of the current page.
 *
 * One solution is to only use full urls, but that may be impossible.
 *
 * Instead, this function "fixes" the relative urls to be absolute according to the current page location.
 *
 * A rudimentary test suite is located at `test/fixUrls.js` and can be run via the `npm test` command.
 *
 */

module.exports = function (css) {
  // get current location
  var location = typeof window !== "undefined" && window.location;

  if (!location) {
    throw new Error("fixUrls requires window.location");
  }

	// blank or null?
	if (!css || typeof css !== "string") {
	  return css;
  }

  var baseUrl = location.protocol + "//" + location.host;
  var currentDir = baseUrl + location.pathname.replace(/\/[^\/]*$/, "/");

	// convert each url(...)
	/*
	This regular expression is just a way to recursively match brackets within
	a string.

	 /url\s*\(  = Match on the word "url" with any whitespace after it and then a parens
	   (  = Start a capturing group
	     (?:  = Start a non-capturing group
	         [^)(]  = Match anything that isn't a parentheses
	         |  = OR
	         \(  = Match a start parentheses
	             (?:  = Start another non-capturing groups
	                 [^)(]+  = Match anything that isn't a parentheses
	                 |  = OR
	                 \(  = Match a start parentheses
	                     [^)(]*  = Match anything that isn't a parentheses
	                 \)  = Match a end parentheses
	             )  = End Group
              *\) = Match anything and then a close parens
          )  = Close non-capturing group
          *  = Match anything
       )  = Close capturing group
	 \)  = Match a close parens

	 /gi  = Get all matches, not the first.  Be case insensitive.
	 */
	var fixedCss = css.replace(/url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)/gi, function(fullMatch, origUrl) {
		// strip quotes (if they exist)
		var unquotedOrigUrl = origUrl
			.trim()
			.replace(/^"(.*)"$/, function(o, $1){ return $1; })
			.replace(/^'(.*)'$/, function(o, $1){ return $1; });

		// already a full url? no change
		if (/^(#|data:|http:\/\/|https:\/\/|file:\/\/\/|\s*$)/i.test(unquotedOrigUrl)) {
		  return fullMatch;
		}

		// convert the url to a full url
		var newUrl;

		if (unquotedOrigUrl.indexOf("//") === 0) {
		  	//TODO: should we add protocol?
			newUrl = unquotedOrigUrl;
		} else if (unquotedOrigUrl.indexOf("/") === 0) {
			// path should be relative to the base url
			newUrl = baseUrl + unquotedOrigUrl; // already starts with '/'
		} else {
			// path should be relative to current directory
			newUrl = currentDir + unquotedOrigUrl.replace(/^\.\//, ""); // Strip leading './'
		}

		// send back the fixed url(...)
		return "url(" + JSON.stringify(newUrl) + ")";
	});

	// send back the fixed css
	return fixedCss;
};


/***/ })

/******/ });
//# sourceMappingURL=FusionSim.js.map