/*!
 * LMV v7.37.0
 * 
 * Copyright 2021 Autodesk, Inc.
 * All rights reserved.
 * 
 * This computer source code and related instructions and comments are the
 * unpublished confidential and proprietary information of Autodesk, Inc.
 * and are protected under Federal copyright and state trade secret law.
 * They may not be disclosed to, copied or used by any third party without
 * the prior written consent of Autodesk, Inc.
 * 
 * Autodesk Forge Viewer Usage Limitations:
 * 
 * The Autodesk Forge viewer can only be used to view files generated by
 * Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be
 * delivered from an Autodesk hosted URL.
 */
Autodesk.Extensions.ProfileUi =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./extensions/ProfileUi/index.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./extensions/ProfileUi/Locales.js":
/*!*****************************************!*\
  !*** ./extensions/ProfileUi/Locales.js ***!
  \*****************************************/
/*! exports provided: locales */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "locales", function() { return locales; });
/* harmony import */ var _res_locales_en_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../res/locales/en/nobundle-profiles.loc.json */ "./res/locales/en/nobundle-profiles.loc.json");
var _res_locales_en_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_0___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/en/nobundle-profiles.loc.json */ "./res/locales/en/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_cs_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../../res/locales/cs/nobundle-profiles.loc.json */ "./res/locales/cs/nobundle-profiles.loc.json");
var _res_locales_cs_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_1___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/cs/nobundle-profiles.loc.json */ "./res/locales/cs/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_de_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../../res/locales/de/nobundle-profiles.loc.json */ "./res/locales/de/nobundle-profiles.loc.json");
var _res_locales_de_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_2___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/de/nobundle-profiles.loc.json */ "./res/locales/de/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_es_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../res/locales/es/nobundle-profiles.loc.json */ "./res/locales/es/nobundle-profiles.loc.json");
var _res_locales_es_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_3___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/es/nobundle-profiles.loc.json */ "./res/locales/es/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_fr_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! ../../res/locales/fr/nobundle-profiles.loc.json */ "./res/locales/fr/nobundle-profiles.loc.json");
var _res_locales_fr_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_4___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr/nobundle-profiles.loc.json */ "./res/locales/fr/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_fr_CA_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__(/*! ../../res/locales/fr-CA/nobundle-profiles.loc.json */ "./res/locales/fr-CA/nobundle-profiles.loc.json");
var _res_locales_fr_CA_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_5___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/fr-CA/nobundle-profiles.loc.json */ "./res/locales/fr-CA/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_it_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__(/*! ../../res/locales/it/nobundle-profiles.loc.json */ "./res/locales/it/nobundle-profiles.loc.json");
var _res_locales_it_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_6___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/it/nobundle-profiles.loc.json */ "./res/locales/it/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_ja_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__(/*! ../../res/locales/ja/nobundle-profiles.loc.json */ "./res/locales/ja/nobundle-profiles.loc.json");
var _res_locales_ja_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_7___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ja/nobundle-profiles.loc.json */ "./res/locales/ja/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_ko_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_8__ = __webpack_require__(/*! ../../res/locales/ko/nobundle-profiles.loc.json */ "./res/locales/ko/nobundle-profiles.loc.json");
var _res_locales_ko_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_8___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ko/nobundle-profiles.loc.json */ "./res/locales/ko/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_pl_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_9__ = __webpack_require__(/*! ../../res/locales/pl/nobundle-profiles.loc.json */ "./res/locales/pl/nobundle-profiles.loc.json");
var _res_locales_pl_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_9___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pl/nobundle-profiles.loc.json */ "./res/locales/pl/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_pt_BR_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_10__ = __webpack_require__(/*! ../../res/locales/pt-BR/nobundle-profiles.loc.json */ "./res/locales/pt-BR/nobundle-profiles.loc.json");
var _res_locales_pt_BR_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_10___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/pt-BR/nobundle-profiles.loc.json */ "./res/locales/pt-BR/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_ru_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_11__ = __webpack_require__(/*! ../../res/locales/ru/nobundle-profiles.loc.json */ "./res/locales/ru/nobundle-profiles.loc.json");
var _res_locales_ru_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_11___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/ru/nobundle-profiles.loc.json */ "./res/locales/ru/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_tr_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_12__ = __webpack_require__(/*! ../../res/locales/tr/nobundle-profiles.loc.json */ "./res/locales/tr/nobundle-profiles.loc.json");
var _res_locales_tr_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_12___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/tr/nobundle-profiles.loc.json */ "./res/locales/tr/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANS_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_13__ = __webpack_require__(/*! ../../res/locales/zh-HANS/nobundle-profiles.loc.json */ "./res/locales/zh-HANS/nobundle-profiles.loc.json");
var _res_locales_zh_HANS_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_13___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANS/nobundle-profiles.loc.json */ "./res/locales/zh-HANS/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_zh_HANT_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_14__ = __webpack_require__(/*! ../../res/locales/zh-HANT/nobundle-profiles.loc.json */ "./res/locales/zh-HANT/nobundle-profiles.loc.json");
var _res_locales_zh_HANT_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_14___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HANT/nobundle-profiles.loc.json */ "./res/locales/zh-HANT/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_zh_HK_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_15__ = __webpack_require__(/*! ../../res/locales/zh-HK/nobundle-profiles.loc.json */ "./res/locales/zh-HK/nobundle-profiles.loc.json");
var _res_locales_zh_HK_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_15___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/zh-HK/nobundle-profiles.loc.json */ "./res/locales/zh-HK/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_nl_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_16__ = __webpack_require__(/*! ../../res/locales/nl/nobundle-profiles.loc.json */ "./res/locales/nl/nobundle-profiles.loc.json");
var _res_locales_nl_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_16___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/nl/nobundle-profiles.loc.json */ "./res/locales/nl/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_sv_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_17__ = __webpack_require__(/*! ../../res/locales/sv/nobundle-profiles.loc.json */ "./res/locales/sv/nobundle-profiles.loc.json");
var _res_locales_sv_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_17___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/sv/nobundle-profiles.loc.json */ "./res/locales/sv/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_da_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_18__ = __webpack_require__(/*! ../../res/locales/da/nobundle-profiles.loc.json */ "./res/locales/da/nobundle-profiles.loc.json");
var _res_locales_da_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_18___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/da/nobundle-profiles.loc.json */ "./res/locales/da/nobundle-profiles.loc.json", 1);
/* harmony import */ var _res_locales_no_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_19__ = __webpack_require__(/*! ../../res/locales/no/nobundle-profiles.loc.json */ "./res/locales/no/nobundle-profiles.loc.json");
var _res_locales_no_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_19___namespace = /*#__PURE__*/__webpack_require__.t(/*! ../../res/locales/no/nobundle-profiles.loc.json */ "./res/locales/no/nobundle-profiles.loc.json", 1);
/**
 * Include each locale json file and return it in an object
 * that can be consumed by i18n
 */






















var locales = {
  en: _res_locales_en_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_0__,
  cs: _res_locales_cs_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_1__,
  de: _res_locales_de_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_2__,
  es: _res_locales_es_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_3__,
  fr: _res_locales_fr_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_4__,
  'fr-CA': _res_locales_fr_CA_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_5__,
  it: _res_locales_it_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_6__,
  ja: _res_locales_ja_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_7__,
  ko: _res_locales_ko_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_8__,
  pl: _res_locales_pl_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_9__,
  'pt-BR': _res_locales_pt_BR_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_10__,
  ru: _res_locales_ru_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_11__,
  tr: _res_locales_tr_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_12__,
  'zh-HANS': _res_locales_zh_HANS_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_13__,
  'zh-HANT': _res_locales_zh_HANT_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_14__,
  'zh-HK': _res_locales_zh_HK_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_15__,
  nl: _res_locales_nl_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_16__,
  sv: _res_locales_sv_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_17__,
  da: _res_locales_da_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_18__,
  no: _res_locales_no_nobundle_profiles_loc_json__WEBPACK_IMPORTED_MODULE_19__ };

/***/ }),

/***/ "./extensions/ProfileUi/ProfilePanel.js":
/*!**********************************************!*\
  !*** ./extensions/ProfileUi/ProfilePanel.js ***!
  \**********************************************/
/*! exports provided: ProfilePanel */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProfilePanel", function() { return ProfilePanel; });
var TAB_ID = 'configTab';
var TAB_LABEL = 'Configuration';
var DEFAULT_DESC = 'Description not available';

/**
                                                 * Retrieves all of the unique profiles that have been registered.
                                                 * @param {Object} registeredProfiles - viewer.profileManager.getProfiles()
                                                 * @returns {Autodesk.Viewing.Profile[]} - array of viewer unique profiles
                                                 * @private
                                                 */
function getUniqueProfiles(registeredProfiles) {
  var profiles = [];
  for (var key in registeredProfiles) {
    var profile = registeredProfiles[key];
    if (profiles.indexOf(profile) === -1) {
      profiles.push(profile);
    }
  }
  return profiles;
}

var ProfilePanel = function ProfilePanel(viewer, title) {

  var PANEL_ID = 'adsk_profile_panel_' + viewer.id;
  var opts = { heightAdjustment: 100, width: 460, hideTabBar: true };
  Autodesk.Viewing.UI.SettingsPanel.call(this, viewer.container, PANEL_ID, title, opts);

  this.container.classList.add('viewer-settings-panel');
  this.viewer = viewer;
  this.setGlobalManager(viewer.globalManager);

  this.addTab(TAB_ID, TAB_LABEL, { className: 'config' });
  this.selectTab(TAB_ID);

  this._profiles = getUniqueProfiles(this.viewer.profileManager.getProfiles());
  this._onClick = this._onClick.bind(this);
  this._onProfileChanged = this._onProfileChanged.bind(this);

  var listContainer = this.tablesContainer.childNodes[0];
  this._simpleList = this.addSimpleList(listContainer, renderListItem, this._onClick);
  this._updateListUi();

  this.viewer.addEventListener(Autodesk.Viewing.PROFILE_CHANGE_EVENT, this._onProfileChanged);
};

ProfilePanel.prototype = Object.create(Autodesk.Viewing.UI.SettingsPanel.prototype);
ProfilePanel.prototype.constructor = ProfilePanel;

/**
                                                    * @private
                                                    */
ProfilePanel.prototype._onClick = function (index) {
  var profile = this._profiles[index];
  this.viewer.setProfile(profile);
};

/**
    * Appends a cell to the Profile grid.
    * @param {*} event - should contain event.profile
    * @returns {boolean} - returns true if a grid cell was added.
    * @private
    */
ProfilePanel.prototype._onProfileChanged = function (event) {
  var profile = event && event.profile;
  if (!profile) return false;
  if (this._profiles.indexOf(profile) === -1) {
    this._profiles.push(profile);
  }
  this._updateListUi();
};

/**
    * Updates the table grid ui.
    * @private
    */
ProfilePanel.prototype._updateListUi = function () {
  // Create a new array of from the this._profiles array.
  // This will update the description if it is not present.
  var uiItems = this._profiles.map(function (profile) {
    return {
      name: profile.label || profile.name,
      description: profile.description || DEFAULT_DESC };

  });

  var selectedIndex = this._profiles.indexOf(this.viewer.profile);
  this._simpleList.setData(uiItems, selectedIndex);

  // Resize the panel for the new cell.
  this.resizeToContent();
};

/**
    * Uninitialize the panel.
    * Removes all event listeners associated with the panel.
    */
ProfilePanel.prototype.uninitialize = function () {
  Autodesk.Viewing.UI.SettingsPanel.prototype.uninitialize.call(this);
  this.viewer.removeEventListener(Autodesk.Viewing.PROFILE_CHANGE_EVENT, this._onProfileChanged);
  this.removeSimpleList(this._simpleList);
  this._simpleList = null;
};



/**
                          * Populates the DOM list element with all the necessary UI to
                          * display a Profile's info the end users.
                          *
                          * @param {HTMLElement} domElem - The DOM element created by SimpleList.
                          * @param {Object} uiItem - The list item to render by domElem.
                          * @param {Object} options - Bag of options.
                          *
                          * @private
                          */
function renderListItem(domElem, uiItem, options) {

  var _document = options.domDocument;
  var i18n = Autodesk.Viewing.i18n;

  domElem.classList.add("settings-cell");

  // Name
  var name = _document.createElement("span");
  name.textContent = i18n.translate(uiItem.name);
  name.classList.add("settings-name");
  name.setAttribute('data-i18n', uiItem.name);
  domElem.appendChild(name);

  var description = _document.createElement("span");
  description.classList.add("settings-description");
  description.textContent = !uiItem.description ? '' : i18n.translate(uiItem.description);
  description.setAttribute('data-i18n', uiItem.description);
  domElem.appendChild(description);
}

/***/ }),

/***/ "./extensions/ProfileUi/index.js":
/*!***************************************!*\
  !*** ./extensions/ProfileUi/index.js ***!
  \***************************************/
/*! exports provided: ProfileUi */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ProfileUi", function() { return ProfileUi; });
/* harmony import */ var _ProfilePanel__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./ProfilePanel */ "./extensions/ProfileUi/ProfilePanel.js");
/* harmony import */ var _Locales__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./Locales */ "./extensions/ProfileUi/Locales.js");


var BUTTON_LABEL = 'Profiles';

/**
                                * Provides UI controls for Profiles
                                * 
                                * The extension id is: `Autodesk.ProfileUi`
                                * 
                                * @example
                                *    viewer.loadExtension('Autodesk.ProfileUi');
                                * 
                                * @see {@link Autodesk.Viewing.Extension} for common inherited methods.
                                * @constructor
                                * @param {Autodesk.Viewing.Viewer3D} viewer - Viewer instance.
                                * @param {Object} options - Not used.
                                */
function ProfileUi(viewer, options) {
  Autodesk.Viewing.Extension.call(this, viewer, options);
  this.viewer = viewer;
  this._configButtonId = null;
  this._panel = null;
  this.openPanel = this.openPanel.bind(this);
  this._initButtonConfig = this._initButtonConfig.bind(this);
};

ProfileUi.prototype = Object.create(Autodesk.Viewing.Extension.prototype);
ProfileUi.prototype.constructor = ProfileUi;

/**
                                              * Load the extensions
                                              */
ProfileUi.prototype.load = function () {
  this.extendLocalization(_Locales__WEBPACK_IMPORTED_MODULE_1__["locales"]);
  return true;
};

/**
    * Unload the extension.
    */
ProfileUi.prototype.unload = function () {
  if (this._configButtonId !== null) {
    this.viewer.viewerSettingsPanel.removeConfigButton(this._configButtonId);
    this._configButtonId = null;
  }
  if (this._panel) {
    this._panel.uninitialize();
    this._panel = null;
  }
  return true;
};

/**
    * Invoked by the viewer when the toolbar UI is available. 
    * Adds a button to the Settings panel.
    *
    * @alias Autodesk.Viewing.Extensions.ProfileUi#onToolbarCreated
    */
ProfileUi.prototype.onToolbarCreated = function () {
  this._initButtonConfig();
};

/**
    * Opens the Profiles panel.
    *
    * @alias Autodesk.Viewing.Extensions.ProfileUi#openPanel
    */
ProfileUi.prototype.openPanel = function () {
  if (!this._panel) {
    this._panel = new _ProfilePanel__WEBPACK_IMPORTED_MODULE_0__["ProfilePanel"](this.viewer, BUTTON_LABEL);
  }
  this._panel.setVisible(true);
};

/**
    * Adds a button to the Settings Panel.
    * @private
    */
ProfileUi.prototype._initButtonConfig = function () {
  var settingsPanel = this.viewer.getSettingsPanel();
  if (!settingsPanel) {
    this.addEventListener(av.SETTINGS_PANEL_CREATED_EVENT, this._initButtonConfig, { once: true });
    return;
  }
  this._configButtonId = settingsPanel.addConfigButton(BUTTON_LABEL, this.openPanel);
};


/**
    * Register the extension with the extension manager.
    */
Autodesk.Viewing.theExtensionManager.registerExtension('Autodesk.ProfileUi', ProfileUi);

/***/ }),

/***/ "./res/locales/cs/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/cs/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"cs\",\"@@context\":\"Profily prohlížeče\",\"Profiles\":\"Profily\",\"Viewer Profiles\":\"Profily prohlížeče\",\"Manufacturing (Default)\":\"Výroba (výchozí)\",\"Construction (AEC)\":\"Stavby (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Spolupráce na návrhu\",\"Default Viewer settings\":\"Výchozí nastavení prohlížeče\",\"A common set of preferences designed for the Construction industry\":\"Běžná sada předvoleb navržená pro stavební průmysl\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Poskytuje uživatelské prostředí podobné aplikaci Autodesk Navisworks pro stolní počítače\",\"Description not available\":\"Popis není k dispozici\",\"User experience that matches Design Collaboration\":\"Uživatelské prostředí, které umožňuje spolupráci na návrhu\"}");

/***/ }),

/***/ "./res/locales/da/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/da/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"da\",\"@@context\":\"Fremviserprofiler\",\"Profiles\":\"Profiler\",\"Viewer Profiles\":\"Fremviserprofiler\",\"Manufacturing (Default)\":\"Fremstilling (Standard)\",\"Construction (AEC)\":\"Konstruktion (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Designsamarbejde\",\"Default Viewer settings\":\"Standardindstillinger for fremviser\",\"A common set of preferences designed for the Construction industry\":\"Et fælles sæt præferencer, som er udviklet til konstruktionsindustrien\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Giver en brugeroplevelse lignende den fra desktopapplikationen Autodesk Navisworks\",\"Description not available\":\"Beskrivelse ikke tilgængelig\",\"User experience that matches Design Collaboration\":\"Brugeroplevelse, der matcher Designsamarbejde\"}");

/***/ }),

/***/ "./res/locales/de/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/de/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"de\",\"@@context\":\"Viewer-Profile\",\"Profiles\":\"Profile\",\"Viewer Profiles\":\"Viewer-Profile\",\"Manufacturing (Default)\":\"Fertigung (Vorgabe)\",\"Construction (AEC)\":\"Bauwesen (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Vorgabemäßige Viewer-Einstellungen\",\"A common set of preferences designed for the Construction industry\":\"Einige häufig genutzte Einstellungen im Bauwesen\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Bietet eine ähnliche Benutzererfahrung wie die Desktop-Anwendung Autodesk Navisworks\",\"Description not available\":\"Beschreibung nicht verfügbar\",\"User experience that matches Design Collaboration\":\"Ähnliche Benutzererfahrung wie Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/en/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/en/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"en\",\"@@context\":\"Viewer Profiles\",\"Profiles\":\"Profiles\",\"Viewer Profiles\":\"Viewer Profiles\",\"Manufacturing (Default)\":\"Manufacturing (Default)\",\"Construction (AEC)\":\"Construction (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Default Viewer settings\",\"A common set of preferences designed for the Construction industry\":\"A common set of preferences designed for the Construction industry\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Provides a user experience similar to Autodesk Navisworks desktop application\",\"Description not available\":\"Description not available\",\"User experience that matches Design Collaboration\":\"User experience that matches Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/es/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/es/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"es\",\"@@context\":\"Perfiles del visor\",\"Profiles\":\"Perfiles\",\"Viewer Profiles\":\"Perfiles del visor\",\"Manufacturing (Default)\":\"Fabricación (por defecto)\",\"Construction (AEC)\":\"Construcción (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Parámetros por defecto del visor\",\"A common set of preferences designed for the Construction industry\":\"Conjunto de preferencias comunes diseñado para el sector de la construcción\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Proporciona una experiencia de usuario similar a la de la aplicación de escritorio de Autodesk Navisworks\",\"Description not available\":\"Descripción no disponible\",\"User experience that matches Design Collaboration\":\"Experiencia del usuario que coincide con Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/fr-CA/nobundle-profiles.loc.json":
/*!******************************************************!*\
  !*** ./res/locales/fr-CA/nobundle-profiles.loc.json ***!
  \******************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr-CA\",\"@@context\":\"Profils de visualiseur\",\"Profiles\":\"Profils\",\"Viewer Profiles\":\"Profils de visualiseur\",\"Manufacturing (Default)\":\"Fabrication (par défaut)\",\"Construction (AEC)\":\"Construction (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Paramètres du visualiseur par défaut\",\"A common set of preferences designed for the Construction industry\":\"Ensemble de préférences commun conçu pour le secteur de la construction\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Fournit une expérience utilisateur similaire à l'application de bureau Autodesk Navisworks\",\"Description not available\":\"Description non disponible\",\"User experience that matches Design Collaboration\":\"Expérience utilisateur correspondant à Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/fr/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/fr/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"fr\",\"@@context\":\"Profils du visualiseur\",\"Profiles\":\"Profils\",\"Viewer Profiles\":\"Profils du visualiseur\",\"Manufacturing (Default)\":\"Fabrication (par défaut)\",\"Construction (AEC)\":\"Construction (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Paramètres du visualiseur par défaut\",\"A common set of preferences designed for the Construction industry\":\"Jeu de préférences commun conçu pour le secteur de la construction\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Fournit une expérience utilisateur similaire à l'application de bureau Autodesk Navisworks\",\"Description not available\":\"Description non disponible\",\"User experience that matches Design Collaboration\":\"Expérience utilisateur correspondant à Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/it/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/it/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"it\",\"@@context\":\"Profili visualizzatori\",\"Profiles\":\"Profili\",\"Viewer Profiles\":\"Profili visualizzatori\",\"Manufacturing (Default)\":\"Produzione (default)\",\"Construction (AEC)\":\"Costruzione (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Collaborazione alla progettazione\",\"Default Viewer settings\":\"Impostazioni del visualizzatore di default\",\"A common set of preferences designed for the Construction industry\":\"Un comune insieme di preferenze progettato per il settore delle costruzioni\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Fornisce un'esperienza utente simile all'applicazione desktop Autodesk Navisworks\",\"Description not available\":\"Descrizione non disponibile\",\"User experience that matches Design Collaboration\":\"Esperienza utente che corrisponde a Collaborazione alla progettazione\"}");

/***/ }),

/***/ "./res/locales/ja/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/ja/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ja\",\"@@context\":\"ビューア プロファイル\",\"Profiles\":\"プロファイル\",\"Viewer Profiles\":\"ビューア プロファイル\",\"Manufacturing (Default)\":\"製造(既定)\",\"Construction (AEC)\":\"建設(AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"既定の Viewer 設定\",\"A common set of preferences designed for the Construction industry\":\"建設業界向けにデザインされた共通の設定セット\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Autodesk Navisworks デスクトップ アプリケーションと同様のユーザ エクスペリエンスを提供します\",\"Description not available\":\"説明は利用できません\",\"User experience that matches Design Collaboration\":\"Design Collaboration と同様のユーザ エクスペリエンス\"}");

/***/ }),

/***/ "./res/locales/ko/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/ko/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ko\",\"@@context\":\"뷰어 프로파일\",\"Profiles\":\"프로파일\",\"Viewer Profiles\":\"뷰어 프로파일\",\"Manufacturing (Default)\":\"제조(기본값)\",\"Construction (AEC)\":\"시공(AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"설계 협업\",\"Default Viewer settings\":\"기본 뷰어 설정\",\"A common set of preferences designed for the Construction industry\":\"시공 산업을 위해 설계된 일반적인 기본 설정 세트\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Autodesk Navisworks 데스크탑 응용프로그램과 유사한 사용자 환경을 제공합니다.\",\"Description not available\":\"설명을 사용할 수 없음\",\"User experience that matches Design Collaboration\":\"설계 협업과 일치하는 사용자 경험\"}");

/***/ }),

/***/ "./res/locales/nl/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/nl/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"nl\",\"@@context\":\"Viewerprofielen\",\"Profiles\":\"Profielen\",\"Viewer Profiles\":\"Viewerprofielen\",\"Manufacturing (Default)\":\"Productie (Standaard)\",\"Construction (AEC)\":\"Bouw (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Standaardinstellingen Viewer\",\"A common set of preferences designed for the Construction industry\":\"Een set met veelvoorkomende voorkeuren, ontworpen voor de bouwsector\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Biedt een gebruikerservaring die vergelijkbaar is met de desktop-app van Autodesk Navisworks\",\"Description not available\":\"Omschrijving niet beschikbaar\",\"User experience that matches Design Collaboration\":\"Gebruikerservaring die overeenkomt met die van Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/no/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/no/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"no\",\"@@context\":\"Visningsprofiler\",\"Profiles\":\"Profiler\",\"Viewer Profiles\":\"Visningsprofiler\",\"Manufacturing (Default)\":\"Produksjon (standard)\",\"Construction (AEC)\":\"Konstruksjon (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Standard visningsinnstillinger\",\"A common set of preferences designed for the Construction industry\":\"Et felles sett med preferanser utformet for konstruksjonsbransjen\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Gir en brukeropplevelse som likner Autodesk Navisworks-skrivebordsprogrammet\",\"Description not available\":\"Beskrivelse er ikke tilgjengelig\",\"User experience that matches Design Collaboration\":\"Brukeropplevelse som er lik Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/pl/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/pl/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pl\",\"@@context\":\"Profile przeglądarki\",\"Profiles\":\"Profile\",\"Viewer Profiles\":\"Profile przeglądarki\",\"Manufacturing (Default)\":\"Produkcja (domyślnie)\",\"Construction (AEC)\":\"Budownictwo (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Współpraca przy projektowaniu\",\"Default Viewer settings\":\"Domyślne ustawienia przeglądarki\",\"A common set of preferences designed for the Construction industry\":\"Wspólny zestaw preferencji zaprojektowanych dla branży budowlanej\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Zapewnia interfejs użytkownika podobny do aplikacji Autodesk Navisworks na komputerze\",\"Description not available\":\"Opis niedostępny\",\"User experience that matches Design Collaboration\":\"Obsługa przez użytkownika, która odpowiada współpracy przy projektowaniu\"}");

/***/ }),

/***/ "./res/locales/pt-BR/nobundle-profiles.loc.json":
/*!******************************************************!*\
  !*** ./res/locales/pt-BR/nobundle-profiles.loc.json ***!
  \******************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"pt\",\"@@context\":\"Perfis do visualizador\",\"Profiles\":\"Perfis\",\"Viewer Profiles\":\"Perfis do visualizador\",\"Manufacturing (Default)\":\"Manufatura (Padrão)\",\"Construction (AEC)\":\"Construção (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Configurações padrão do visualizador\",\"A common set of preferences designed for the Construction industry\":\"Um conjunto comum de preferências projetadas para a indústria de construção\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Fornece uma experiência de usuário similar ao aplicativo para desktop do Autodesk Navisworks\",\"Description not available\":\"Descrição não disponível\",\"User experience that matches Design Collaboration\":\"Experiência de usuário similar ao Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/ru/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/ru/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"ru\",\"@@context\":\"Профили средства просмотра\",\"Profiles\":\"Профили\",\"Viewer Profiles\":\"Профили средства просмотра\",\"Manufacturing (Default)\":\"Промышленное производство (по умолчанию)\",\"Construction (AEC)\":\"Строительство (архитектура и строительство)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Параметры средства просмотра по умолчанию\",\"A common set of preferences designed for the Construction industry\":\"Стандартный набор параметров, предназначенный для строительной отрасли\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Обеспечивает рабочий процесс, аналогичный классическому приложению Autodesk Navisworks\",\"Description not available\":\"Описание недоступно\",\"User experience that matches Design Collaboration\":\"Рабочий процесс, как в Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/sv/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/sv/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"sv\",\"@@context\":\"Profiler för visningsprogram\",\"Profiles\":\"Profiler\",\"Viewer Profiles\":\"Profiler för visningsprogram\",\"Manufacturing (Default)\":\"Tillverkning (Standard)\",\"Construction (AEC)\":\"Bygg (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Design Collaboration\",\"Default Viewer settings\":\"Standardinställningar för Viewer\",\"A common set of preferences designed for the Construction industry\":\"En gemensam uppsättning inställningar som tagits fram för byggbranschen\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Ger en användarupplevelse som efterliknar Autodesk Navisworks-skrivbordsprogrammet\",\"Description not available\":\"Ingen beskrivning tillgänglig\",\"User experience that matches Design Collaboration\":\"Användarmiljö som matchar Design Collaboration\"}");

/***/ }),

/***/ "./res/locales/tr/nobundle-profiles.loc.json":
/*!***************************************************!*\
  !*** ./res/locales/tr/nobundle-profiles.loc.json ***!
  \***************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"tr\",\"@@context\":\"Görüntüleyici Profilleri\",\"Profiles\":\"Profiller\",\"Viewer Profiles\":\"Görüntüleyici Profilleri\",\"Manufacturing (Default)\":\"İmalat (Varsayılan)\",\"Construction (AEC)\":\"İnşaat (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"Tasarım İş Birliği\",\"Default Viewer settings\":\"Varsayılan Görüntüleyici ayarları\",\"A common set of preferences designed for the Construction industry\":\"İnşaat sektörü için tasarlanan yaygın tercihler\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"Autodesk Navisworks masaüstü uygulamasına benzer bir kullanıcı deneyimi sunar\",\"Description not available\":\"Açıklama mevcut değil\",\"User experience that matches Design Collaboration\":\"Tasarım İş Birliği ile eşleşen kullanıcı deneyimi\"}");

/***/ }),

/***/ "./res/locales/zh-HANS/nobundle-profiles.loc.json":
/*!********************************************************!*\
  !*** ./res/locales/zh-HANS/nobundle-profiles.loc.json ***!
  \********************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hans\",\"@@context\":\"查看器配置文件\",\"Profiles\":\"配置文件\",\"Viewer Profiles\":\"查看器配置文件\",\"Manufacturing (Default)\":\"制造(默认)\",\"Construction (AEC)\":\"建筑(AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"设计协作\",\"Default Viewer settings\":\"默认查看器设置\",\"A common set of preferences designed for the Construction industry\":\"为建筑行业设计的一组通用首选项\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"提供与 Autodesk Navisworks 桌面应用程序类似的用户体验\",\"Description not available\":\"说明不可用\",\"User experience that matches Design Collaboration\":\"与“设计协作”匹配的用户体验\"}");

/***/ }),

/***/ "./res/locales/zh-HANT/nobundle-profiles.loc.json":
/*!********************************************************!*\
  !*** ./res/locales/zh-HANT/nobundle-profiles.loc.json ***!
  \********************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-Hant\",\"@@context\":\"檢視器紀要\",\"Profiles\":\"紀要\",\"Viewer Profiles\":\"檢視器紀要\",\"Manufacturing (Default)\":\"製造 (預設)\",\"Construction (AEC)\":\"營造 (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"設計協同合作\",\"Default Viewer settings\":\"預設檢視器設定\",\"A common set of preferences designed for the Construction industry\":\"一組專門針對營造業設計的常用偏好設定\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"提供與 Autodesk Navisworks 桌面應用程式類似的使用者體驗\",\"Description not available\":\"描述無法使用\",\"User experience that matches Design Collaboration\":\"符合設計協同合作的使用者體驗\"}");

/***/ }),

/***/ "./res/locales/zh-HK/nobundle-profiles.loc.json":
/*!******************************************************!*\
  !*** ./res/locales/zh-HK/nobundle-profiles.loc.json ***!
  \******************************************************/
/*! exports provided: @@locale, @@context, Profiles, Viewer Profiles, Manufacturing (Default), Construction (AEC), Navisworks, Design Collaboration, Default Viewer settings, A common set of preferences designed for the Construction industry, Provides a user experience similar to Autodesk Navisworks desktop application, Description not available, User experience that matches Design Collaboration, default */
/***/ (function(module) {

module.exports = JSON.parse("{\"@@locale\":\"zh-hk\",\"@@context\":\"檢視器設定檔案\",\"Profiles\":\"設定檔案\",\"Viewer Profiles\":\"檢視器設定檔案\",\"Manufacturing (Default)\":\"製造 (預設)\",\"Construction (AEC)\":\"建築 (AEC)\",\"Navisworks\":\"Navisworks\",\"Design Collaboration\":\"設計協作\",\"Default Viewer settings\":\"預設「檢視器」設定\",\"A common set of preferences designed for the Construction industry\":\"一系列常見的偏好設定，專為建造業而設\",\"Provides a user experience similar to Autodesk Navisworks desktop application\":\"提供與 Autodesk Navisworks 桌面應用程式類似的使用者體驗\",\"Description not available\":\"沒有提供描述\",\"User experience that matches Design Collaboration\":\"符合「設計協作」的使用者體驗\"}");

/***/ })

/******/ });
//# sourceMappingURL=ProfileUi.js.map