/*!
 * LMV v7.9.0
 * 
 * Copyright 2019 Autodesk, Inc.
 * All rights reserved.
 * 
 * This computer source code and related instructions and comments are the
 * unpublished confidential and proprietary information of Autodesk, Inc.
 * and are protected under Federal copyright and state trade secret law.
 * They may not be disclosed to, copied or used by any third party without
 * the prior written consent of Autodesk, Inc.
 * 
 * Autodesk Forge Viewer Usage Limitations:
 * 
 * The Autodesk Forge viewer can only be used to view files generated by
 * Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be
 * delivered from an Autodesk hosted URL.
 */
Autodesk.Extensions.webVR =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = "./extensions/webVR/webVR.js");
/******/ })
/************************************************************************/
/******/ ({

/***/ "./extensions/webVR/StereoRenderContext.js":
/*!*************************************************!*\
  !*** ./extensions/webVR/StereoRenderContext.js ***!
  \*************************************************/
/*! exports provided: StereoRenderContext */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "StereoRenderContext", function() { return StereoRenderContext; });
var av = Autodesk.Viewing;

function StereoRenderContext(_vrDisplay, camera, HUD, toolConfig) {

  var avp = Autodesk.Viewing.Private;

  var _vrDisplay; //holds the VR device object info supported by webVR
  var _context;
  var _renderer;
  var _w, _h;
  var pose;
  var RADIUS = 2.1;


  var leftEyeParams = _vrDisplay.getEyeParameters("left");
  var rightEyeParams = _vrDisplay.getEyeParameters("right");
  var eyeTranslationL = new THREE.Vector3();
  var eyeTranslationR = new THREE.Vector3();
  var cameraL = new THREE.PerspectiveCamera();
  var cameraR = new THREE.PerspectiveCamera();

  var _standing = false;
  var _userHeight = 0.5;
  var _scale = 10.0 * _vrDisplay.modelScaleFactor; // scale factor 10.0 of a 'toy house'.  Make a UI for this.

  var frameData = null;

  var that = this;
  this.init = function (renderer, width, height) {
    _context = new avp.RenderContext();
    _renderer = renderer;

    var _window = that.getWindow();
    var dpr = _window.devicePixelRatio * 1.5;
    _w = _vrDisplay.getEyeParameters("left").renderWidth * 2 / dpr;
    _h = _vrDisplay.getEyeParameters("right").renderHeight / dpr;

    this.settings = _context.settings;
    _context.init(_renderer, _w, _h);
    eyeTranslationL.fromArray(leftEyeParams.offset);
    eyeTranslationR.fromArray(rightEyeParams.offset);

    frameData = new VRFrameData();

    if (camera.worldup && camera.worldup.z == 1)
    toolConfig.webVR_orbitModel = false; // model is not fusion, switch to walkthrough mode
  };

  this.modeFusion = function (pose) {
    var position = new THREE.Vector3(0, 0, 1);
    position.applyQuaternion(new THREE.Quaternion().fromArray(pose.orientation)).multiplyScalar(_scale * RADIUS);
    camera.position.set(position.x, position.y, position.z);
    camera.lookAt(_vrDisplay.target); // compute quaternion
    //camera.quaternion.z = pose.orientation[2];  // roll camera based on head tilt
    camera.up.set(0, 1, 0); // override touch events
  };

  this.modeWalkthrough = function (pose) {
    if (pose.orientation && pose.orientation[1] != 0)
    camera.quaternion.fromArray(pose.orientation);
    if (pose.position && pose.position[0] != 0)
    camera.position.fromArray(pose.position).multiplyScalar(_scale);

    // adjust for alternate worldup
    if (camera.worldup && camera.worldup.z == 1) {
      camera.quaternion.setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI / 2);
      camera.quaternion.multiply(new THREE.Quaternion().fromArray(pose.orientation));
      if (pose.position && pose.position[0] != 0)
      camera.position.set(camera.position.x, -camera.position.z, camera.position.y);
    }
    // adjust camera target
    var lookAtDir = new THREE.Vector3(0, 0, -1);
    lookAtDir.applyQuaternion(camera.quaternion);
    camera.target = camera.position.clone().add(lookAtDir.clone().multiplyScalar(10));
  };

  this.updateCamera = function () {
    if (!(_vrDisplay && _vrDisplay._isPresenting)) return;

    // set position and orientation
    _vrDisplay.depthNear = camera.near;
    _vrDisplay.depthFar = camera.far;
    _vrDisplay.getFrameData(frameData);

    pose = frameData.pose;
    if (!pose.orientation) return;

    if (toolConfig.webVR_orbitModel)
    this.modeFusion(pose);else

    this.modeWalkthrough(pose);

    if (_standing) //MB: perhaps add configurable user height option in settings menu
      camera.position.setY(camera.position.y + _userHeight);
    //_vrDisplay.stageParameters.sittingToStandingTransform;

    camera.updateMatrixWorld();
    camera.dirty = true;

    getStereoCamera(camera, frameData, true, false, cameraL);
    getStereoCamera(camera, frameData, false, false, cameraR);

    if (HUD) {

      HUD.camera = camera.clone();
      HUD.camera.position.set(0, 0, 0);

      getStereoCamera(camera, frameData, true, true, HUD.cameraL);
      getStereoCamera(camera, frameData, false, true, HUD.cameraR);
    }

    return { L: cameraL, R: cameraR, C: camera };
  };

  this.beginScene = function (prototypeScene, _camera, customLights, needClear) {
    _context.beginScene(prototypeScene, camera, customLights, needClear);
  };


  this.renderScenePart = function (scene, want_colorTarget, want_saoTarget, want_idTarget, updateLights) {

    var halfW = _w / 2;

    _renderer.setViewport(0, 0, halfW, _h);
    _context.setCamera(cameraL);
    _context.renderScenePart(scene, true, false, false, false);

    _renderer.setViewport(halfW, 0, halfW, _h);
    _context.setCamera(cameraR);
    _context.renderScenePart(scene, true, false, false, false);

    if (HUD) {

      _renderer.setViewport(0, 0, halfW, _h);
      _context.setCamera(HUD.cameraL);
      _context.renderScenePart(HUD.scene, true, false, false, false);

      _renderer.setViewport(halfW, 0, halfW, _h);
      _context.setCamera(HUD.cameraR);
      _context.renderScenePart(HUD.scene, true, false, false, false);
    }

    _renderer.setViewport(0, 0, _w, _h);
  };

  this.sceneDirty = function (camera, bbox) {
    _context.sceneDirty(camera, bbox);
  };

  //TODO: get rid of this and combine it with composeFinalFrame
  this.endScene = function () {
    _context.endScene();
  };

  this.clearAllOverlays = function () {};

  this.renderOverlays = function (overlays) {
    // disabled, due to performance hit on mobile
  };

  this.composeFinalFrame = function (skipAOPass, skipPresent) {
    _context.composeFinalFrame(true, skipPresent);
    if (_vrDisplay._isPresenting) _vrDisplay.submitFrame();
  };

  this.cleanup = function () {
    _context.cleanup();
  };

  this.setSize = function (w, h, force) {
    _w = w;
    _h = h;
    _context.setSize(_w, _h, force);
  };

  this.getMaxAnisotropy = function () {
    return _context.getMaxAnisotropy();
  };

  this.hasMRT = function () {
    return _context.hasMRT();
  };

  this.initPostPipeline = function (useSAO, useFXAA, useIDBuffer) {
    _context.initPostPipeline(false, false, false);
  };

  this.setClearColors = function (colorTop, colorBot) {
    _context.setClearColors(colorTop, colorBot);
  };

  this.setAOOptions = function (radius, intensity) {
    _context.setAOOptions(radius, intensity);
  };

  this.getAORadius = function () {
    return _context.getAORadius();
  };

  this.getAOIntensity = function () {
    return _context.getAOIntensity();
  };

  this.setTonemapExposureBias = function (bias) {
    _context.setTonemapExposureBias(bias);
  };

  this.getExposureBias = function () {
    return _context.getExposureBias();
  };

  this.setTonemapMethod = function (value) {
    _context.setTonemapMethod(value);
  };

  this.getToneMapMethod = function () {
    return _context.getToneMapMethod();
  };

  this.toggleTwoSided = function (isTwoSided) {
    _context.toggleTwoSided(isTwoSided);
  };

  this.enter2DMode = function (idMaterial) {
    _context.enter2DMode(idMaterial);
  };

  this.getAOEnabled = function () {
    return false;
  };

  this.idAtPixel = function (vpx, vpy) {
    // idAtPixel not implemented in stereo context
    return 0;
  };

  this.setHighlightLights = function (customLights) {
    // Nothing
  };

  this.setStencilEnabled = function (enabled) {
    // Nothing
  };

  this.setEdgeColor = function (colorAsVec4) {
    // Nothing
  };

  this.overlayUpdate = function (highResTimer) {
    _context.overlayUpdate(highResTimer);
  };

  this.rolloverObjectViewport = function (vpx, vpy) {};

  this.screenCapture = function () {
    console.warn("Screen capture not implemented by stereo render context");
    return null;
  };

  this.setUnitScale = function (metersPerUnit) {
    _context.setUnitScale(metersPerUnit);
  };

  this.getUnitScale = function () {
    return _context.getUnitScale();
  };

  // TODO_NOP: hack expose colorTarget so shadow/reflection can draw into
  this.getColorTarget = function () {
    return null;
  };

  function getStereoCamera(camera, frameData, leftEye, fixed, result) {

    // Copy world transform and move camera to origin if it's fixed.
    camera.matrixWorld.decompose(result.position, result.quaternion, result.scale);
    if (fixed) {
      result.position.set(0, 0, 0);
    }

    // Translate eye bye scene scaling.
    result.translateOnAxis(leftEye ? eyeTranslationL : eyeTranslationR, _scale);

    // Copy projection matrix.
    result.projectionMatrix.elements =
    leftEye ? frameData.leftProjectionMatrix : frameData.rightProjectionMatrix;

  }
};

av.GlobalManagerMixin.call(StereoRenderContext.prototype);

/***/ }),

/***/ "./extensions/webVR/VR.css":
/*!*********************************!*\
  !*** ./extensions/webVR/VR.css ***!
  \*********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {


var content = __webpack_require__(/*! !../../node_modules/css-loader!../../node_modules/sass-loader/dist/cjs.js!./VR.css */ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/webVR/VR.css");

if(typeof content === 'string') content = [[module.i, content, '']];

var transform;
var insertInto;



var options = {"hmr":true}

options.transform = transform
options.insertInto = undefined;

var update = __webpack_require__(/*! ../../node_modules/style-loader/lib/addStyles.js */ "./node_modules/style-loader/lib/addStyles.js")(content, options);

if(content.locals) module.exports = content.locals;

if(false) {}

/***/ }),

/***/ "./extensions/webVR/cursorVR.js":
/*!**************************************!*\
  !*** ./extensions/webVR/cursorVR.js ***!
  \**************************************/
/*! exports provided: WebVrCursor */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "WebVrCursor", function() { return WebVrCursor; });
function WebVrCursor(viewerImpl, autocam, _scale, USE_YUP) {

  var STANDING_HEIGHT = 5;
  var DEFAULT_GREEN = 0x0022aa;
  var DEFAULT_RED = 0xaa0022;
  var _cursor;
  var hit;

  var USE_ANGLECURSOR = true;

  this.init = function (scene) {
    // Create Cursor
    _cursor = new THREE.Object3D();
    _cursor.scale.set(0.25, 0.25, 1);
    _cursor.add(new THREE.Mesh(
    new THREE.RingGeometry(.6, 1, 32, 32),
    new THREE.MeshBasicMaterial({
      color: DEFAULT_RED,
      depthTest: false,
      side: THREE.DoubleSide })));



    scene.add(_cursor);
  };

  this.update = function (camera, hud) {

    var dist;

    // set cursor red, not available to move or to green otherwise
    hit = viewerImpl.hitTestViewport(new THREE.Vector3(), false);
    if (hit) {
      _cursor.children[0].material.color.setHex(DEFAULT_GREEN);
      dist = hit.intersectPoint.clone().sub(camera.position).length();
    } else {
      _cursor.children[0].material.color.setHex(DEFAULT_RED);
      dist = (camera.far - camera.near) * 0.5;
    }

    var matrix = new THREE.Matrix4();
    matrix.extractRotation(hud.camera.matrixWorld);

    var direction = new THREE.Vector3(0, 0, -1);
    direction = matrix.multiplyVector3(direction);
    direction.multiplyScalar(dist);

    _cursor.scale.set(_scale, _scale, _scale);
    _cursor.position.copy(direction);
    _cursor.lookAt(hud.camera.position);

    // orientate the cursor angle with the terrain and position it's distance
    // this technique reduces cursor jitter
    if (USE_ANGLECURSOR) {




    } //        _cursor.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), hit.face.normal.clone().normalize());
    //        _cursor.quaternion.multiply(camera.quaternion);
    //        _cursor.quaternion.inverse();
    //_cursor.quaternion.y = 0;
    // if (Math.round(hit.face.normal.x*10)/10 == -0.7) {}
  };
  this.onClick = function () {
    if (!hit) return;
    var hitpt = hit.intersectPoint;
    var hitangle = hit.face.normal;
    if (USE_YUP)
    hitpt.z += STANDING_HEIGHT;else

    hitpt.y += STANDING_HEIGHT;

    var view = autocam.getCurrentView();
    view.position.copy(hitpt);

    // optional: force walkthrough pivot effect, using existing nav controls (used within desktop browser)
    view.center.set(hitpt.x + 0.000001, hitpt.y, hitpt.z);
    view.pivot.set(hitpt.x, hitpt.y, hitpt.z);

    autocam.goToView(view);
  };
};

/***/ }),

/***/ "./extensions/webVR/menuVR.js":
/*!************************************!*\
  !*** ./extensions/webVR/menuVR.js ***!
  \************************************/
/*! exports provided: WebVrMenu */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "WebVrMenu", function() { return WebVrMenu; });
function WebVrMenu(_scale) {
  var DEFAULT_COLOR = 0xffffff; // default color of menu items
  var YOFFSET = -12;
  var DEPTH = -14;

  var _menu, menuAnchor, menuRotOffset;
  var prevMenuIdx;

  this.init = function (scene) {
    if (_menu) return;

    var getResourceUrl = Autodesk.Viewing.Private.getResourceUrl;
    var imgLoader = THREE.ImageUtils;
    imgLoader.crossOrigin = 'anonymous';
    var BASE_URL = "res/webvr/";
    var icons = [
    "back.png",
    "zoomin.png",
    "zoomout.png",
    "next.png"];


    // position the menu so it is floating at waist level in front of the user
    _menu = new THREE.Object3D();
    menuAnchor = new THREE.Object3D();
    var menuOffset = new THREE.Object3D();
    menuOffset.position.set(0, YOFFSET, DEPTH);
    menuOffset.rotateX(-0.6);

    // create each menu item
    function createMenuItem(url, xScale, opacity) {
      return new THREE.Mesh(
      new THREE.PlaneBufferGeometry(xScale, 1),
      new THREE.MeshBasicMaterial({
        map: imgLoader.loadTexture(getResourceUrl(url)),
        color: DEFAULT_COLOR,
        side: THREE.DoubleSide,
        depthTest: false,
        transparent: true,
        opacity: opacity }));


    }
    // horizontal menu layout
    for (var i = 0; i < icons.length; i++) {
      var item = createMenuItem(BASE_URL + icons[i], 2, 1);
      item.position.set(2 * (i - icons.length / 2), 0, 0.1);
      item.scale.set(0.94, 0.94, 0.1);
      menuOffset.add(item);
    };
    // add wide transparent black background for menu container
    var menuBg = createMenuItem(BASE_URL + "bg.png", 48, 0.1);
    menuOffset.add(menuBg);
    menuAnchor.add(menuOffset);
    _menu.add(menuAnchor);

    _menu.visible = true;
    scene.add(_menu);
  };

  this.onVisible = function (camera) {
    menuAnchor.rotation.y = camera.rotation._z;
    menuRotOffset = -_menu.quaternion.y;
  };

  this.update = function (camera) {
    // move menu based on camera orientation only
    var cam = camera.quaternion.clone().inverse();
    _menu.quaternion.copy(cam);

    // look down for menu to appear in front of user
    var tmp = _menu.visible;
    _menu.visible = _menu.quaternion.x > 0.26 && _menu.quaternion.x < 0.4;
    if (!tmp && _menu.visible)
    this.onVisible(camera);
    /*
                            // fade in/out
                            _menu.traverse(function(node) {
                                if (node.material)
                                    node.material.opacity = (_menu.quaternion.x * _menu.quaternion.x) - 0.1;
                            });
                            */
    if (prevMenuIdx >= 0 && prevMenuIdx < 4) {
      _menu.children[0].children[0].children[prevMenuIdx].material.color.setHex(DEFAULT_COLOR);
    }
    prevMenuIdx = Math.floor((menuRotOffset + _menu.quaternion.y + 0.14) * 4.54 * 4);
    if (prevMenuIdx >= 0 && prevMenuIdx < 4) {
      _menu.children[0].children[0].children[prevMenuIdx].material.color.setHex(0xaaaaff);
    }
  };

  this.onClick = function () {
    // handle menu click
  };
};

/***/ }),

/***/ "./extensions/webVR/webVR.js":
/*!***********************************!*\
  !*** ./extensions/webVR/webVR.js ***!
  \***********************************/
/*! exports provided: VRExtension */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "VRExtension", function() { return VRExtension; });
/* harmony import */ var _webVrTool__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./webVrTool */ "./extensions/webVR/webVrTool.js");
/* harmony import */ var _VR_css__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./VR.css */ "./extensions/webVR/VR.css");
/* harmony import */ var _VR_css__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_VR_css__WEBPACK_IMPORTED_MODULE_1__);


 // REQUIRED !!

//
// WebVR extension (both Toolbar icon and mode)
//

'use strict';

/**
               * First Person navigation tool, similar to those found in videogames.
               *
               * It will also replace the default walk tool button when {@link Autodesk.Viewing.GuiViewer3D} is present.
               * @constructor
               * @see {@link Autodesk.Viewing.Extension} for common inherited methods.
               * @param {Autodesk.Viewing.Viewer3D} viewer - Viewer instance.
               * @param {object} options - Not used.
               */

function VRExtension(viewer, options) {
  Autodesk.Viewing.Extension.call(this, viewer, options);
  this.name = 'webvr';
};

/**
    * Static function internally used that provides info on what are the configuration options
    * available to this extension.
    * @private
    */
VRExtension.populateDefaultOptions = function (options) {
  // Use double-dashes to prevent flag from being active by default while still surfacing them out (cuz why not)
  options.experimental.push('--webVR_orbitModel');
  options.experimental.push('--webVR_cursor');
  options.experimental.push('--webVR_menu');
};

VRExtension.prototype = Object.create(Autodesk.Viewing.Extension.prototype);
VRExtension.prototype.constructor = VRExtension;

var proto = VRExtension.prototype;

proto.load = function () {
  var self = this;
  var _vrDisplay = null;
  var avp = Autodesk.Viewing.Private;

  // check if browser supports webVR1.1 natively, if not, load polyfill
  avp.loadDependency('VRFrameData', 'webvr-polyfill.min.js', function () {
    navigator.getVRDisplays().then(function (displays) {
      if (displays.length > 0) {
        _vrDisplay = displays[0];
        if (_vrDisplay.capabilities.canPresent) {

          // VR detected, add the 'VR button'
          var viewer = self.viewer;
          var toolbar = viewer.getToolbar();
          var avu = Autodesk.Viewing.UI;

          // Register tool
          self.tool = new _webVrTool__WEBPACK_IMPORTED_MODULE_0__["VRTool"](viewer, self, _vrDisplay);
          viewer.toolController.registerTool(self.tool);
          self.createUI(toolbar);

          // Register listeners
          self.onToolChanged = function (e) {
            var vrToolActive = e.toolName === 'vr' && e.active;
            var state = vrToolActive ? avu.Button.State.ACTIVE : avu.Button.State.INACTIVE;
            self.vrToolButton && self.vrToolButton.setState(state);
          };
          viewer.addEventListener(Autodesk.Viewing.TOOL_CHANGE_EVENT, self.onToolChanged);
          return;
        }
      }
      avp.logger.warn('Attempted to load WebVR extension, but WebVR is not supported.');
    });
  });

  return true;
};

proto.createUI = function (toolbar) {
  var self = this;
  var viewer = this.viewer;
  var avu = Autodesk.Viewing.UI;
  var navTools = toolbar.getControl(Autodesk.Viewing.TOOLBAR.NAVTOOLSID);

  // Create a button for the VR Tool. 
  this.vrToolButton = new avu.Button('toolbar-vrTool');
  this.vrToolButton.setGlobalManager(this.globalManager);
  this.vrToolButton.setToolTip('Enable VR mode');
  this.vrToolButton.setIcon("adsk-icon-webvr");
  this.vrToolButton.onClick = function (e) {
    var state = self.vrToolButton.getState();
    if (state === avu.Button.State.INACTIVE) {
      self.activate();
    } else if (state === avu.Button.State.ACTIVE) {
      self.deactivate();
    }
  };

  var cameraSubmenuTool = navTools.getControl('toolbar-cameraSubmenuTool');
  if (cameraSubmenuTool) {
    navTools.addControl(this.vrToolButton, {
      index: navTools.indexOf(cameraSubmenuTool.getId()) });

  } else {
    navTools.addControl(this.vrToolButton);
  }
};

proto.unload = function () {
  var viewer = this.viewer;

  // Remove listeners
  if (this.onToolChanged) {
    viewer.removeEventListener(Autodesk.Viewing.TOOL_CHANGE_EVENT, this.onToolChanged);
    this.onToolChanged = undefined;
  }

  // Remove the UI
  var toolbar = viewer.getToolbar();
  if (toolbar && this.vrToolButton) {
    this.vrToolButton.removeFromParent();
  }
  this.vrToolButton = null;

  // Deregister tool
  if (this.tool) {
    viewer.toolController.deregisterTool(this.tool);
    this.tool = null;
  }

  return true;
};

proto.activate = function () {
  if (!this.activeStatus) {
    this.viewer.setActiveNavigationTool("vr");
    this.activeStatus = true;
  }
  return true;
};

proto.deactivate = function () {
  if (this.activeStatus) {
    this.viewer.setActiveNavigationTool();
    this.activeStatus = false;
  }
  return true;
};

Autodesk.Viewing.theExtensionManager.registerExtension('Autodesk.Viewing.WebVR', VRExtension);

/***/ }),

/***/ "./extensions/webVR/webVrTool.js":
/*!***************************************!*\
  !*** ./extensions/webVR/webVrTool.js ***!
  \***************************************/
/*! exports provided: VRTool */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "VRTool", function() { return VRTool; });
/* harmony import */ var _StereoRenderContext__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./StereoRenderContext */ "./extensions/webVR/StereoRenderContext.js");
/* harmony import */ var _menuVR__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./menuVR */ "./extensions/webVR/menuVR.js");
/* harmony import */ var _cursorVR__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./cursorVR */ "./extensions/webVR/cursorVR.js");




var av = Autodesk.Viewing;

function VRTool(viewer, vrExtension, _vrDisplay) {
  this.setGlobalManager(viewer.globalManager);

  var _canvas = viewer.canvas;
  var _navapi = viewer.navigation;
  var _camera = _navapi.getCamera();
  var _stereoRenderContext, _HUD;
  var avp = Autodesk.Viewing.Private;
  var toolConfig = {
    webVR_cursor: avp.isExperimentalFlagEnabled('webVR_cursor', vrExtension.options),
    webVR_menu: avp.isExperimentalFlagEnabled('webVR_menu', vrExtension.options),
    webVR_orbitModel: avp.isExperimentalFlagEnabled('webVR_orbitModel', vrExtension.options) };


  // VR state
  var _names = ["vr"];
  var _isActive = false;
  var _isPresenting = false;

  var that = this;

  this.activate = function (name) {
    _isActive = true;

    // prepare camera for VR mode
    viewer.impl.toggleGroundShadow(false);
    viewer.impl.toggleGroundReflection(false);
    _navapi.toPerspective();
    _navapi.setVerticalFov(75, true); // same as firstPerson FOV
    _navapi.setRequestFitToView(true);

    // Calculate a model scale factor based on the model bounds.
    var boundsSize = viewer.model.getBoundingBox().size();
    _vrDisplay.target = viewer.model.getBoundingBox().center();
    _navapi.setPivotPoint(_vrDisplay.target, true, true);
    _navapi.setView(_camera.position, _vrDisplay.target);
    _navapi.setCameraUpVector(new THREE.Vector3(0, 1, 0));
    _vrDisplay.modelScaleFactor = Math.max(Math.min(Math.min(boundsSize.x, boundsSize.y), boundsSize.z) / 10.0, 0.0001);

    // Request webVR full screen
    _vrDisplay._isPresenting = av.isMobileDevice();
    _vrDisplay.requestPresent([{
      source: _canvas }]).
    then(function () {
      viewer.impl.setLmvDisplay(_vrDisplay);
      _vrDisplay._isPresenting = true;
      //viewer.resize(viewer.canvas.clientWidth, viewer.canvas.clientHeight);
    });
    _vrDisplay.resetPose();

    // handle fullscreen on mobile/cardboard differently.  Add 'exit VR' button and hide toolbar
    if (av.isMobileDevice()) {
      var self = this;
      showHUD(false);
      viewer.setScreenMode(Autodesk.Viewing.ScreenMode.kFullScreen);
      _canvas.addEventListener("dblclick", function () {
        if (_isActive)
        viewer.setActiveNavigationTool();
      });
    }
    if (toolConfig.webVR_cursor || toolConfig.webVR_menu)
    _HUD = this.initHUD();

    _stereoRenderContext = new _StereoRenderContext__WEBPACK_IMPORTED_MODULE_0__["StereoRenderContext"](_vrDisplay, _camera, _HUD, toolConfig);
    _stereoRenderContext.setGlobalManager(this.globalManager);
    viewer.impl.setUserRenderContext(_stereoRenderContext);
  };

  this.initHUD = function () {
    // Create HUD overlay scene and camera
    var scene = new THREE.Scene();
    var HUDCamera = _camera.clone();

    //    new THREE.PerspectiveCamera(_camera.fov, _camera.aspect * 0.5, 0.1, 2000);
    //    HUDcamera.position.set(0, 0, 0);
    //    scene.add(HUDcamera);

    if (toolConfig.webVR_menu) {
      // Add menu and cursor to the HUD scene
      var menu = new _menuVR__WEBPACK_IMPORTED_MODULE_1__["WebVrMenu"](_vrDisplay.modelScaleFactor);
      menu.init(scene);
    }

    if (toolConfig.webVR_cursor) {
      var camYup = _camera.worldup && _camera.worldup.z == 1;
      var cursor = new _cursorVR__WEBPACK_IMPORTED_MODULE_2__["WebVrCursor"](viewer.impl, viewer.autocam, _vrDisplay.modelScaleFactor, camYup);
      cursor.init(scene);
      _canvas.addEventListener("click", cursor.onClick);
    }

    return {
      scene: scene,
      camera: HUDCamera,
      cameraL: HUDCamera.clone(),
      cameraR: HUDCamera.clone(),
      menu: menu,
      cursor: cursor,
      IPD: 1.2 };

  };

  this.update = function (timeStamp) {

    if (!_vrDisplay) {
      return true;
    }

    if (_isPresenting && !_vrDisplay.isPresenting && _isActive) {
      viewer.setActiveNavigationTool();
    }
    _isPresenting = _vrDisplay.isPresenting;

    var cam = _stereoRenderContext.updateCamera();
    if (!_HUD) return true;

    if (toolConfig.webVR_cursor)
    _HUD.cursor.update(cam.C, _HUD);

    if (toolConfig.webVR_menu)
    _HUD.menu.update(_HUD.camera);

    return true;
  };

  this.deactivate = function (name) {
    if (_vrDisplay) {
      if (_vrDisplay.isPresenting)
      _vrDisplay.exitPresent(); // Stops VR mode
      _vrDisplay._isPresenting = false;
    }
    _isActive = false;
    showHUD(true);

    viewer.impl.setUserRenderContext(null);
    viewer.setScreenMode(Autodesk.Viewing.ScreenMode.kNormal);
    viewer.resize(viewer.canvas.clientWidth, viewer.canvas.clientHeight);
    viewer.autocam.resetHome();
    if (_HUD && toolConfig.webVR_cursor)
    _canvas.removeEventListener("click", _HUD.cursor.onClick);
  };

  var showHUD = function showHUD(isVisible) {
    // Show/hide the toolbar (don't show when in mobile)
    viewer.getExtension("Autodesk.ViewCubeUi", function (ext) {
      ext.setVisible(isVisible);
      ext.displayViewCube(isVisible && !av.isMobileDevice());
    });

    var _document = that.getDocument();
    var tbar = _document.getElementsByClassName('adsk-toolbar');
    if (tbar.length > 0) {// HACK: Assume only 1
      if (tbar[0] !== '')
      tbar[0].style.display = isVisible ? 'block' : 'none';
    }
  };

  this.isActive = function () {
    return _isActive;
  };

  this.getNames = function () {
    return _names;
  };

  this.getName = function () {
    return _names[0];
  };
};

av.GlobalManagerMixin.call(VRTool.prototype);

/***/ }),

/***/ "./node_modules/css-loader/index.js!./node_modules/sass-loader/dist/cjs.js!./extensions/webVR/VR.css":
/*!**************************************************************************************************!*\
  !*** ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./extensions/webVR/VR.css ***!
  \**************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../../node_modules/css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, "/**\n * Toolbar - VR Tool\n */\n.adsk-icon-webvr {\n  background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAAAc1JREFUSA3tVL2KwkAQnsSgpYKCtaIgCNaCja0gYiHY6Qv4BsFnsLLwFawsLSy0VBQbLQT/CxFEsFIUdW4ndy4uGy9y3jWHAyH5Zr6ZyXyzCcDbLBRQWBwtOC+FtUwmA4lEAhB/t4+qqrDb7QA6nQ6r/XemvjT/E8kqe/cnaD+nmE5wOByg2+3CcDi0rEw6t9ttmEwm5lwWFBawXq8xlUqh3W5Hp9OJuq7j6XQSODcwGAwwGo2ipmno9XqxUqncQvxO3Tmgh2KxSJrxy2azYaPREDgErtcrZrNZzqMct9uNo9FI4EoSTadTYdTL5QKr1UrwEWANYLFYCP7tdgubzUbwSQ3ou3A4HJwUCAQgFosZ+Hw+AxUhY5MBce8tHo9DOBy+d4EkEY1erVYxnU5jPp/HXq9njMyWiblcDkOhEJZKJcN3PB6xXC5jMpnEQqGAs9lMkIeA1EBifDlogezVjMvlciEt+BmTJBLn+0Skd61W4yE6mvV6nePvHlTS0sqWyyX0+32B1mw2BfwIaOPxGCKRyMOfnaIo0Gq1gH0fQg1qyI4k+P1+01zK2+/3oHg8HvT5fKYkqkjE+XwuHT+KBYNBYPswzb01IN7b/rkCH+c1AQdiGKHcAAAAAElFTkSuQmCC\");\n  background-repeat: no-repeat;\n  background-position: center; }\n\n/* On fullscreen viewer canvas size is wrong on some devices, this rule fixes it*/\n.webvr-polyfill-fullscreen-wrapper canvas {\n  width: 100% !important;\n  height: 100% !important; }\n", ""]);

// exports


/***/ }),

/***/ "./node_modules/css-loader/lib/css-base.js":
/*!*************************************************!*\
  !*** ./node_modules/css-loader/lib/css-base.js ***!
  \*************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
// css base code, injected by the css-loader
module.exports = function(useSourceMap) {
	var list = [];

	// return the list of modules as css string
	list.toString = function toString() {
		return this.map(function (item) {
			var content = cssWithMappingToString(item, useSourceMap);
			if(item[2]) {
				return "@media " + item[2] + "{" + content + "}";
			} else {
				return content;
			}
		}).join("");
	};

	// import a list of modules into the list
	list.i = function(modules, mediaQuery) {
		if(typeof modules === "string")
			modules = [[null, modules, ""]];
		var alreadyImportedModules = {};
		for(var i = 0; i < this.length; i++) {
			var id = this[i][0];
			if(typeof id === "number")
				alreadyImportedModules[id] = true;
		}
		for(i = 0; i < modules.length; i++) {
			var item = modules[i];
			// skip already imported module
			// this implementation is not 100% perfect for weird media query combinations
			//  when a module is imported multiple times with different media queries.
			//  I hope this will never occur (Hey this way we have smaller bundles)
			if(typeof item[0] !== "number" || !alreadyImportedModules[item[0]]) {
				if(mediaQuery && !item[2]) {
					item[2] = mediaQuery;
				} else if(mediaQuery) {
					item[2] = "(" + item[2] + ") and (" + mediaQuery + ")";
				}
				list.push(item);
			}
		}
	};
	return list;
};

function cssWithMappingToString(item, useSourceMap) {
	var content = item[1] || '';
	var cssMapping = item[3];
	if (!cssMapping) {
		return content;
	}

	if (useSourceMap && typeof btoa === 'function') {
		var sourceMapping = toComment(cssMapping);
		var sourceURLs = cssMapping.sources.map(function (source) {
			return '/*# sourceURL=' + cssMapping.sourceRoot + source + ' */'
		});

		return [content].concat(sourceURLs).concat([sourceMapping]).join('\n');
	}

	return [content].join('\n');
}

// Adapted from convert-source-map (MIT)
function toComment(sourceMap) {
	// eslint-disable-next-line no-undef
	var base64 = btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap))));
	var data = 'sourceMappingURL=data:application/json;charset=utf-8;base64,' + base64;

	return '/*# ' + data + ' */';
}


/***/ }),

/***/ "./node_modules/style-loader/lib/addStyles.js":
/*!****************************************************!*\
  !*** ./node_modules/style-loader/lib/addStyles.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/

var stylesInDom = {};

var	memoize = function (fn) {
	var memo;

	return function () {
		if (typeof memo === "undefined") memo = fn.apply(this, arguments);
		return memo;
	};
};

var isOldIE = memoize(function () {
	// Test for IE <= 9 as proposed by Browserhacks
	// @see http://browserhacks.com/#hack-e71d8692f65334173fee715c222cb805
	// Tests for existence of standard globals is to allow style-loader
	// to operate correctly into non-standard environments
	// @see https://github.com/webpack-contrib/style-loader/issues/177
	return window && document && document.all && !window.atob;
});

var getTarget = function (target, parent) {
  if (parent){
    return parent.querySelector(target);
  }
  return document.querySelector(target);
};

var getElement = (function (fn) {
	var memo = {};

	return function(target, parent) {
                // If passing function in options, then use it for resolve "head" element.
                // Useful for Shadow Root style i.e
                // {
                //   insertInto: function () { return document.querySelector("#foo").shadowRoot }
                // }
                if (typeof target === 'function') {
                        return target();
                }
                if (typeof memo[target] === "undefined") {
			var styleTarget = getTarget.call(this, target, parent);
			// Special case to return head of iframe instead of iframe itself
			if (window.HTMLIFrameElement && styleTarget instanceof window.HTMLIFrameElement) {
				try {
					// This will throw an exception if access to iframe is blocked
					// due to cross-origin restrictions
					styleTarget = styleTarget.contentDocument.head;
				} catch(e) {
					styleTarget = null;
				}
			}
			memo[target] = styleTarget;
		}
		return memo[target]
	};
})();

var singleton = null;
var	singletonCounter = 0;
var	stylesInsertedAtTop = [];

var	fixUrls = __webpack_require__(/*! ./urls */ "./node_modules/style-loader/lib/urls.js");

module.exports = function(list, options) {
	if (typeof DEBUG !== "undefined" && DEBUG) {
		if (typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
	}

	options = options || {};

	options.attrs = typeof options.attrs === "object" ? options.attrs : {};

	// Force single-tag solution on IE6-9, which has a hard limit on the # of <style>
	// tags it will allow on a page
	if (!options.singleton && typeof options.singleton !== "boolean") options.singleton = isOldIE();

	// By default, add <style> tags to the <head> element
        if (!options.insertInto) options.insertInto = "head";

	// By default, add <style> tags to the bottom of the target
	if (!options.insertAt) options.insertAt = "bottom";

	var styles = listToStyles(list, options);

	addStylesToDom(styles, options);

	return function update (newList) {
		var mayRemove = [];

		for (var i = 0; i < styles.length; i++) {
			var item = styles[i];
			var domStyle = stylesInDom[item.id];

			domStyle.refs--;
			mayRemove.push(domStyle);
		}

		if(newList) {
			var newStyles = listToStyles(newList, options);
			addStylesToDom(newStyles, options);
		}

		for (var i = 0; i < mayRemove.length; i++) {
			var domStyle = mayRemove[i];

			if(domStyle.refs === 0) {
				for (var j = 0; j < domStyle.parts.length; j++) domStyle.parts[j]();

				delete stylesInDom[domStyle.id];
			}
		}
	};
};

function addStylesToDom (styles, options) {
	for (var i = 0; i < styles.length; i++) {
		var item = styles[i];
		var domStyle = stylesInDom[item.id];

		if(domStyle) {
			domStyle.refs++;

			for(var j = 0; j < domStyle.parts.length; j++) {
				domStyle.parts[j](item.parts[j]);
			}

			for(; j < item.parts.length; j++) {
				domStyle.parts.push(addStyle(item.parts[j], options));
			}
		} else {
			var parts = [];

			for(var j = 0; j < item.parts.length; j++) {
				parts.push(addStyle(item.parts[j], options));
			}

			stylesInDom[item.id] = {id: item.id, refs: 1, parts: parts};
		}
	}
}

function listToStyles (list, options) {
	var styles = [];
	var newStyles = {};

	for (var i = 0; i < list.length; i++) {
		var item = list[i];
		var id = options.base ? item[0] + options.base : item[0];
		var css = item[1];
		var media = item[2];
		var sourceMap = item[3];
		var part = {css: css, media: media, sourceMap: sourceMap};

		if(!newStyles[id]) styles.push(newStyles[id] = {id: id, parts: [part]});
		else newStyles[id].parts.push(part);
	}

	return styles;
}

function insertStyleElement (options, style) {
	var target = getElement(options.insertInto)

	if (!target) {
		throw new Error("Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.");
	}

	var lastStyleElementInsertedAtTop = stylesInsertedAtTop[stylesInsertedAtTop.length - 1];

	if (options.insertAt === "top") {
		if (!lastStyleElementInsertedAtTop) {
			target.insertBefore(style, target.firstChild);
		} else if (lastStyleElementInsertedAtTop.nextSibling) {
			target.insertBefore(style, lastStyleElementInsertedAtTop.nextSibling);
		} else {
			target.appendChild(style);
		}
		stylesInsertedAtTop.push(style);
	} else if (options.insertAt === "bottom") {
		target.appendChild(style);
	} else if (typeof options.insertAt === "object" && options.insertAt.before) {
		var nextSibling = getElement(options.insertAt.before, target);
		target.insertBefore(style, nextSibling);
	} else {
		throw new Error("[Style Loader]\n\n Invalid value for parameter 'insertAt' ('options.insertAt') found.\n Must be 'top', 'bottom', or Object.\n (https://github.com/webpack-contrib/style-loader#insertat)\n");
	}
}

function removeStyleElement (style) {
	if (style.parentNode === null) return false;
	style.parentNode.removeChild(style);

	var idx = stylesInsertedAtTop.indexOf(style);
	if(idx >= 0) {
		stylesInsertedAtTop.splice(idx, 1);
	}
}

function createStyleElement (options) {
	var style = document.createElement("style");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}

	if(options.attrs.nonce === undefined) {
		var nonce = getNonce();
		if (nonce) {
			options.attrs.nonce = nonce;
		}
	}

	addAttrs(style, options.attrs);
	insertStyleElement(options, style);

	return style;
}

function createLinkElement (options) {
	var link = document.createElement("link");

	if(options.attrs.type === undefined) {
		options.attrs.type = "text/css";
	}
	options.attrs.rel = "stylesheet";

	addAttrs(link, options.attrs);
	insertStyleElement(options, link);

	return link;
}

function addAttrs (el, attrs) {
	Object.keys(attrs).forEach(function (key) {
		el.setAttribute(key, attrs[key]);
	});
}

function getNonce() {
	if (false) {}

	return __webpack_require__.nc;
}

function addStyle (obj, options) {
	var style, update, remove, result;

	// If a transform function was defined, run it on the css
	if (options.transform && obj.css) {
	    result = typeof options.transform === 'function'
		 ? options.transform(obj.css) 
		 : options.transform.default(obj.css);

	    if (result) {
	    	// If transform returns a value, use that instead of the original css.
	    	// This allows running runtime transformations on the css.
	    	obj.css = result;
	    } else {
	    	// If the transform function returns a falsy value, don't add this css.
	    	// This allows conditional loading of css
	    	return function() {
	    		// noop
	    	};
	    }
	}

	if (options.singleton) {
		var styleIndex = singletonCounter++;

		style = singleton || (singleton = createStyleElement(options));

		update = applyToSingletonTag.bind(null, style, styleIndex, false);
		remove = applyToSingletonTag.bind(null, style, styleIndex, true);

	} else if (
		obj.sourceMap &&
		typeof URL === "function" &&
		typeof URL.createObjectURL === "function" &&
		typeof URL.revokeObjectURL === "function" &&
		typeof Blob === "function" &&
		typeof btoa === "function"
	) {
		style = createLinkElement(options);
		update = updateLink.bind(null, style, options);
		remove = function () {
			removeStyleElement(style);

			if(style.href) URL.revokeObjectURL(style.href);
		};
	} else {
		style = createStyleElement(options);
		update = applyToTag.bind(null, style);
		remove = function () {
			removeStyleElement(style);
		};
	}

	update(obj);

	return function updateStyle (newObj) {
		if (newObj) {
			if (
				newObj.css === obj.css &&
				newObj.media === obj.media &&
				newObj.sourceMap === obj.sourceMap
			) {
				return;
			}

			update(obj = newObj);
		} else {
			remove();
		}
	};
}

var replaceText = (function () {
	var textStore = [];

	return function (index, replacement) {
		textStore[index] = replacement;

		return textStore.filter(Boolean).join('\n');
	};
})();

function applyToSingletonTag (style, index, remove, obj) {
	var css = remove ? "" : obj.css;

	if (style.styleSheet) {
		style.styleSheet.cssText = replaceText(index, css);
	} else {
		var cssNode = document.createTextNode(css);
		var childNodes = style.childNodes;

		if (childNodes[index]) style.removeChild(childNodes[index]);

		if (childNodes.length) {
			style.insertBefore(cssNode, childNodes[index]);
		} else {
			style.appendChild(cssNode);
		}
	}
}

function applyToTag (style, obj) {
	var css = obj.css;
	var media = obj.media;

	if(media) {
		style.setAttribute("media", media)
	}

	if(style.styleSheet) {
		style.styleSheet.cssText = css;
	} else {
		while(style.firstChild) {
			style.removeChild(style.firstChild);
		}

		style.appendChild(document.createTextNode(css));
	}
}

function updateLink (link, options, obj) {
	var css = obj.css;
	var sourceMap = obj.sourceMap;

	/*
		If convertToAbsoluteUrls isn't defined, but sourcemaps are enabled
		and there is no publicPath defined then lets turn convertToAbsoluteUrls
		on by default.  Otherwise default to the convertToAbsoluteUrls option
		directly
	*/
	var autoFixUrls = options.convertToAbsoluteUrls === undefined && sourceMap;

	if (options.convertToAbsoluteUrls || autoFixUrls) {
		css = fixUrls(css);
	}

	if (sourceMap) {
		// http://stackoverflow.com/a/26603875
		css += "\n/*# sourceMappingURL=data:application/json;base64," + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
	}

	var blob = new Blob([css], { type: "text/css" });

	var oldSrc = link.href;

	link.href = URL.createObjectURL(blob);

	if(oldSrc) URL.revokeObjectURL(oldSrc);
}


/***/ }),

/***/ "./node_modules/style-loader/lib/urls.js":
/*!***********************************************!*\
  !*** ./node_modules/style-loader/lib/urls.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports) {


/**
 * When source maps are enabled, `style-loader` uses a link element with a data-uri to
 * embed the css on the page. This breaks all relative urls because now they are relative to a
 * bundle instead of the current page.
 *
 * One solution is to only use full urls, but that may be impossible.
 *
 * Instead, this function "fixes" the relative urls to be absolute according to the current page location.
 *
 * A rudimentary test suite is located at `test/fixUrls.js` and can be run via the `npm test` command.
 *
 */

module.exports = function (css) {
  // get current location
  var location = typeof window !== "undefined" && window.location;

  if (!location) {
    throw new Error("fixUrls requires window.location");
  }

	// blank or null?
	if (!css || typeof css !== "string") {
	  return css;
  }

  var baseUrl = location.protocol + "//" + location.host;
  var currentDir = baseUrl + location.pathname.replace(/\/[^\/]*$/, "/");

	// convert each url(...)
	/*
	This regular expression is just a way to recursively match brackets within
	a string.

	 /url\s*\(  = Match on the word "url" with any whitespace after it and then a parens
	   (  = Start a capturing group
	     (?:  = Start a non-capturing group
	         [^)(]  = Match anything that isn't a parentheses
	         |  = OR
	         \(  = Match a start parentheses
	             (?:  = Start another non-capturing groups
	                 [^)(]+  = Match anything that isn't a parentheses
	                 |  = OR
	                 \(  = Match a start parentheses
	                     [^)(]*  = Match anything that isn't a parentheses
	                 \)  = Match a end parentheses
	             )  = End Group
              *\) = Match anything and then a close parens
          )  = Close non-capturing group
          *  = Match anything
       )  = Close capturing group
	 \)  = Match a close parens

	 /gi  = Get all matches, not the first.  Be case insensitive.
	 */
	var fixedCss = css.replace(/url\s*\(((?:[^)(]|\((?:[^)(]+|\([^)(]*\))*\))*)\)/gi, function(fullMatch, origUrl) {
		// strip quotes (if they exist)
		var unquotedOrigUrl = origUrl
			.trim()
			.replace(/^"(.*)"$/, function(o, $1){ return $1; })
			.replace(/^'(.*)'$/, function(o, $1){ return $1; });

		// already a full url? no change
		if (/^(#|data:|http:\/\/|https:\/\/|file:\/\/\/|\s*$)/i.test(unquotedOrigUrl)) {
		  return fullMatch;
		}

		// convert the url to a full url
		var newUrl;

		if (unquotedOrigUrl.indexOf("//") === 0) {
		  	//TODO: should we add protocol?
			newUrl = unquotedOrigUrl;
		} else if (unquotedOrigUrl.indexOf("/") === 0) {
			// path should be relative to the base url
			newUrl = baseUrl + unquotedOrigUrl; // already starts with '/'
		} else {
			// path should be relative to current directory
			newUrl = currentDir + unquotedOrigUrl.replace(/^\.\//, ""); // Strip leading './'
		}

		// send back the fixed url(...)
		return "url(" + JSON.stringify(newUrl) + ")";
	});

	// send back the fixed css
	return fixedCss;
};


/***/ })

/******/ });
//# sourceMappingURL=webVR.js.map